<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbc87e67ba09c822dd164ac218700497c
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Stripe\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Stripe\\' => 
        array (
            0 => __DIR__ . '/..' . '/stripe/stripe-php/lib',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbc87e67ba09c822dd164ac218700497c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbc87e67ba09c822dd164ac218700497c::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
