<?php
        /**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
*
 * Not edit this file.
 * Edit /resources/locale/ru.js
          */
return array(
            'Out work audio' => 'OUT WOOK AUDIO',
    'P2P CustomerSiteID' => 'P2P CombersentityID',
    'P2P KeyID' => 'P2P CeyID',
    'P2P Passphrase' => 'P2P пароль фраза',
    'P2P RecipientKeyID' => 'P2P RecentientkeyID',
    'QoR => ported number' => 'Qor => портированный номер',
    'Restrição' => 'Rensição.',
    'Round robin with memory, remember where we left off last ring pass' => 'Round Robin с памятью, помните, где мы остановились на последнем звонке',
    'SIP Call' => 'SIP Call.',
    'SIP Code' => 'SIP код',
    'SIP group' => 'SIP Group',
    'SIP pass' => 'SIP проход',
    'SIP password' => 'SIP пароль',
    'SIP user' => 'SIP пользователя',
    'SMS Text' => 'SMS текст',
    'SMTP' => 'SMTP.',
    'STUN Server' => 'Stun Server.',
    'Sendrpid' => 'Sendrpid.',
    'Sip user' => 'SIP пользователя',
    'SipProxy' => 'Sipproxy.',
    'SipShowPeer' => 'SipshowPeer.',
    'SipTrace' => 'Siptrace',
    'Spy call' => 'Spy Call.',
    'TLS' => 'TLS.',
    'TTS/ASR' => 'TTS / ASR',
    'Tech Prefix have a invalid length' => 'Tech Prefix имеет неверную длину',
    'Tech prefix' => 'Tech Prefix',
    'Toggle max completed calls' => 'Toggle Max Завершенные звонки',
    'URL to cancel email credit notification' => 'URL отменить уведомление по электронной почте',
    'Use_Pref_Codec' => 'Use_pref_codec.',
    'Voucher inexistente or already used' => 'Voucher Onlystleente или уже используется',
    'm/d/Y' => 'M / D / Y',

);