Help.load({
    //USERNAME 
    'user.username': 'User to client login into the panel.',
    'user.password': 'Pass to client login into the panel.',
    'user.id_group': 'There are 3 groups types: admin, agent and client. You can create or edit any of these groups. Each group can have specific permissions. Check the menu Configuration-User Group.',
    'user.id_group_agent': 'The group that agent\'s client will use.',
    'user.id_plan': 'Which plan will be used to bill calls for this user.',
    'user.prefix_local': 'Use it to allow your user dial local format. Rules description: The rules are comma separated, and each rule is composed for 3 values with / separated. The fist value is the number to match. The second is the number to replace. The third is the number length. The first number can be * to match any digit and add the second number on the beginning. Example to Brazil 0/55/11,*/5511/8,*/5511/9. RULE 1 -> number that start with 0 and length is 11 digits, replace 0 per 55. RULE 2 ->  number that start with any digit and length is 8, add 5511 on the beginning. RULE 3 ->  number that start with any digit and length is 9, add 5511 on the beginning .',
    'user.active': 'Only active users can login into the panel and make calls',
    'user.country': 'Used to CID Callback. The country prefix code will be added before the CID to convert the CID to format E164',
    'user.id_offer': 'Used to give free minutes. You need to add your package on the menu Rates Offer.',
    'user.cpslimit': 'How many Calls Per Seconds this user can send? The excess will receive CONGESTION.',
    'user.vat': 'Used with some payment gateways.',
    'user.typepaid': 'Where postpaid is necessary to add a credit limit.',
    'user.creditlimit': 'If the user is postpaid, the client will make calls until he reach this limit.',
    'user.credit_notification': 'If user credit is less then this value, MagnusBilling will try send an email. YOU NEED TO CONFIGURE SMTP.',
    'user.enableexpire': 'Enable the user to expire.',
    'user.expirationdate': 'The date that the user will expire and be deactivated.',
    'user.callshop': 'Activate the Callshop module. It is necessary to give permissions to this group.',
    'user.mix_monitor_format': 'Which format will used to record calls. Activate record on the Sip Account.',
    'user.disk_space': 'Insert the space available to record in GB. Use -1 to unlimit.',
    'user.calllimit': 'How many simultaneous calls this user can have? The excess will receive CONGESTION.',
    'user.calllimit_error': '',
    'user.sipaccountlimit': 'How many SipAccount this user can create. You need add permissions on the group to allow user create SipAccout. Or use Services menu to control permissions.',
    'user.callingcard_pin': 'Used to callingcard authentication.',
    'user.restriction': 'Used to restriction dial. Add the numbers in User menu, Restricted Numbers sub-menu.',
    //SIP ACCOUNT
    'sip.defaultuser': 'Username to login on the SIP device.',
    'sip.secret': 'Password to login on the SIP device.',
    'sip.callerid': 'The Caller ID number. Your trunk need accept CLI.',
    'sip.disallow': 'First disallow all codecs, and select below the codecs available to your user. G729 is not installed by default, because is commercial license.',
    'sip.host': 'Dynamic is to allow your user register his account from any IP. If you want authenticate via IP add the user IP here. REMEMBER TO AUTHENTICATE VIA IP -> remove password and set insecure to invite',
    'sip.group': 'Used to incomming call. Is used to ring more than one SIP account. You can create groups with any string.',
    'sip.block_call_reg': 'You can block call with regular expression. For example, you want block all call that start with 9. Use regex ^9 ',
    'sip.nat': 'Check this link https://www.voip-info.org/asterisk-sip-nat/',
    'sip.directmedia': 'If enable, Asterisk tries to redirect the RTP media stream to go directly from the caller to the callee.',
    'sip.qualify': 'Send OPTION to user CONTACT field to qualify the user.',
    'sip.context': 'Only change if you know you doing.',
    'sip.insecure': 'Need be NO if host is dynamic. To IP authentication set to invite.',
    'sip.allowtransfer': 'Enable it to allow trasnfers between SIP account ',
    'sip.ringfalse': 'If YES, generate a ringing tone for the calling party.',
    'sip.calllimit': 'Maximum simultaneous calls',
    'sip.dial_timeout': 'Timeout in seconds to wait the sip answer the call.',
    //ATA LIKKSYS/SIPURA
    'sipuras.nserie': 'Linksys serial number',
    'sipuras.macadr': 'Linksys MAC address',
    'sipuras.senha_user': 'User to add in LinkSys configuration',
    'sipuras.senha_admin': 'Pass to add in LinkSys configuration',
    'sipuras.antireset': 'Be careful. Avoid reset linksys with *73738#',
    'sipuras.Enable_Web_Server': 'Be careful. If disable, you can\'t more login on Linksys configuration',
    'sipuras.User_ID_1': 'SipAccount username',
    'sipuras.Password_1': 'SipAccount password',
    'sipuras.Use_Pref_Codec_Only_1': 'Only use the preference CODEC',
    'sipuras.Preferred_Codec_1': 'Set the preference CODEC',
    'sipuras.Register_Expires_1': 'Interval in seconds that the linksys send REGISTER to your server. Useful to avoid loss connection when you will receive call.',
    'sipuras.Dial_Plan_1': 'Read linkys documentation',
    'sipuras.NAT_Mapping_Enable_1_': '',
    'sipuras.NAT_Keep_Alive_Enable_1_': '',
    'sipuras.STUN_Enable': '',
    'sipuras.STUN_Test_Enable': '',
    'sipuras.Substitute_VIA_Addr': '',
    'sipuras.STUN_Server': '',
    //ONOINE CALLS
    'callonline.ndiscado': 'Dialed number',
    'callonline.callerid': 'The CID number.',
    'callonline.billsec': 'Time in seconds after call answered.',
    'callonline.codec': 'Codec used',
    'callonline.reinvite': 'If YES, mean the RTP audio was send directly between callee and caller',
    'callonline.from_ip': 'Ip of caller',
    //CALLERID
    'callerid.cid': 'The number to CID authenticate on CallingCard. Use the exact format that you receive the callerID from your DID provider.',
    //RESTRICTED NUMBERS
    'restrictedphonenumber.number': 'You can use the complete number or only one part. Example. if you select \'Only call for restricted numbers\' and add here the number 1360888777, this user can\'t call to this number. If you add only part of the number, like 1360, your user can\'t call to any number that start with 1360',
    //TOKEN
    'gauthenticator.googleAuthenticator_enable': 'After user active the seconds authenticate method, only be possible login into user panel or disable the token with the token or the manual code. If your lose both codes, contacts us.',
    //VOUCHER
    'voucher.credit': 'How much credit is this voucher?',
    'voucher.id_plan': 'Plan used to create user when voucher to be used',
    'voucher.language': 'Language used to create user when voucher to be used',
    'voucher.prefix_local': 'Local Prefix used to create user when voucher to be used',
    'voucher.quantity': 'How many voucher do you want generate?',
    //USER RATE
    'userrate.id_user': 'Select the client that you want replace tariff price.',
    'userrate.id_prefix': 'Select the prefix that you want replace the price.',
    'userrate.rateinitial': 'New price to above destination',
    'userrate.initblock': 'Initial block',
    'userrate.billingblock': 'increment block',
    //TRUNK
    'services.disk_space': 'Insert the space available to record in GB.',
    'trunk.trunkcode': '',
    'trunk.user': 'Only use if authentication is via user and pass.',
    'trunk.secret': 'Only use if authentication is via user and pass.',
    'trunk.host': 'IP or SIP',
    'trunk.trunkprefix': 'Add a prefix to send to your trunk.',
    'trunk.removeprefix': 'Remove a prefix to send to your trunk.',
    'trunk.allow': 'G723 and G729 are not installed.',
    'trunk.providertech': 'You need install appropriate drive to use card like dgv extra Dongle.',
    'trunk.status': 'If you inactive the Trunk, MagnusBilling will try send call to selectd Trunk backup',
    'trunk.allow_error': 'If YES, all call, less ANSWERED or CANCEL, will send to trunk backup',
    'trunk.register': 'You trunk need REGISTER? No try register trunk authenticated via IP',
    'trunk.register_string': '',
    'trunk.fromuser': 'Many SIP providers require this. Normally it is the some username',
    'trunk.fromdomain': 'Set the Trunk IP or SIP, if require this.',
    'trunk.language': '',
    'trunk.context': 'Only change if you know you doing.',
    'trunk.dtmfmode': 'Set default dtmfmode for sending DTMF. Default: rfc2833 Other options: info : SIP INFO messages (application/dtmf-relay) shortinfo : SIP INFO messages (application/dtmf) inband : Inband audio (requires 64 kbit codec -alaw, ulaw) auto : Use rfc2833 if offered, inband otherwise.',
    'trunk.insecure': '',
    'trunk.maxuse': 'Maximum simultaneous call. If you set it, your server need use many resources to control it. Not recommend.',
    'trunk.nat': '',
    'trunk.directmedia': '',
    'trunk.qualify': '',
    'trunk.type': '',
    'trunk.disallow': '',
    'trunk.addparameter': '',
    'trunk.link_sms': 'Post here your SMS link to send SMS. Replace: number variable per %number% and text per %text%. EXAMPLE. Your sms URL is http://trunkWebSite.com/sendsms.php?user=magnus&pass=billing&number=XXXXXX&sms_text=SSSSSSSSSSS. replace XXXXXX per %number and SSSSSSSSSSS per %text% ',
    'trunk.sms_res': 'Leave it empty to not wait URL result. If you want wait the any success message, write here the expected result.',
    'trunk.port': 'If you want use diferent of 5060, you will need open new port in IPTABLES.',
    'trunk.encryption': 'Whether to offer SRTP encrypted media (ONLY TO SRTP)',
    'trunk.transport': 'Enable TLS transport. Need install certificate on Asterisk',
    //TEMPLATE MAIL
    'templatemail.fromname': '',
    'templatemail.fromemail': '',
    'templatemail.subject': '',
    //SMTPS
    'smtps.host': 'YOU NEED CHECK IF YOU DATACENTER NOT BLOCK EMAIL PORTS',
    'smtps.username': '',
    'smtps.password': '',
    'smtps.port': '',
    'smtps.encryption': '',
    //SMS
    'sms.telephone': 'Need be in E164 format',
    'sms.sms': '',
    //SERVICES 
    'services.type': '',
    'services.name': '',
    'services.calllimit': '',
    'services.disk_space': '',
    'services.sipaccountlimit': '',
    'services.moneyfield': '',
    'services.textarea': '',
    //SERVICES USE
    'servicesuse.id': '',
    'servicesuse.price': '',
    'servicesuse.method': '',
    //SERVERS
    'servers.host': '',
    'servers.username': '',
    'servers.password': '',
    'servers.port': '',
    'servers.type': '',
    'servers.weight': '',
    'servers.status': '',
    'servers.description': '',
    //REFILL PROVIDER
    'refillprovider.credit': '',
    'refillprovider.description': '',
    'refillprovider.payment': '',
    //REFILL
    'refill.credit': '',
    'refill.description': '',
    'refill.payment': 'This option is only to your control, the credit will be released to user same if set to Payment NO',
    'refill.invoice_number': '',
    //RATE CALL SHOP
    'ratecallshop.dialprefix': '',
    'ratecallshop.destination': '',
    'ratecallshop.buyrate': '',
    'ratecallshop.minimo': '',
    'ratecallshop.block': '',
    'ratecallshop.minimal_time_charge': '',
    //RATE
    'rate.id_plan': 'The plan where you want add this tariff',
    'rate.id_prefix': 'Find the prefix that you want add a tariff',
    'rate.id_trunk': 'Select the trunk to send call that match with this tariff',
    'rate.buyrate': 'How much you pay per minute to your provider?',
    'rate.buyrateinitblock': 'Minimal time in seconds to buy cost. Ex: if set 30s and call duration is 10s, will charged 30s.',
    'rate.buyrateincrement': 'After the Minimal time, how is the increment. Ex: if set to 6s and call duration is 32s, will charged 36.',
    'rate.minimal_time_buy': '',
    'rate.rateinitial': 'How much do you want sell per minute?',
    'rate.initblock': 'Minimal time in seconds to sell. Ex: if set 30s and call duration is 21s, will charged 30s.',
    'rate.billingblock': 'After the Minimal sale, how is the increment. Ex: if set to 6s and call duration is 32s, will charged 36.',
    'rate.minimal_time_charge': '',
    'rate.additional_grace': 'Aditional time to add on call duration. Ex: the call duration 20s and you add here 3s, will be charged 23 seconds.',
    'rate.package_offer': 'Set to yes whether you want include this tariff on package offer',
    'rate.status': '',
    //QUEUE MEMBER
    'queuemember.queue_name': '',
    'queuemember.interface': '',
    'queuemember.paused': '',
    //QUEUE
    'queue.name': '',
    'queue.language': '',
    'queue.strategy': '',
    'queue.ringinuse': 'If you want the queue to avoid sending calls to agent whose devices are known to be \'in use\' set this option to NO. ',
    'queue.timeout': 'How long does that second member\'s phone ring',
    'queue.retry': 'Time in second to try another agent',
    'queue.wrapuptime': 'Time in secods to agent receive another call',
    'queue.weight': 'Weight of queue - when compared to other queues, higher weights get first shot at available channels when the same channel is included in more than one queue.',
    'queue.periodic-announce': 'A set of periodic announcements can be defined by separating. periodic announcements to reproduce by commas. For example:queue-periodic-announce,your-call-is-important,please-wait',
    'queue.periodic-announce-frequency': 'How often to make any periodic announcement',
    'queue.announce-position': 'Queue position announce?',
    'queue.announce-holdtime': 'Should we include estimated hold time in position announcements?',
    'queue.announce-frequency': 'How often to announce queue position and/or estimated holdtime to caller 0=off',
    'queue.joinempty': '',
    'queue.leavewhenempty': '',
    'queue.ring_or_moh': '',
    'queue.musiconhold': '',
    //PROVIDER
    'provider.provider_name': '',
    'provider.credit': '',
    'provider.credit_control': '',
    'provider.description': '',
    //PREFIX
    'prefix.prefix': '',
    'prefix.destination': '',
    //PLAN
    'plan.name': '',
    'plan.lcrtype': 'How will order the tariffs if found more than one tariff to the same prefix? Load balancer will use RAND function to balancer call between all found tariffs.',
    'plan.signup': 'Show this plan on signup form?',
    'plan.ini_credit': 'How much initial credit you want add to new users that select this plan on signup form?',
    'plan.play_audio': 'Execute audio like You not have enugh credit | destination unreachable. If inactive, MagnusBilling will send 603.',
    'plan.portabilidadeMobile': '',
    'plan.portabilidadeFixed': '',
    'plan.techprefix': 'This is like a code to any client use this plan. Example. User 12345 have plan Gold, alse he want send call to plan SILVER too. So, you can create plan SILVER and set a tech prefix ex. 77777, if client want call to 1360888777 with plan Gold dial normally 1360888777, or dial 777771360888777 if want to use plan SILVER.',
    //PHONE NUMBER
    'phonenumber.number': '',
    'phonenumber.name': '',
    'phonenumber.city': '',
    'phonenumber.status': '',
    'phonenumber.info': '',
    //PHONE BOOK
    'phonebook.name': '',
    'phonebook.status': '',
    'phonebook.description': '',
    //OFFER USE
    'offeruse.month_payed': '',
    'offeruse.reservationdate': '',
    //OFFER CDR
    'offercdr.used_secondes': '',
    'offercdr.date_consumption': '',
    //OFFER
    'offer.label': '',
    'offer.packagetype': '',
    'offer.freetimetocall': '',
    'offer.billingtype': '',
    'offer.price': '',
    //METHOD PAY
    'methodpay.payment_method': '',
    'methodpay.show_name': 'Name to show to user on Buy Credit option',
    'methodpay.id_user': '',
    'methodpay.country': 'Only to reference.',
    'methodpay.active': 'Activate this payment gateway to users?',
    'methodpay.min': 'How the minimum amount you want accept?',
    'methodpay.max': 'How the maximum amount you want accept?',
    'methodpay.username': '',
    'methodpay.url': '',
    'methodpay.fee': 'Release the paid amount less the Paypal fee.',
    'methodpay.boleto_banco': '',
    'methodpay.boleto_convenio': '',
    'methodpay.boleto_agencia': '',
    'methodpay.boleto_conta_corrente': '',
    'methodpay.boleto_inicio_nosso_numeroa': '',
    'methodpay.boleto_carteira': '',
    'methodpay.boleto_taxa': '',
    'methodpay.boleto_instrucoes': '',
    'methodpay.boleto_nome_emp': '',
    'methodpay.boleto_end_emp': '',
    'methodpay.boleto_cidade_emp': '',
    'methodpay.boleto_estado_emp': '',
    'methodpay.boleto_cpf_emp': '',
    'methodpay.pagseguro_TOKEN': '',
    'methodpay.P2P_CustomerSiteID': '',
    'methodpay.P2P_KeyID': '',
    'methodpay.P2P_Passphrase': '',
    'methodpay.P2P_RecipientKeyID': '',
    'methodpay.P2P_tax_amount': '',
    'methodpay.client_id': '',
    'methodpay.client_secret': '',
    //LOG USERS
    'logusers.id_log_actions': '',
    'logusers.ip': '',
    'logusers.description': '',
    //IVR
    'ivr.name': '',
    'ivr.monFriStart': 'Hour to start the weekly work interval',
    'ivr.monFriStop': 'Hour to stop the weekly work interval',
    'ivr.satStart': 'Hour to start the Saturday work interval',
    'ivr.satStop': 'Hour to start the Saturday work interval',
    'ivr.sunStart': 'Hour to start the Sunday work interval',
    'ivr.sunStop': 'Hour to start the Sunday work interval',
    'ivr.workaudio': 'Audio to execute when receive call between work interval',
    'ivr.noworkaudio': 'Audio to execute out work interval',
    //IAX
    'iax.username': '',
    'iax.secret': '',
    'iax.callerid': '',
    'iax.disallow': '',
    'iax.allow': '',
    'iax.host': '',
    'iax.nat': '',
    'iax.context': '',
    'iax.qualify': '',
    'iax.dtmfmode': '',
    'iax.insecure': '',
    'iax.type': '',
    'iax.calllimit': '',
    //GROUP USER GROUP
    'groupusergroup.name': '',
    //GROUP USER
    'groupuser.id': '',
    'groupuser.name': '',
    //FIREWALL
    'firewall.ip': '',
    'firewall.action': '',
    'firewall.description': '',
    //DID USE
    'diduse.reservationdate': '',
    //DID DESTINATION
    'diddestination.id_did': 'Select the DID that you want create new destination',
    'diddestination.activated': '',
    'diddestination.priority': 'You can create 5 destination to your DID. If try call to the priority 1 and receive error, Magnusbilling will try send call to destination priority two and so on. Onlu work with "Call SIP" type ',
    'diddestination.voip_call': '',
    'diddestination.destination': '',
    'diddestination.id_ivr': '',
    'diddestination.id_queue': '',
    'diddestination.id_sip': '',
    //DID
    'did.did': 'The number exact as coming in the conext. We recommend you ever use E164 format.',
    'did.connection_charge': 'Activation cost. Example: If \'Activation Cost\' is 5 and \'Monthly price\' is 10, will be removed 15 from user credit when you active the DID.',
    'did.fixrate': 'Monthly cost. This amount will be removed from user credit each month. The DID will be release whether user not have enough credit to pay the DID.',
    'did.activated': '',
    'did.connection_sell': 'This amount will be remove from user credit when the DID is answered.',
    'did.minimal_time_charge': '',
    'did.initblock': 'Minimal time in seconds to charge. Ex: if set 30s and call duration is 10s, will charge 30s.',
    'did.increment': 'After the Minimal time, how is the increment. Ex: if set to 6s and call duration is 32s, will charge 36.',
    'did.charge_of': '',
    'did.calllimit': 'Did simultaneous calls',
    'did.expression_1': 'User REGEX to able to bill the incomming call per CallerID(ANI). Ex. If you call to you DID and your number is 443432221234, suppose you want charge call that start with 44 0.1 than you can use the REGEX ^44, and Sell price per min 0.1',
    'did.selling_rate_1': 'Price per minute if match above regular expression',
    'did.block_expression_1': 'Set to yes to block call that callerid match with above regular expression',
    'did.send_to_callback_1': 'Send this call to CallBack if match with above regular expression',
    'did.expression_2': 'Like above, but you can use 3 REGEX to billing 3 diferent rules. Ex: on the first REGEX you want charge 0.1 to number that start with 44 and second rule charge 0.2 number that start with 447, use ^447 and Sell price per min 0.2',
    'did.selling_rate_2': '',
    'did.block_expression_2': '',
    'did.send_to_callback_2': '',
    'did.expression_3': 'You can try use REGEX in above 2 rules to get fixed and mobile, and in this rule set to *, get any number, and set to block call that match this expression. It avoid billing issues if callerid come with invalid format',
    'did.selling_rate_3': '',
    'did.block_expression_3': '',
    'did.send_to_callback_3': '',
    'did.cbr': 'Enable callback pro. Only work if DID destination is a QUEUE.',
    'did.cbr_ua': 'Try execute audio when receive call',
    'did.cbr_em': 'Try execute audio before answer call. Your DID provider need allow early media.',
    'did.TimeOfDay_monFri': 'For example, your company only will callback to callee if call is between 09-12PM and 02:06PM MON-FRY, between this time interval will try execute the workaudio and try callback to the callee. You can use many time interval with | separated',
    'did.TimeOfDay_sat': 'The same but to sat',
    'did.TimeOfDay_sun': 'The same but to sun',
    'did.workaudio': 'Audio to execute when receive call on the time interval',
    'did.noworkaudio': 'Audio to execute if call is out time interval',
    //CONFIGURATION
    'configuration.config_value': '',
    'configuration.config_description': '',
    //CAMPAIGN POLL INFO
    'campaignpollinfo.number': '',
    'campaignpollinfo.resposta': '',
    'campaignpollinfo.obs': '',
    //CAMPAIGN POLL
    'campaignpoll.name': '',
    'campaignpoll.repeat': '',
    'campaignpoll.request_authorize': '',
    'campaignpoll.digit_authorize': '',
    'campaignpoll.description': '',
    'campaignpoll.arq_audio': '',
    'campaignpoll.option0': '',
    'campaignpoll.option1': '',
    'campaignpoll.option2': '',
    'campaignpoll.option3': '',
    'campaignpoll.option4': '',
    'campaignpoll.option5': '',
    'campaignpoll.option6': '',
    'campaignpoll.option7': '',
    'campaignpoll.option8': '',
    'campaignpoll.option9': '',
    //CAMPAIGN
    'campaign.id_plan': '',
    'campaign.name': '',
    'campaign.status': '',
    'campaign.startingdate': '',
    'campaign.expirationdate': '',
    'campaign.type': '',
    'campaign.audio': '',
    'campaign.audio_2': '',
    'campaign.restrict_phone': '',
    'campaign.digit_authorize': '',
    'campaign.type_0': '',
    'campaign.extensions_0': '',
    'campaign.id_queue_0': '',
    'campaign.id_sip_0': '',
    'campaign.extension_0': '',
    'campaign.daily_start_time': '',
    'campaign.daily_stop_time': '',
    'campaign.monday': '',
    'campaign.tuesday': '',
    'campaign.wednesday': '',
    'campaign.thursday': '',
    'campaign.friday': '',
    'campaign.saturday': '',
    'campaign.sunday': '',
    'campaign.frequency': '',
    'campaign.nb_callmade': '',
    'campaign.enable_max_call': '',
    'campaign.secondusedreal': '',
    'campaign.description': '',
    'campaign.tts_audio': '',
    'campaign.tts_audio2': '',
    'campaign.asr_options': '',
    //CALL SUMMARY CALL SHOP
    'callsummarycallshop.sumsessiontime': '',
    'callsummarycallshop.sumprice': '',
    'callsummarycallshop.sumlucro': '',
    'callsummarycallshop.sumbuycost': '',
    'callsummarycallshop.sumnbcall': '',
    //CALL SUMMARY BY MONTH
    'callsummarybymonth.sumsessiontime': '',
    'callsummarybymonth.sumsessionbill': '',
    'callsummarybymonth.sumbuycost': '',
    'callsummarybymonth.sumlucro': '',
    'callsummarybymonth.sumnbcall': '',
    //CALL SUMMARY
    'callsummary.sumsessiontime': '',
    'callsummary.sumsessionbill': '',
    'callsummary.sumbuycost': '',
    'callsummary.sumlucro': '',
    'callsummary.sumnbcall': '',
    //CALLBACK
    'callback.exten': '',
    'callback.status': '',
    //CALL
    'call.calledstation': '',
    'call.sessiontime': '',
    'call.buycost': '',
    'call.sessionbill': '',
    'call.agent_bill': '',
    //BOLETO
    'boleto.payment': '',
    'boleto.status': '',
    'boleto.vencimento': '',
    'boleto.description': '',
});