Help.load({
    //API
    'api.id_user': `You need use the MagnusBilling API from https://github.com/magnussolution/magnusbilling-api-php. The username owner this API`,
    'api.api_key': `This apy key will be necessary to execute the API`,
    'api.api_secret': `This apy secret will be necessary to execute the API`,
    'api.status': `You can activete or inactivate this API`,
    'api.action': `Which action the user will have execute`,
    'api.api_restriction_ips': `What IPS you want allow access this API. Leave blank to allow any IP. It is very recomended set the IPS`,
    //CDR
    'call.starttime': ``,
    'call.src': ``,
    'call.callerid': ``,
    'call.calledstation': ``,
    'call.idPrefixdestination': ``,
    'call.idUserusername': ``,
    'call.idTrunktrunkcode': ``,
    'call.sessiontime': ``,
    'call.buycost': ``,
    'call.sessionbill': ``,
    'call.agent_bill': ``,
    'call.uniqueid': ``,
    //CALL ARCHIVE
    'callarchive.calledstation': ``,
    'callarchive.sessiontime': ``,
    'callarchive.buycost': ``,
    'callarchive.sessionbill': ``,
    'callarchive.agent_bill': ``,
    //CALLBACK
    'callback.id_user': ``,
    'callback.exten': ``,
    'callback.status': ``,
    //CALLERID
    'callerid.id_user': ``,
    'callerid.cid': `The number to CID authenticate with CallingCard. Use the exact format that you received the callerID from your DID provider.`,
    'callerid.activated': ``,
    //CALLS ONLINE
    'callonline.idUserusername': ``,
    'callonline.sip_account': ``,
    'callonline.idUsercredit': ``,
    'callonline.ndiscado': `Dialed number`,
    'callonline.codec': `Codec used`,
    'callonline.callerid': `The CID number.`,
    'callonline.tronco': ``,
    'callonline.reinvite': `If set to YES, means the RTP audio was sent directly between callee and caller`,
    'callonline.from_ip': `IP of the caller`,
    'callonline.description': ``,
    //BOOTHS REPORT
    'callshopcdr.id_user': ``,
    //SUMMARY PER DAY
    'callsummarycallshop.sumsessiontime': ``,
    'callsummarycallshop.sumprice': ``,
    'callsummarycallshop.sumlucro': ``,
    'callsummarycallshop.sumbuycost': ``,
    'callsummarycallshop.sumnbcall': ``,
    //SUMMARY DAY AGENT
    'callsummarydayagent.sumsessiontime': ``,
    'callsummarydayagent.sumsessionbill': ``,
    'callsummarydayagent.sumbuycost': ``,
    'callsummarydayagent.sumlucro': ``,
    'callsummarydayagent.sumnbcall': ``,
    //SUMMARY DAY TRUNK
    'callsummarydaytrunk.sumsessiontime': ``,
    'callsummarydaytrunk.sumsessionbill': ``,
    'callsummarydaytrunk.sumbuycost': ``,
    'callsummarydaytrunk.sumlucro': ``,
    'callsummarydaytrunk.sumnbcall': ``,
    //SUMMARY DAY USER
    'callsummarydayuser.sumsessiontime': ``,
    'callsummarydayuser.sumlucro': ``,
    'callsummarydayuser.sumnbcall': ``,
    //SUMMARY MONTH TRUNK
    'callsummarymonthtrunk.sumsessiontime': ``,
    'callsummarymonthtrunk.sumsessionbill': ``,
    'callsummarymonthtrunk.sumbuycost': ``,
    'callsummarymonthtrunk.sumlucro': ``,
    'callsummarymonthtrunk.sumnbcall': ``,
    //SUMMARY MONTH USER
    'callsummarymonthuser.sumsessiontime': ``,
    'callsummarymonthuser.sumlucro': ``,
    'callsummarymonthuser.sumnbcall': ``,
    //SUMMARY PER DAY
    'callsummaryperday.sumsessiontime': ``,
    'callsummaryperday.sumsessionbill': ``,
    'callsummaryperday.sumbuycost': ``,
    'callsummaryperday.sumlucro': ``,
    'callsummaryperday.sumnbcall': ``,
    'callsummaryperday.sumnbcallfail': ``,
    //SUMMARY PER MONTH
    'callsummarypermonth.sumsessiontime': ``,
    'callsummarypermonth.sumsessionbill': ``,
    'callsummarypermonth.sumbuycost': ``,
    'callsummarypermonth.sumlucro': ``,
    'callsummarypermonth.sumnbcall': ``,
    //SUMMARY PER TRUNK
    'callsummarypertrunk.sumsessiontime': ``,
    'callsummarypertrunk.sumsessionbill': ``,
    'callsummarypertrunk.sumbuycost': ``,
    'callsummarypertrunk.sumlucro': ``,
    'callsummarypertrunk.sumnbcall': ``,
    'callsummarypertrunk.sumnbcallfail': ``,
    //SUMMARY PER USER
    'callsummaryperuser.sumsessiontime': ``,
    'callsummaryperuser.sumlucro': ``,
    'callsummaryperuser.sumnbcall': ``,
    'callsummaryperuser.sumnbcallfail': ``,
    //CAMPAIGNS
    'campaign.id_user': ``,
    'campaign.id_plan': `What plan do you want to use to bill this campaign?`,
    'campaign.name': ``,
    'campaign.status': ``,
    'campaign.startingdate': `The campaign will start from this date.`,
    'campaign.expirationdate': `The campaign will stop in this date`,
    'campaign.type': ``,
    'campaign.audio': `Available to massive call. The audio needs to be compatible with Asterisk. The recomended format is GSM or WWAV(8k hz mono).`,
    'campaign.audio_2': `If you use TTS, the name will be executed between Audio and Audio2`,
    'campaign.restrict_phone': ``,
    'campaign.auto_reprocess': `If there are no active numbers in this campaign phone book, reactivates all pending numbers.`,
    'campaign.id_phonebook': `Select one or more phonebooks to to be used.`,
    'campaign.digit_authorize': `Do you want to forward the call after the audio?  E.g, if the callee presses 1, he gets sent to SIP account XXXX. Set Number to Forward = 1, Forward Type = SIP and select the SIP account to send the callee to. Set -1 to disable.`,
    'campaign.type_0': ``,
    'campaign.id_ivr_0': ``,
    'campaign.id_queue_0': ``,
    'campaign.id_sip_0': ``,
    'campaign.extension_0': ``,
    'campaign.daily_start_time': ``,
    'campaign.daily_stop_time': ``,
    'campaign.monday': ``,
    'campaign.tuesday': ``,
    'campaign.wednesday': ``,
    'campaign.thursday': ``,
    'campaign.friday': ``,
    'campaign.saturday': ``,
    'campaign.sunday': ``,
    'campaign.frequency': `How many numbers will be processed per minute?`,
    'campaign.max_frequency': ``,
    'campaign.nb_callmade': `Used to control the max completed calls.`,
    'campaign.enable_max_call': ``,
    'campaign.secondusedreal': `How many calls you want to send. You need the above parameters active to control it.`,
    'campaign.description': `Text to send to SMS. You can use %name% where you want to show the number name.`,
    'campaign.tts_audio': ``,
    'campaign.tts_audio2': ``,
    //CAMPAIGNS DASHBOARD
    'campaigndashboard.name': ``,
    //CALL PER MINUTES
    'campaignlog.total': ``,
    //POLLS
    'campaignpoll.id_campaign': ``,
    'campaignpoll.name': ``,
    'campaignpoll.repeat': ``,
    'campaignpoll.request_authorize': ``,
    'campaignpoll.digit_authorize': ``,
    'campaignpoll.arq_audio': ``,
    'campaignpoll.description': ``,
    'campaignpoll.option0': ``,
    'campaignpoll.option1': ``,
    'campaignpoll.option2': ``,
    'campaignpoll.option3': ``,
    'campaignpoll.option4': ``,
    'campaignpoll.option5': ``,
    'campaignpoll.option6': ``,
    'campaignpoll.option7': ``,
    'campaignpoll.option8': ``,
    'campaignpoll.option9': ``,
    //POLLS REPORTS
    'campaignpollinfo.number': ``,
    'campaignpollinfo.resposta': ``,
    //RESTRICT PHONE
    'campaignrestrictphone.number': ``,
    //CONFIGURATION
    'configuration.config_value': ``,
    'configuration.config_description': ``,
    //DIDS
    'did.did': `The exact number coming from the context. We recommend you to always use the E164 format.`,
    'did.activated': ``,
    'did.callerid': `Use this field to set a Callerid name, or leave blank to use the received callerid from the DID provider.`,
    'did.connection_charge': `Activation cost. E.`,
    'did.fixrate': ``,
    'did.connection_sell': ``,
    'did.minimal_time_charge': ``,
    'did.initblock': `Minimum time in seconds to buy. E.g., if set to 30s and the call duration is 10s, charged for 30s.`,
    'did.increment': `This defines how the time is incremented after the minimum. E.g, if set to 6s and call duration is 32s, charged for 36.`,
    'did.charge_of': ``,
    'did.calllimit': `DID simultaneous calls`,
    'did.description': ``,
    'did.expression_1': `Use REGEX to able to bill the incomming calls by CallerID(ANI). E.g, if you are calling your DID and your number is 443432221234, suppose you want to charge all calls that start with 44 for 0.1. Therefore you can use ^44, and Sell price per min 0.1.`,
    'did.selling_rate_1': `Price per minute if the number matches the above regular expression.`,
    'did.block_expression_1': `Set to yes to block calls that matches with the above regular expression`,
    'did.send_to_callback_1': `Send this call to CallBack if it matches with the above regular expression`,
    'did.expression_2': `Same as the field above but you can use 3 REGEXes to bill with 3 diferent rules. E.g, on the first REGEX you want to charge 0.1 for numbers that start with 44, the second rule charges 0.2 for numbers that start with 447. Therefore you can use ^447 and Sell price per min 0.2.`,
    'did.selling_rate_2': ``,
    'did.block_expression_2': ``,
    'did.send_to_callback_2': ``,
    'did.expression_3': ``,
    'did.selling_rate_3': ``,
    'did.block_expression_3': ``,
    'did.send_to_callback_3': ``,
    'did.cbr': `Enables CallBack Pro. Only works if DID destination is a QUEUE.`,
    'did.cbr_ua': `Tries to execute an audio when a call is received.`,
    'did.cbr_total_try': ``,
    'did.cbr_time_try': ``,
    'did.cbr_em': `Tries to execute an audio before the call is answered. Your DID provider needs to allow early media.`,
    'did.TimeOfDay_monFri': `E.g, your company will only callback to the callee if the call was in between 09-12PM and 02:06PM MON-FRY, between this time interval the workaudio is going to be played and then callback to the callee. You can use multiple time intervals with | separated.`,
    'did.TimeOfDay_sat': `The same but for Sat.`,
    'did.TimeOfDay_sun': `The same but for Sun.`,
    'did.workaudio': `Audio to execute when a call is received at the time interval.`,
    'did.noworkaudio': `Audio to execute when a call is received out of the time interval.`,
    //DID DESTINATION
    'diddestination.id_did': `Select the DID that you want create new destination for.`,
    'diddestination.id_user': ``,
    'diddestination.activated': ``,
    'diddestination.priority': `You can create 5 destinations to your DID. If a try to the priority 1 is made and a error is received, MagnusBilling will try to send a call to the next destination priority available. Only works with the "SIP call" type.`,
    'diddestination.voip_call': ``,
    'diddestination.destination': ``,
    'diddestination.id_ivr': ``,
    'diddestination.id_queue': ``,
    'diddestination.id_sip': ``,
    'diddestination.context': ``,
    //DIDS USE
    'diduse.id_user': ``,
    'diduse.id_did': ``,
    'diduse.reservationdate': ``,
    //FAIL2BAN
    'firewall.ip': ``,
    'firewall.action': ``,
    'firewall.description': ``,
    //TOKEN
    'gauthenticator.username': ``,
    'gauthenticator.googleAuthenticator_enable': `Enable/Disable Google Authenticator.`,
    'gauthenticator.code': ``,
    'gauthenticator.google_authenticator_key': ``,
    //GROUPMODULE
    'groupmodule.id_group': ``,
    'groupmodule.id_module': ``,
    //GROUP USERS
    'groupuser.name': ``,
    //GROUP TO ADMINS
    'groupusergroup.name': ``,
    'groupusergroup.user_prefix': ``,
    'groupusergroup.id_group': ``,
    //IAX USERS
    'iax.id_user': ``,
    'iax.username': ``,
    'iax.secret': ``,
    'iax.callerid': ``,
    'iax.disallow': ``,
    'iax.allow': ``,
    'iax.host': ``,
    'iax.nat': ``,
    'iax.context': ``,
    'iax.qualify': ``,
    'iax.dtmfmode': ``,
    'iax.insecure': ``,
    'iax.type': ``,
    'iax.calllimit': ``,
    //IVRS
    'ivr.name': ``,
    'ivr.id_user': ``,
    'ivr.monFriStart': `Time to start weekly work interval`,
    'ivr.satStart': ``,
    'ivr.sunStart': ``,
    'ivr.workaudio': `Audio to execute when a call is received in between work interval`,
    'ivr.noworkaudio': `Audio to execute when a call is received out of the work interval`,
    'ivr.option_0': ``,
    'ivr.option_1': ``,
    'ivr.option_2': ``,
    'ivr.option_3': ``,
    'ivr.option_4': ``,
    'ivr.option_5': ``,
    'ivr.option_6': ``,
    'ivr.option_7': ``,
    'ivr.option_8': ``,
    'ivr.option_9': ``,
    'ivr.option_10': ``,
    'ivr.direct_extension': `Makes the caller able to type the SIP account he wants to call directly. E.g, Press 1 to xxx, Press 2 to yyy or type the SIP account.`,
    'ivr.option_out_0': ``,
    'ivr.option_out_1': ``,
    'ivr.option_out_2': ``,
    'ivr.option_out_3': ``,
    'ivr.option_out_4': ``,
    'ivr.option_out_5': ``,
    'ivr.option_out_6': ``,
    'ivr.option_out_7': ``,
    'ivr.option_out_8': ``,
    'ivr.option_out_9': ``,
    'ivr.option_out_10': ``,
    //LOG USERS
    'logusers.id_user': ``,
    'logusers.id_log_actions': ``,
    'logusers.ip': ``,
    'logusers.description': ``,
    //PAYMENT METHODS
    'methodpay.show_name': `Name to show to user in the Buy Credit option.`,
    'methodpay.id_user': ``,
    'methodpay.country': ``,
    'methodpay.active': `Activate this payment gateway to users?`,
    'methodpay.min': ``,
    'methodpay.max': ``,
    'methodpay.username': ``,
    'methodpay.url': ``,
    'methodpay.fee': `Discount the Paypal fee from the paid amount.`,
    'methodpay.pagseguro_TOKEN': ``,
    'methodpay.P2P_CustomerSiteID': ``,
    'methodpay.P2P_KeyID': ``,
    'methodpay.P2P_Passphrase': ``,
    'methodpay.P2P_RecipientKeyID': ``,
    'methodpay.P2P_tax_amount': ``,
    'methodpay.client_id': ``,
    'methodpay.client_secret': ``,
    //MENUS
    'module.text': ``,
    'module.icon_cls': ``,
    'module.id_module': ``,
    'module.priority': ``,
    //OFFERS
    'offer.label': ``,
    'offer.packagetype': ``,
    'offer.freetimetocall': ``,
    'offer.billingtype': ``,
    'offer.price': ``,
    //OFFER CDR
    'offercdr.id_user': ``,
    'offercdr.id_offer': ``,
    'offercdr.used_secondes': ``,
    'offercdr.date_consumption': ``,
    //OFFER USE
    'offeruse.id_user': ``,
    'offeruse.id_offer': ``,
    'offeruse.month_payed': ``,
    'offeruse.reservationdate': ``,
    //PHONEBOOKS
    'phonebook.name': ``,
    'phonebook.status': ``,
    'phonebook.description': ``,
    //PHONENUMBERS
    'phonenumber.id_phonebook': ``,
    'phonenumber.number': `Number to send calls/sms. Use only E164 format`,
    'phonenumber.name': `Used to TTS and SMS`,
    'phonenumber.city': ``,
    'phonenumber.status': ``,
    'phonenumber.info': ``,
    //PLANS
    'plan.name': ``,
    'plan.signup': `Display this plan in the signup form?`,
    'plan.ini_credit': `How much initial credit do you want to add to new users that select this plan in signup form?`,
    'plan.play_audio': `Should the system execute audios li`,
    'plan.techprefix': ``,
    'plan.id_service': ``,
    //PREFIXES
    'prefix.prefix': `Prefix code. Prefix will be used to tariff and bill the calls.`,
    'prefix.destination': `Destination name.`,
    //PROVIDERS
    'provider.provider_name': `Provider name`,
    'provider.credit': `How much credit do you have in your provider account? This field is optional.`,
    'provider.credit_control': `If you set to YES and your provider credit is < 0, all trunks from this provider will be deactivated.`,
    'provider.description': ``,
    //QUEUES
    'queue.id_user': ``,
    'queue.name': ``,
    'queue.language': ``,
    'queue.strategy': ``,
    'queue.ringinuse': ``,
    'queue.timeout': `How long the phone will ring until timeout`,
    'queue.retry': `Time in seconds to try another agent.`,
    'queue.wrapuptime': `Time in seconds until the agent receives another call.`,
    'queue.weight': `Weight of queue - when compared to other queues, higher weights get the first try at available channels when the same channel is included in more than one queue.`,
    'queue.periodic-announce': `A set of periodic announcements can be created by separating each announcements to reproduce whit commas. E.g.: queue-periodic-announce,your-call-is-important,please-wait`,
    'queue.periodic-announce-frequency': `How often to make a periodic announcement.`,
    'queue.announce-position': `Queue position announce?`,
    'queue.announce-holdtime': `Should we include an estimated hold time in the position announcements?`,
    'queue.announce-frequency': `How often to announce queue position and/or estimated holdtime to caller 0=off`,
    'queue.joinempty': ``,
    'queue.leavewhenempty': ``,
    'queue.max_wait_time': `Maximum wait time on the queue`,
    'queue.max_wait_time_action': `SipAccount, IVR or QUEUE to send the caller if the maximum wait time is reached. Use: SIP/sip_account, QUEUE/queue_name or IVR/ivr_name.`,
    'queue.ring_or_moh': ``,
    'queue.musiconhold': ``,
    //QUEUES MEMBERS
    'queuemember.queue_name': ``,
    'queuemember.interface': ``,
    'queuemember.paused': ``,
    //TARIFFS
    'rate.id_plan': `The plan that you want to create a tariff for.`,
    'rate.id_prefix': `The prefix that you want create a tariff for.`,
    'rate.id_trunk_group': ``,
    'rate.rateinitial': `How much do you want to charge per minute?`,
    'rate.initblock': `Minimum time in seconds to buy. E.g., if set to 30s and the call duration is 21s, charged for 30s.`,
    'rate.billingblock': `This defines how the time is incremented after the minimum. E.g, if set to 6s and call duration is 32s, charged for 36.`,
    'rate.minimal_time_charge': ``,
    'rate.additional_grace': `Aditional time to add to call duration. Ex: the call duration 20s and you add here 3s, will be charged 23 seconds.`,
    'rate.package_offer': `Set to yes if you want to include this tariff to a package offer.`,
    'rate.status': ``,
    //BOOTHS TARIFFS
    'ratecallshop.dialprefix': ``,
    'ratecallshop.destination': ``,
    'ratecallshop.buyrate': ``,
    'ratecallshop.minimo': ``,
    'ratecallshop.block': ``,
    'ratecallshop.minimal_time_charge': ``,
    //PROVIDER RATES
    'rateprovider.id_provider': ``,
    'rateprovider.id_prefix': ``,
    'rateprovider.buyrate': ``,
    'rateprovider.buyrateinitblock': ``,
    'rateprovider.buyrateincrement': ``,
    'rateprovider.minimal_time_buy': ``,
    //REFILLS
    'refill.id_user': ``,
    'refill.credit': ``,
    'refill.description': ``,
    'refill.payment': `This setting is only to your control, the credit will be released to the user anyway if set to Payment NO`,
    'refill.invoice_number': ``,
    //REFILL PROVIDERS
    'refillprovider.id_provider': ``,
    'refillprovider.credit': ``,
    'refillprovider.description': ``,
    'refillprovider.payment': ``,
    //RESTRICTED NUMBER
    'restrictedphonenumber.id_user': ``,
    'restrictedphonenumber.number': ``,
    'restrictedphonenumber.direction': ``,
    //SEND CREDIT PRODUCTS
    'sendcreditproducts.country': ``,
    'sendcreditproducts.operator_name': ``,
    'sendcreditproducts.operator_id': ``,
    'sendcreditproducts.SkuCode': ``,
    'sendcreditproducts.product': ``,
    'sendcreditproducts.send_value': ``,
    'sendcreditproducts.wholesale_price': ``,
    'sendcreditproducts.provider': ``,
    'sendcreditproducts.status': ``,
    'sendcreditproducts.info': ``,
    //SEND CREDIT RATES
    'sendcreditrates.idProductcountry': ``,
    'sendcreditrates.idProductoperator_name': ``,
    'sendcreditrates.sell_price': ``,
    //SEND CREDIT SUMMARY
    'sendcreditsummary.id_user': ``,
    //SERVERS
    'servers.name': ``,
    'servers.host': ``,
    'servers.public_ip': ``,
    'servers.username': ``,
    'servers.password': ``,
    'servers.port': ``,
    'servers.sip_port': ``,
    'servers.type': ``,
    'servers.weight': ``,
    'servers.status': ``,
    'servers.description': ``,
    //SERVICES
    'services.type': ``,
    'services.name': ``,
    'services.calllimit': ``,
    'services.disk_space': `Insert the space available to record in GB.`,
    'services.sipaccountlimit': ``,
    'services.price': ``,
    'services.return_credit': `Return credit to the user if they cancel before the expiration date.`,
    'services.description': ``,
    //SERVICES USE
    'servicesuse.id_user': ``,
    'servicesuse.id_services': ``,
    'servicesuse.price': ``,
    'servicesuse.method': ``,
    'servicesuse.reservationdate': ``,
    //SIP USERS
    'sip.id_user': ``,
    'sip.defaultuser': `Username used to login in a SIP device.`,
    'sip.secret': `Password to login in a SIP device.`,
    'sip.callerid': `The Caller ID number. Your trunk needs to accept CLI.`,
    'sip.alias': `Alias to dial between sip accounts from the same AccountCode (company).`,
    'sip.disallow': `Disallow all codecs and then select the codecs available below to enable them to the user.`,
    'sip.allow': ``,
    'sip.host': ``,
    'sip.sip_group': ``,
    'sip.videosupport': ``,
    'sip.block_call_reg': `You can block calls with a regular expression. For example, if you want block all calls that start with a 9, use regex ^9 `,
    'sip.record_call': ``,
    'sip.techprefix': ``,
    'sip.nat': `Nat. Click here for more info|https://www.voip-info.org/asterisk-sip-nat/`,
    'sip.directmedia': `If enabled, Asterisk tries to redirect the RTP media stream to go directly from the caller to the callee.`,
    'sip.qualify': `Send OPTION to user CONTACT field to qualify the user.`,
    'sip.context': ``,
    'sip.dtmfmode': ``,
    'sip.insecure': `Needs to be NO if the host is dynamic. To IP authenticate set to invite.`,
    'sip.deny': ``,
    'sip.permit': ``,
    'sip.type': ``,
    'sip.allowtransfer': `Enable it to allow transfers between SIP accounts.`,
    'sip.ringfalse': `If YES, generate a ringing tone for the calling party.`,
    'sip.calllimit': `Maximum simultaneous calls`,
    'sip.mohsuggest': ``,
    'sip.url_events': ``,
    'sip.addparameter': ``,
    'sip.amd': ``,
    'sip.type_forward': ``,
    'sip.id_ivr': ``,
    'sip.id_queue': ``,
    'sip.id_sip': ``,
    'sip.extension': ``,
    'sip.dial_timeout': `Timeout in seconds to wait for the call to be picked-up.`,
    'sip.voicemail': ``,
    'sip.voicemail_email': ``,
    'sip.voicemail_password': ``,
    'sip.sipshowpeer': ``,
    //SIP TRACE
    'siptrace.head': ``,
    //ATA LINKSYS
    'sipuras.nserie': `LinkSys serial number`,
    'sipuras.macadr': `LinkSys MAC address`,
    'sipuras.senha_user': `User to set in LinkSys configuration`,
    'sipuras.senha_admin': `Pass to set in LinkSys configuration`,
    'sipuras.antireset': `Prevent resetting LinkSys with *73738#`,
    'sipuras.Enable_Web_Server': `Enabling/Disabling LinkSys configuration WebPage`,
    'sipuras.marca': ``,
    'sipuras.altera': ``,
    'sipuras.User_ID_1': `SIP account username`,
    'sipuras.Password_1': `SIP account password`,
    'sipuras.Use_Pref_Codec_Only_1': `Only use the preferred CODEC`,
    'sipuras.Preferred_Codec_1': `Set the preferred CODEC`,
    'sipuras.Register_Expires_1': `Interval in seconds that LinkSys will send a REGISTER to your server. Useful to avoid a loss of connection when you receive a call.`,
    'sipuras.Dial_Plan_1': `Read LinkSys documentation`,
    'sipuras.NAT_Mapping_Enable_1_': ``,
    'sipuras.NAT_Keep_Alive_Enable_1_': ``,
    'sipuras.User_ID_2': ``,
    'sipuras.Password_2': ``,
    'sipuras.Use_Pref_Codec_Only_2': ``,
    'sipuras.Preferred_Codec_2': ``,
    'sipuras.Register_Expires_2': ``,
    'sipuras.Dial_Plan_2': ``,
    'sipuras.NAT_Mapping_Enable_2_': ``,
    'sipuras.NAT_Keep_Alive_Enable_2_': ``,
    'sipuras.STUN_Enable': ``,
    'sipuras.STUN_Test_Enable': ``,
    'sipuras.Substitute_VIA_Addr': ``,
    'sipuras.STUN_Server': ``,
    //SMS
    'sms.id_user': ``,
    'sms.telephone': `Needs to be in E164 format`,
    'sms.sms': ``,
    'sms.sms_from': ``,
    //SMTP
    'smtps.host': ``,
    'smtps.username': ``,
    'smtps.password': ``,
    'smtps.port': ``,
    'smtps.encryption': ``,
    //EMAILS TEMPLATES
    'templatemail.fromname': ``,
    'templatemail.fromemail': ``,
    'templatemail.subject': ``,
    'templatemail.messagehtml': ``,
    //TRUNKS
    'trunk.id_provider': ``,
    'trunk.trunkcode': ``,
    'trunk.user': `Only used if the authentication is via user and pass.`,
    'trunk.secret': `Only used if the authentication is via user and pass.`,
    'trunk.host': `IP or SIP`,
    'trunk.trunkprefix': `Add a prefix to send to your trunk.`,
    'trunk.removeprefix': `Remove a prefix to send to your trunk.`,
    'trunk.allow': `Select the codecs that are allowed in this trunk.`,
    'trunk.providertech': `You need install appropriate drive to use card like dgv extra Dongle.`,
    'trunk.status': ``,
    'trunk.allow_error': `If YES all calls but ANSWERED and CANCEL will be sent to a backup trunk.`,
    'trunk.register': ``,
    'trunk.register_string': ``,
    'trunk.fromuser': ``,
    'trunk.fromdomain': `Set the Trunk IP or SIP, if required.`,
    'trunk.language': ``,
    'trunk.context': `Only change if you know what you are doing.`,
    'trunk.dtmfmode': `Set default dtmfmode for sending DTMF. Default: rfc2833 Other options: info : SIP INFO messages (application/dtmf-relay) shortinfo : SIP INFO messages (application/dtmf) inband : Inband audio (requires 64 kbit codec -alaw, ulaw) auto : Use rfc2833 if offered, inband otherwise.`,
    'trunk.insecure': ``,
    'trunk.maxuse': `Maximum simultaneous call. If you set it, your server will need to use a lot of resources to control it. Not recommended.`,
    'trunk.nat': ``,
    'trunk.directmedia': ``,
    'trunk.qualify': ``,
    'trunk.type': ``,
    'trunk.disallow': ``,
    'trunk.sendrpid': ``,
    'trunk.addparameter': ``,
    'trunk.port': `If you want to use a different than 5060, you will need open the port in IPTABLES.`,
    'trunk.link_sms': `Set your SMS link here to send SMS. Replace: number variable per %number% and text per %text%. EXAMPLE. Your SMS URL is http://trunkWebSite.com/sendsms.php?user=magnus&pass=billing&number=XXXXXX&sms_text=SSSSSSSSSSS. replace XXXXXX per %number and SSSSSSSSSSS per %text% `,
    'trunk.sms_res': `Leave it empty to not wait URL result. If you want wait the any success message, write here the expected result.`,
    'trunk.sip_config': ``,
    //TRUNK GROUPS
    'trunkgroup.name': ``,
    'trunkgroup.type': ``,
    'trunkgroup.id_trunk': ``,
    //USERS
    'user.username': `Username used to login into the panel.`,
    'user.password': `Password used to login into the panel.`,
    'user.id_group': `There are 3 groups: admin, agent and client. You can create more or edit any of these groups. Each group can have specific permissions. Check the menu Configuration->User Group.`,
    'user.id_group_agent': ``,
    'user.id_plan': `Which plan will be used to bill calls for this user.`,
    'user.language': ``,
    'user.prefix_local': `Prefix rules. Click here for more info|https://www.magnusbilling.org/local_prefix`,
    'user.active': `Only active users can login into the panel and make calls`,
    'user.country': `Used to CID Callback. The country prefix code will be added before the CID to convert the CID to E164`,
    'user.id_offer': `Used to give free minutes. You need to add your package in the menu: Rates->Offer.`,
    'user.cpslimit': `How many Calls Per Second this user can send? The excess will receive CONGESTION.`,
    'user.company_name': ``,
    'user.state_number': ``,
    'user.lastname': ``,
    'user.firstname': ``,
    'user.city': ``,
    'user.state': ``,
    'user.address': ``,
    'user.neighborhood': ``,
    'user.zipcode': ``,
    'user.phone': ``,
    'user.mobile': ``,
    'user.email': ``,
    'user.doc': ``,
    'user.vat': `Used with some payment gateways.`,
    'user.typepaid': ``,
    'user.creditlimit': `If the user is Post-paid, the user will be able to make calls until he reaches this limit.`,
    'user.credit_notification': ``,
    'user.enableexpire': `Makes the user expire at a determined date.`,
    'user.expirationdate': `The date that the user will expire and be deactivated.`,
    'user.record_call': ``,
    'user.mix_monitor_format': `What format will used to record calls. Activate recording in the menu: Users->SIP accounts.`,
    'user.calllimit': `How many simultaneous calls this user can have? The excess will receive CONGESTION.`,
    'user.calllimit_error': ``,
    'user.callshop': ``,
    'user.disk_space': `Insert the amount disk space available to record, in GB. Use -1 to remove the limit.`,
    'user.sipaccountlimit': ``,
    'user.callingcard_pin': `Used to authenticate through CallingCard.`,
    'user.restriction': `Used to restrict dialing. Add the numbers in the menu: Users->Restricted numbers.`,
    'user.transfer_international_profit': ``,
    'user.transfer_flexiload_profit': ``,
    'user.transfer_bkash_profit': ``,
    'user.transfer_dbbl_rocket': ``,
    'user.transfer_dbbl_rocket_profit': ``,
    'user.transfer_show_selling_price': ``,
    //USER CUSTOM RATES
    'userrate.id_prefix': `Select the prefix that you want set the price.`,
    'userrate.rateinitial': `Sell price`,
    'userrate.initblock': `Initial block`,
    'userrate.billingblock': `Increment block`,
    //VOUCHER
    'voucher.credit': `How much credit is this voucher worth?`,
    'voucher.id_plan': `Select the plan that is going to be used to create the user when the voucher is redeemed.`,
    'voucher.language': `Language used to create the user when voucher when the voucher is redeemed.`,
    'voucher.prefix_local': `Local Prefix used to the create user when the voucher is redeemed.`,
    'voucher.quantity': `How many vouchers do you want to generate?`,
    'voucher.tag': ``,
    'voucher.voucher': ``,
});