Help.load({
    //API
    'api.id_user': `You need use the MagnusBilling API from https://github.com/magnussolution/magnusbilling-api-php. The username owner this API`,
    'api.api_key': `This apy key will be necessary to execute the API`,
    'api.api_secret': `This apy secret will be necessary to execute the API`,
    'api.status': `You can activete or inactivate this API`,
    'api.action': `Which action the user will have execute`,
    'api.api_restriction_ips': `What IPS you want allow access this API. Leave blank to allow any IP. It is very recomended set the IPS`,
    //CDR
    'call.starttime': `Start time of the call`,
    'call.src': `SIP Account that made the call`,
    'call.callerid': `Number sent to the trunk as the identifier of the call.||
    If the trunk accepts the sent CallerID, then this number will be used as the identifier.
    In order to this work its going to be necessary to have the Fromuser field in the trunk empty.`,
    'call.calledstation': `Number dialed by the client.`,
    'call.idPrefixdestination': `Name of the destination, this name is a relation to the prefix menu.`,
    'call.idUserusername': `User that made the call, the one who the call cost was taken from.`,
    'call.idTrunktrunkcode': `Trunk that was used to complete the call.`,
    'call.sessiontime': `Duration of the call in seconds.`,
    'call.buycost': `Buy cost. Click to understand how the cost is calculated|https://wiki.magnusbilling.org/en/source/price_calculation.html.`,
    'call.sessionbill': `Sell price, the value that was taken from the client. Click to understand how the cost is calculated|https://wiki.magnusbilling.org/en/source/price_calculation.html.`,
    'call.agent_bill': `Sell price, the value that was taken from the client. Click to understand how the cost is calculated|https://wiki.magnusbilling.org/en/source/price_calculation.html.`,
    'call.uniqueid': `Unique ID generated by Asterisk, this field is also the start time of the call in Epoch Unix.`,
    //CALL ARCHIVE
    'callarchive.calledstation': `Number dialed by the client.`,
    'callarchive.sessiontime': `Duration of the call in seconds.`,
    'callarchive.buycost': `Buy cost. Click to understand how the cost is calculated|https://wiki.magnusbilling.org/en/source/price_calculation.html`,
    'callarchive.sessionbill': `Buy cost. Click to understand how the cost is calculated|https://wiki.magnusbilling.org/en/source/price_calculation.html`,
    'callarchive.agent_bill': `Buy cost. Click to understand how the cost is calculated|https://wiki.magnusbilling.org/en/source/price_calculation.html`,
    //CALLBACK
    'callback.id_user': `Owner of the DID that received the CallBack request.`,
    'callback.exten': `Number of who called the DID requesting the CallBack`,
    'callback.status': `Status of the call||The statuses are:
    * Active
        The CallBack still hasn't been processed.
    * Pending
        MagnusBilling processed the CallBack and sent it to the trunk.
    * Sent
        The CallBack has been processed successfully.
    * Outside of the time range
        The call was received outside of the time range configured in the DID menu, tab CallBack Pro.
    .`,
    //CALLERID
    'callerid.id_user': `Select user.`,
    'callerid.cid': `The number to CID authenticate with CallingCard. Use the exact format that you received the CallerID from your DID provider.`,
    'callerid.name': `Optional.`,
    'callerid.activated': `Status of the CallerID.`,
    //CALLS ONLINE
    'callonline.idUserusername': `Main user of the SIP account that started the call.`,
    'callonline.sip_account': `SIP Account that requested the call.`,
    'callonline.idUsercredit': `User credit.`,
    'callonline.ndiscado': `Dialed number.`,
    'callonline.codec': `Codec used.`,
    'callonline.callerid': `The CallerID number.`,
    'callonline.tronco': `Trunk that was used to complete the call.`,
    'callonline.reinvite': `Reinvite is the parameter that informs if the audio is passing through Asterisk or if its going through the client and trunk. Click to learn more about this option|https://wiki.magnusbilling.org/en/source/asterisk_options/directmedia.html.`,
    'callonline.from_ip': `IP of the caller.`,
    'callonline.description': `Data from the sip show channel command.`,
    //BOOTHS REPORT
    'callshopcdr.id_user': `User.`,
    //SUMMARY PER DAY
    'callsummarycallshop.sumsessiontime': `Sum of call minutes.`,
    'callsummarycallshop.sumprice': `Total value.`,
    'callsummarycallshop.sumlucro': `Sum of the earnings.`,
    'callsummarycallshop.sumbuycost': `Sum of the buy cost.`,
    'callsummarycallshop.sumnbcall': `Total of calls.`,
    //SUMMARY DAY AGENT
    'callsummarydayagent.sumsessiontime': `Sum of call minutes.||Its possible to use filters like showing only the last few days of the week or a specific reseller. This summary will only show the data related to the filter made.`,
    'callsummarydayagent.sumsessionbill': `Sum of the sell price.`,
    'callsummarydayagent.sumbuycost': `Sum of the buy cost.`,
    'callsummarydayagent.sumlucro': `Sum of the earnings.`,
    'callsummarydayagent.sumnbcall': `Total of calls.`,
    //SUMMARY DAY TRUNK
    'callsummarydaytrunk.sumsessiontime': `Sum of call minutes.||Its possible to use filters like showing only the last few days of the week or a specific reseller. This summary will only show the data related to the filter made.`,
    'callsummarydaytrunk.sumsessionbill': `Sum of the sell price.`,
    'callsummarydaytrunk.sumbuycost': `Sum of the buy cost.`,
    'callsummarydaytrunk.sumlucro': `Sum of the earnings.`,
    'callsummarydaytrunk.sumnbcall': `Total of calls.`,
    //SUMMARY DAY USER
    'callsummarydayuser.sumsessiontime': `Sum of call minutes.||Its possible to use filters like showing only the last few days of the week or a specific reseller. This summary will only show the data related to the filter made.`,
    'callsummarydayuser.sumlucro': `Sum of the earnings.`,
    'callsummarydayuser.sumnbcall': `Total of calls.`,
    //SUMMARY MONTH TRUNK
    'callsummarymonthtrunk.sumsessiontime': `Sum of call minutes.||Its possible to use filters like showing only the last few days of the week or a specific reseller. This summary will only show the data related to the filter made.`,
    'callsummarymonthtrunk.sumsessionbill': `Sum of the sell price.`,
    'callsummarymonthtrunk.sumbuycost': `Sum of the buy cost.`,
    'callsummarymonthtrunk.sumlucro': `Sum of the earnings.`,
    'callsummarymonthtrunk.sumnbcall': `Total of calls.`,
    //SUMMARY MONTH USER
    'callsummarymonthuser.sumsessiontime': `Sum of call minutes.||Its possible to use filters like showing only the last few days of the week or a specific reseller. This summary will only show the data related to the filter made.`,
    'callsummarymonthuser.sumlucro': `Sum of the earnings.`,
    'callsummarymonthuser.sumnbcall': `Total of calls.`,
    //SUMMARY PER DAY
    'callsummaryperday.sumsessiontime': `Sum of call minutes.||Its possible to use filters like showing only the last few days of the week or a specific reseller. This summary will only show the data related to the filter made.`,
    'callsummaryperday.sumsessionbill': `Sum of the sell price.`,
    'callsummaryperday.sumbuycost': `Sum of the buy cost.`,
    'callsummaryperday.sumlucro': `Sum of the earnings.`,
    'callsummaryperday.sumnbcall': `Total of calls.`,
    'callsummaryperday.sumnbcallfail': `Total of calls that failed.`,
    //SUMMARY PER MONTH
    'callsummarypermonth.sumsessiontime': `Sum of call minutes.||Its possible to use filters like showing only the last few days of the week or a specific reseller. This summary will only show the data related to the filter made.`,
    'callsummarypermonth.sumsessionbill': `Sum of the sell price.`,
    'callsummarypermonth.sumbuycost': `Sum of the buy cost.`,
    'callsummarypermonth.sumlucro': `Sum of the earnings.`,
    'callsummarypermonth.sumnbcall': `Total of calls.`,
    //SUMMARY PER TRUNK
    'callsummarypertrunk.sumsessiontime': `Sum of call minutes.||Its possible to use filters like showing only the last few days of the week or a specific reseller. This summary will only show the data related to the filter made.`,
    'callsummarypertrunk.sumsessionbill': `Sum of the sell price.`,
    'callsummarypertrunk.sumbuycost': `Sum of the buy cost.`,
    'callsummarypertrunk.sumlucro': `Sum of the earnings.`,
    'callsummarypertrunk.sumnbcall': `Total of calls.`,
    'callsummarypertrunk.sumnbcallfail': `Total of calls that failed.`,
    //SUMMARY PER USER
    'callsummaryperuser.sumsessiontime': `Sum of call minutes.||Its possible to use filters like showing only the last few days of the week or a specific reseller. This summary will only show the data related to the filter made.`,
    'callsummaryperuser.sumlucro': `Sum of the earnings.`,
    'callsummaryperuser.sumnbcall': `Total of calls.`,
    'callsummaryperuser.sumnbcallfail': `Total of calls that failed.`,
    //CAMPAIGNS
    'campaign.id_user': `User that owns the campaign.`,
    'campaign.id_plan': `What plan do you want to use to bill this campaign?`,
    'campaign.name': `Name of the campaign.`,
    'campaign.status': `Status of the campaign.`,
    'campaign.startingdate': `The campaign will start from this date.`,
    'campaign.expirationdate': `The campaign will stop in this date.`,
    'campaign.type': `Choose Voice or SMS. If you choose Voice you will need to import audio. If you choose SMS you will need to set the text in the SMS tab.`,
    'campaign.audio': `Available to massive calling. The audio needs to be compatible with Asterisk. The recomended format is GSM or WAV(8k hz mono).`,
    'campaign.audio_2': `If you use TTS, the name will be executed between Audio and Audio2.`,
    'campaign.restrict_phone': ``,
    'campaign.auto_reprocess': `If there are no active numbers in this campaign phone book, reactivates all pending numbers.`,
    'campaign.id_phonebook': `Select one or more phonebooks to to be used.`,
    'campaign.digit_authorize': `Do you want to forward the call after the audio?  E.g, if the callee presses 1, he gets sent to SIP account XXXX. Set Number to Forward = 1, Forward Type = SIP and select the SIP account to send the callee to. Set -1 to disable.`,
    'campaign.type_0': `Choose the type of redirect. This will send the call to the chosen destination.`,
    'campaign.id_ivr_0': `Choose a IVR to send the call to. The IVR needs to belong to the owner of the campaign.`,
    'campaign.id_queue_0': `Choose a Queue to send the call to. The Queue needs to belong to the owner of the campaign.`,
    'campaign.id_sip_0': `Choose a SIP Account to send the call to. The SIP Account needs to belong to the owner of the campaign.`,
    'campaign.extension_0': `Click for more details||There are two options available.
    *Group, the group name should be put here exactly as it is in the SIP Accounts that should receive the calls.
    *Personalized, you may execute any valid option via Asterisk's DIAL command. Example: SIP/sipaccount,45,tTr.`,
    'campaign.daily_start_time': `Time that the campaign will start sending.`,
    'campaign.daily_stop_time': `Time that the campaign will stop sending.`,
    'campaign.monday': `Activating this option the system will send calls on Mondays.`,
    'campaign.tuesday': `Activating this option the system will send calls on Tuesdays.`,
    'campaign.wednesday': `Activating this option the system will send calls on Wednesdays.`,
    'campaign.thursday': `Activating this option the system will send calls on Thursdays.`,
    'campaign.friday': `Activating this option the system will send calls on Fridays.`,
    'campaign.saturday': `Activating this option the system will send calls on Saturdays.`,
    'campaign.sunday': `Activating this option the system will send calls on Sundays.`,
    'campaign.frequency': `How many numbers will be processed per minute?||This value will be divided by 60 seconds and the calls will be sent every minute at the same time.`,
    'campaign.max_frequency': `This is the maximum value that the client will be able to set. If you set it to 50 the user will be able to change to any value that is 50 or less than 50.`,
    'campaign.nb_callmade': `Used to control the max completed calls.`,
    'campaign.enable_max_call': `If activated MagnusBilling will check how many calls were already made and have a duration total bigger than the audios. If the quantity is equal or bigger than the value set in the field, the campaign will be deactivated.`,
    'campaign.secondusedreal': `Maximum amount of complete calls. You need to activate the field above to use this.`,
    'campaign.description': `This field has different uses if the campaign is sending Voice or SMS.||Uses:
    * Voice: This field is simply a description of the campaign.
    * SMS: The text in here is going to be sent to the numbers. You may use the var %name% where you want to use the name of the customer. Example:
    Hello %name%`,
    'campaign.tts_audio': `With this setting the system will generate the audio 1 for the campaign via TTS.||In order for this to work, you will need to set the TTS URL under Settings, Configuration, TTS URL.`,
    'campaign.tts_audio2': `Same setting as the previous field but for audio 2. Keep in mind that in between audio 1 and 2, the TTS executes the name imported with the number.`,
    'campaign.record_call': `Record the calls of the campaign. They only will be recorded if the call is transferred.`,
    //CAMPAIGNS DASHBOARD
    'campaigndashboard.name': `Name of the campaign.`,
    //CALL PER MINUTES
    'campaignlog.total': `Total of calls.`,
    //POLLS
    'campaignpoll.id_campaign': `Choose the campaign that will execute this poll.`,
    'campaignpoll.name': `Name of the poll. This name is seen on your end only.`,
    'campaignpoll.repeat': `How many times should MagnusBilling repeat the poll audio if the client didn't press any valid option.||You may check what are the options under the option tab.`,
    'campaignpoll.request_authorize': `In some cases, you will need to request for compliance in order to execute the poll. If that's the case, select Yes.`,
    'campaignpoll.digit_authorize': `Digit to authorize the excution of the poll.`,
    'campaignpoll.arq_audio': `Audio file. Please use a GSM or WAV 8khz mono audio file.`,
    'campaignpoll.description': `Description of the poll.`,
    'campaignpoll.option0': `Describe the option||Example poll:
    Who will you vote for?
    Press 1 for option one
    Press 2 for option two
    Press 3 for option three
    
    .. image:: ../img/poll_options.png
    :scale: 100% 
    
    These settings will be useful when reading the poll summary.

    `,
    'campaignpoll.option1': `Describe the option. Read the description of option 0.`,
    'campaignpoll.option2': `Describe the option. Read the description of option 0.`,
    'campaignpoll.option3': `Describe the option. Read the description of option 0.`,
    'campaignpoll.option4': `Describe the option. Read the description of option 0.`,
    'campaignpoll.option5': `Describe the option. Read the description of option 0.`,
    'campaignpoll.option6': `Describe the option. Read the description of option 0.`,
    'campaignpoll.option7': `Describe the option. Read the description of option 0.`,
    'campaignpoll.option8': `Describe the option. Read the description of option 0.`,
    'campaignpoll.option9': `Describe the option. Read the description of option 0.`,
    //POLLS REPORTS
    'campaignpollinfo.number': `Number of the person who voted.`,
    'campaignpollinfo.resposta': `Option chosen.`,
    //RESTRICT PHONE
    'campaignrestrictphone.number': `Number that should be blocked. Its necessary to activate the blocked numbers option in the campaign.`,
    //CONFIGURATION
    'configuration.config_value': `Value. Click here to read more about the options of this menu.|https://wiki.magnusbilling.org/en/source/config.html.`,
    'configuration.config_description': `Description. Click here to read more about the options of this menu.|https://wiki.magnusbilling.org/en/source/config.html`,
    //DIDS
    'did.did': `The exact number coming from the context in Asterisk. We recommend you to always use the E164 format. Also you can create intervals. Example 13605040001-13605040009. In this example will be created the DIDs 13605040001 until  13605040009.`,
    'did.activated': `Only active numbers can receive calls.`,
    'did.callerid': `Use this field to set a CallerID name or leave it blank to use the received CallerID from the DID provider.`,
    'did.connection_charge': `Activation cost. This value will be deducted from the client the moment that the DID is associated with the user.`,
    'did.fixrate': `Monthly price. This value will be deducted automatically every month from the user's balance. If the client doesn't have enough credit the DID will be cancelled automatically.`,
    'did.connection_sell': `This is the value that will be charged for each call. Simply by picking up the call, this value will be deducted.`,
    'did.minimal_time_charge': `Minimum time to tariff the DID. If you set it to 3 any call that with lower duration will not be charged for.`,
    'did.initblock': `Minimum time in seconds to buy. If you set it to 30 and the call duration is 10, the call will be billed as 30.`,
    'did.increment': `This defines the block in which the call billing time will be incremented, in seconds. If set to 6 and call duration is 32, the call will be billed as 36.`,
    'did.charge_of': `The user that will be charged for the DID cost.`,
    'did.calllimit': `Maximum simultaneous calls for this DID.`,
    'did.description': `Set here the destination!`,
    'did.expression_1': `This is a regular expression to tariff the DID depending on who is calling it.||Lets analyze a real example:
    Suppose we want to charge 0.10 when we receive a call from a landline and 0.20 if its a mobile phone and block any other format.
    In this example we will create rules to identify the CallerID in the format 0 + area code + number, area code + number, or 55 + area code + number.

    Take a look at the following image on what the result would look like:
    
    .. image:: ../img/did_regex.png
    :scale: 100% 


    Regular expression for mobile
    ^[1-9][0-9]9\\d{8}$|^0[1-9][0-9]9\\d{8}$|^55[1-9][0-9]9\\d{8}$

    Regular expression for landline
    ^[1-9][0-9]\\d{8}$|^0[1-9][0-9]\\d{8}$|^55[1-9][0-9]\\d{8}$


    `,
    'did.selling_rate_1': `Price per minute if the number matches the above regular expression.`,
    'did.block_expression_1': `Set to yes to block calls that matches with the above regular expression.`,
    'did.send_to_callback_1': `Send this call to CallBack if it matches with the above regular expression.`,
    'did.expression_2': `Same as the first expression. Click for more info.|https://wiki.magnusbilling.org/en/source/modules/did/did.html#did-expression-1.`,
    'did.selling_rate_2': `Price per minute if the number matches the above regular expression.`,
    'did.block_expression_2': `Set to yes to block calls that matches with the above regular expression.`,
    'did.send_to_callback_2': `Send this call to CallBack if it matches with the above regular expression.`,
    'did.expression_3': `Same as the first expression. Click for more info.|https://wiki.magnusbilling.org/en/source/modules/did/did.html#did-expression-1.`,
    'did.selling_rate_3': `Price per minute if the number matches the above regular expression.`,
    'did.block_expression_3': `Set to yes to block calls that matches with the above regular expression.`,
    'did.send_to_callback_3': `Send this call to CallBack if it matches with the above regular expression.`,
    'did.cbr': `Enables CallBack Pro.`,
    'did.cbr_ua': `Execute an audio.`,
    'did.cbr_total_try': `How many times will the system try to return the call?`,
    'did.cbr_time_try': `Time interval between each try, in minutes.`,
    'did.cbr_em': `Execute an audio before the call is answered. Your DID provider needs to allow early media.`,
    'did.TimeOfDay_monFri': `Example: if your company only callbacks to the callee if the call was placed in between 09:00-12:00 and 14:00-18:00 MON-FRY, between this time interval the workaudio is going to be played and then callback to the callee. You can use multiple time intervals separated by |.`,
    'did.TimeOfDay_sat': `The same but for Saturday.`,
    'did.TimeOfDay_sun': `The same but for Sunday.`,
    'did.workaudio': `Audio that will be executed when a call is received at the time interval.`,
    'did.noworkaudio': `Audio that will be executed when a call is received out of the time interval.`,
    'did.record_call': `Record calls for this DID. Recorded regardless of destination.`,
    //DID DESTINATION
    'diddestination.id_did': `Select the DID that you want create new destination for.`,
    'diddestination.id_user': `User that will be the owner of this DID.`,
    'diddestination.activated': `Only active destinations will be used.`,
    'diddestination.priority': `You can create up to 5 destinations for your DID. If a try is made and a error is received, MagnusBilling will try to send the call to the next destination priority available. Only works with the "SIP call" type.`,
    'diddestination.voip_call': `Type of destination.`,
    'diddestination.destination': `Set here the destination!`,
    'diddestination.id_ivr': `Select a IVR to send the call to. The IVR needs to belong to the owner of the DID aswell.`,
    'diddestination.id_queue': `Select a Queue  to send the call to. The Queue needs to belong to the owner of the DID aswell.`,
    'diddestination.id_sip': `Select a SIP Account to send the call to. The SIP Account needs to belong to the owner of the DID aswell.`,
    'diddestination.context': `In this field you may use a context in the format supported by Asterisk||Example:
    
_X. => 1,Dial(SIP/sipaccount,45)
same => n,Goto(s-\${DIALSTATUS},1)


exten => s-NOANSWER,1,Hangup
exten => s-CONGESTION,1,Congestion
exten => s-CANCEL,1,Hangup
exten => s-BUSY,1,Busy
exten => s-CHANUNAVAIL,1,SetCallerId(4545454545)
exten => s-CHANUNAVAIL,2,Dial(SIP/sipaccount2,,T)


You should NOT set a name for the context because the name will be set automatically as [did-number-of-the-did]

You may take a look at the context at /etc/asterisk/extensions_magnus_did.conf
    
    `,
    //DIDS USE
    'diduse.id_user': `User that owns the DID.`,
    'diduse.id_did': `DID Number`,
    'diduse.reservationdate': `Day that the DID was reserved for the user.`,
    'diduse.month_payed': ``,
    //FAIL2BAN
    'firewall.ip': `IP Address.`,
    'firewall.action': `With this option marked on YES, the IP will be placed on the ip-blacklist list of fail2ban and will be blocked forever. ||The option will NOT block the IP momentarily according the parameters of the file /etc/fail2ba/jail.local.
    
    By default the IP is going to stay blocked for 10 minutes`,
    'firewall.description': `These informations are captured from the log file /var/log/fail2ban.log || It's possible to track this LOG with the command 
    
    tail -f /var/log/fail2ban.log`,
    //TOKEN
    'gauthenticator.username': `The user that wants to activate TOKEN`,
    'gauthenticator.googleAuthenticator_enable': `After activating the TOKEN for the user, login will be only possible using the generated TOKEN by the Google Aunthenticator APP.||After activating the TOKEN, in the next user login will be requested to scan the QR CODE as shown in the image below
    
.. image:: ../img/token.png
    :scale: 100% 
    
To scan the code will be necessary to install the Google Aunthenticator APP, this APP wil be avaible to download in the app store for IOS and Android.

It's important to save the manual code shown in the image, in case if you ever need to activate the token in another cellphone the code will be necessary.


With the token of Google Aunthentitor will be only possible to login into the panel or deactivate the token function`,
    'gauthenticator.code': `The code will be necessary to deactivate the TOKEN. In case if you don't have the code anymore, will be necessary to deactivate via the database.`,
    'gauthenticator.google_authenticator_key': `This KEY will be necessary to activate the TOKEN in a different cellphone`,
    //GROUPMODULE
    'groupmodule.id_group': `User group`,
    'groupmodule.id_module': `Menu`,
    //GROUP USERS
    'groupuser.name': `Name of the user group`,
    //GROUP TO ADMINS
    'groupusergroup.name': `Group name`,
    'groupusergroup.user_prefix': `Filling this field, all users created by an administrator that uses this group will be initialized with this prefix.`,
    'groupusergroup.id_group': `Which client groups will the administrator group have access.|| When an administrator that belongs to this group login, only the administrator will see the client data of the selected groups`,
    //IAX USERS
    'iax.id_user': `The user whose IAX account will belong`,
    'iax.username': `The user that will be used to authenticate in the softphone`,
    'iax.secret': `The Password that will be used to authenticate in the softphone`,
    'iax.callerid': `This is the CallerID that will be shown in their destination, in external calls the provider will need to permit CLI to be correctly identified in their destination.`,
    'iax.disallow': `In this option will be possible to deactivate codecs. To deactivate all the codecs and letting avaible to the user only what you select below, use "Use all"`,
    'iax.allow': `Codecs that will be accepted.`,
    'iax.host': `"Dynamic" is an option that will let the user register his account in any IP. If you want to to authenticate the user by their IP, fill here the IP of the client, let the password field blank and put "insecure" for the port/invite in the tab "Additional Information"`,
    'iax.nat': `The client is behind NAT? Click here for more information|https://www.voip-info.org/asterisk-sip-nat/.`,
    'iax.context': `This is the context that the call will be processed, by default is set to "billing". Only alter if you have knowledge of Asterisk.`,
    'iax.qualify': `Sent the "OPTION" package to verify if the user is online.||Sintax:
    
qualify = xxx | no | yes
    
Where the XXX is the number of milliseconds used. If "yes", the time configurated in sip.conf is used, 2 seconds is the standard.

If you activate "qualify", the Asterisk will sent the command "OPTION" to SIP peer regulary to verify if the device is still online.
If the device don't answer the "OPTION" in the set period of time, Asterisk will consider the device offline for future calls.

This status can be verified with the function "sip show peer XXXX", this funcition will only provide status informations to the SIP peer that have "qualify = yes".`,
    'iax.dtmfmode': `Type of DTMF. Click here for more informations|https://www.voip-info.org/asterisk-sip-dtmfmode/.`,
    'iax.insecure': `If the host is set to "dynamic", this option will need to be set to "no". To authenticate via IP and alter to port. Click here for more information|https://www.voip-info.org/asterisk-sip-insecure/.`,
    'iax.type': `Default type is "friend", in other words they can make and receive calls. Click here for more informations|https://www.voip-info.org/asterisk-sip-type/.`,
    'iax.calllimit': `Total of simultaneous calls allowed for this IAX account.`,
    //IVRS
    'ivr.name': `Name of the IVR`,
    'ivr.id_user': `User who owns the IVR`,
    'ivr.monFriStart': `Weekly interval of attendance, can be configurated with multiples shifts.||Example:
Supposing that the attendance hours are 08h to 12h and 14h to 19h. In this case the rule would be

08:00-12:00|14:00-19:00

`,
    'ivr.satStart': `Interval of attendance in saturdays, can be configurated with multiple shifts||Example:

Supposing that the attendance hours in the saturdays are 08h to 13h. In this case the rule would be
    
08:00-13:00`,
    'ivr.sunStart': `Interval of attendance in sundays, can be configurated with multiple shifts||Example:
    
Supposing that theres no attendance hours in the sundays. In this case the rule would be
    
00:00-00:00
    
`,
    'ivr.workaudio': `Audio to play in the attendance hours.`,
    'ivr.noworkaudio': `Audio to play when it's not attendance hours`,
    'ivr.option_0': `Select the destination if the option 0 is pressed. Let it in blank if don't want any action`,
    'ivr.option_1': `Select the destination if the option 1 is pressed. Let it in blank if don't want any action`,
    'ivr.option_2': `Select the destination if the option 2 is pressed. Let it in blank if don't want any action`,
    'ivr.option_3': `Select the destination if the option 3 is pressed. Let it in blank if don't want any action`,
    'ivr.option_4': `Select the destination if the option 4 is pressed. Let it in blank if don't want any action`,
    'ivr.option_5': `Select the destination if the option 5 is pressed. Let it in blank if don't want any action`,
    'ivr.option_6': `Select the destination if the option 6 is pressed. Let it in blank if don't want any action`,
    'ivr.option_7': `Select the destination if the option 7 is pressed. Let it in blank if don't want any action`,
    'ivr.option_8': `Select the destination if the option 8 is pressed. Let it in blank if don't want any action`,
    'ivr.option_9': `Select the destination if the option  is pressed. Let it in blank if don't want any action`,
    'ivr.option_10': `Select the destination if none of the options was selected.`,
    'ivr.direct_extension': `Activating this option will be able to type an SIP account to call it directly.`,
    'ivr.option_out_0': `Select the destinationif the option 0 is pressed. Let it in blank if don't want any action`,
    'ivr.option_out_1': `Select the destination if the option 1 is pressed. Let it in blank if don't want any action`,
    'ivr.option_out_2': `Select the destination if the option 2 is pressed. Let it in blank if don't want any action`,
    'ivr.option_out_3': `Select the destination if the option 3 is pressed. Let it in blank if don't want any action`,
    'ivr.option_out_4': `Select the destination if the option 4 is pressed. Let it in blank if don't want any action`,
    'ivr.option_out_5': `Select the destination if the option 5 is pressed. Let it in blank if don't want any action`,
    'ivr.option_out_6': `Select the destination if the option 6 is pressed. Let it in blank if don't want any action`,
    'ivr.option_out_7': `Select the destination if the option 7 is pressed. Let it in blank if don't want any action`,
    'ivr.option_out_8': `Select the destination if the option 8 is pressed. Let it in blank if don't want any action`,
    'ivr.option_out_9': `Select the destination if the option 9 is pressed. Let it in blank if don't want any action`,
    'ivr.option_out_10': `Select the destination if none of the options was selected.`,
    //LOG USERS
    'logusers.id_user': `User that executed the action.`,
    'logusers.id_log_actions': `Type of action.`,
    'logusers.ip': `IP utilized for the action.`,
    'logusers.description': `What was done, normally is in JSON.`,
    //PAYMENT METHODS
    'methodpay.show_name': `The name that is shown in the client panel.`,
    'methodpay.id_user': `The user payment method. You can create payment methods for administrators or resellers. `,
    'methodpay.country': `Only for reference.`,
    'methodpay.active': `Activate this if you want to be avaible for the clients.`,
    'methodpay.min': `Mininum accepted value.`,
    'methodpay.max': `Maximun accepted value.`,
    'methodpay.username': `User payment method`,
    'methodpay.url': `Payment method URL, in the most cases the methods this URL is already preconfigurated.`,
    'methodpay.fee': `Payment method fee.`,
    'methodpay.pagseguro_TOKEN': `Payment method TOKEN`,
    'methodpay.P2P_CustomerSiteID': `This field is exclusive for some payments methods.`,
    'methodpay.P2P_KeyID': `This field is exclusive for some payments methods.`,
    'methodpay.P2P_Passphrase': `This field is exclusive for some payments methods.`,
    'methodpay.P2P_RecipientKeyID': `This field is exclusive for some payments methods.`,
    'methodpay.P2P_tax_amount': `This field is exclusive for some payments methods.`,
    'methodpay.client_id': `This field is exclusive for some payments methods.`,
    'methodpay.client_secret': `This field is exclusive for some payments methods.`,
    //MENUS
    'module.text': `Menu name `,
    'module.icon_cls': `Icon, default font "awesome V4".`,
    'module.id_module': `Menu which this menu belongs. In case the menu is blank, it's a main menu`,
    'module.priority': `Order that the menu will be shown in the menu`,
    //OFFERS
    'offer.label': `Free package name`,
    'offer.packagetype': `Type of package, there's 3 types. Unlimited calls, free calls or free seconds. `,
    'offer.freetimetocall': `In this field is where the package avaible quantity configuration will occur.||Example:
* Unlimited calls: In this option the field is blank, because will be allowed to call without any control.
* Free calls: Configure the amount of free calls that you want to give.
* Free seconds: Configure the amount of seconds that you want to allow the client to call.`,
    'offer.billingtype': `This is the period that the package will be calculated.|| Look the description:
* Monthly: The system will verify the day of the plan activation + 30 days that the client reached the package limit.
* Weekly: The system will verify the day of the plan activation + 7 days that the client reached the package limit.`,
    'offer.price': `Price that will be charged monthly to the client.||If on the expiry day the client don't have the sufficient funds to pay the package MagnusBilling will automatically cancel the package.
    
In the settings menu, ajusts, exist one option named Package Offer Notification, this value means how many days are left until the expiration of the package, the system will try to charge the subscription, if the client don't have the balance, MagnusBilling will send an email to the client informing the lack of funds.

The email can be edited in the menu, Email models , type, plan_unpaid, Expiry of Monthly Plan Notice subject.

To send emails it's necessary the configuration of SMTP in the SMTP menu.

To learn how free packages works: https://wiki.magnusbilling.org/en/source/offer.html.`,
    //OFFER CDR
    'offercdr.id_user': ``,
    'offercdr.id_offer': `Name of the offer.`,
    'offercdr.used_secondes': `Call duration.`,
    'offercdr.date_consumption': `Date and hour of the call.`,
    //OFFER USE
    'offeruse.id_user': `User that made  the call.`,
    'offeruse.id_offer': `Name of the offer.`,
    'offeruse.month_payed': `Paid months.`,
    'offeruse.reservationdate': `Date and hour that the offer was canceled.`,
    //PHONEBOOKS
    'phonebook.name': `Phonebook name.`,
    'phonebook.status': `Phonebook status.`,
    'phonebook.description': `Phonebook description, personal control only.`,
    //PHONENUMBERS
    'phonenumber.id_phonebook': `Phonebook that this number belongs to.`,
    'phonenumber.number': `Number to send calls/sms. Always need to be used in the E164 format.`,
    'phonenumber.name': `Number owner name, used for TTS or SMS`,
    'phonenumber.city': `Client city, not required field.`,
    'phonenumber.status': `MagnusBilling will only try to send when the status is active||When the call is sent to your provider, the number stays with pending status.
If the call is completed, the status switches to sent.
Otherwise will stay pending, this means that your trunk rejected the call and completed it self for some reason.
If is activated in the campaign the "blocked numbers" option, if the number is registered in the "calls & SMS" menu, "restricted numbers" submenu, blocked status.
You can use the button "process" to reactivate the numbers with pending status.`,
    'phonenumber.info': `Phonebook description, personal control only||When used for survey, will be saved here what the number that the client typed.`,
    //PLANS
    'plan.name': `Plan name`,
    'plan.signup': `Making avaible this plan in the signup formulary. If only has 1 plan, the clients that register will use this plan, if theres more than 1 plan, then the client will be able to choose. It's necessary to have at least 1 plan with this option activated to make the registers work.`,
    'plan.ini_credit': `The amount of credit you want to give to the clients whom registered through signup formulary.`,
    'plan.play_audio': `Execute audios to the client from this plan or just send the error only? For example, the audios that theres no more credit.`,
    'plan.techprefix': `Techprefix is like a password to the client, that allows the use of more plans.`,
    'plan.id_service': `Select here the services that will be avaible to the users of this plan.`,
    //PREFIXES
    'prefix.prefix': `Prefix code. Prefix will be used to tariff and bill the calls.`,
    'prefix.destination': `Destination name.`,
    //PROVIDERS
    'provider.provider_name': `Provider name`,
    'provider.credit': `The amount of credit you have in your provider's account. This field is optional.`,
    'provider.credit_control': `If you set to YES and your provider credit is < 0, all trunks from this provider will be deactivated.`,
    'provider.description': `Description to the calendar, only for self control.`,
    //QUEUES
    'queue.id_user': `User that owns the queue. `,
    'queue.name': `Queue name.`,
    'queue.language': `Queue language.`,
    'queue.strategy': `Queue strategy.`,
    'queue.ringinuse': `Call or not the agents of the queue that are in call.`,
    'queue.timeout': `How long the phone will ring until timeout`,
    'queue.retry': `The amount of time in seconds that will retry the call.`,
    'queue.wrapuptime': `Time in seconds until the agent can receive another call.`,
    'queue.weight': `Queue Priority.`,
    'queue.periodic-announce': `A set of periodic announcements can be created by separating each announcements to reproduce whit commas. E.g.: queue-periodic-announce,your-call-is-important,please-wait. This data need to be in /var/lib/asterisk/sounds/ directory.`,
    'queue.periodic-announce-frequency': `How often to make a periodic announcement.`,
    'queue.announce-position': `Informs the postition in the queue.`,
    'queue.announce-holdtime': `Should we include an estimated hold time in the position announcements?`,
    'queue.announce-frequency': `How often to announce queue position and/or estimated holdtime to caller 0=off`,
    'queue.joinempty': `Allow calls when theres no one to answer the call.`,
    'queue.leavewhenempty': `Hang the calls in queue when there's no one to answer.`,
    'queue.max_wait_time': `Maximum wait time on the queue`,
    'queue.max_wait_time_action': `SipAccount, IVR, QUEUE or LOCAL channel to send the caller if the maximum wait time is reached. Use: SIP/sip_account, QUEUE/queue_name, IVR/ivr_name OR LOCAL/extension@context.`,
    'queue.ring_or_moh': `Play waiting music or tone when the client is in the queue.`,
    'queue.musiconhold': `Import one waiting music to this queue.`,
    //QUEUES MEMBERS
    'queuemember.queue_name': `Queue that wants to add SIP account.`,
    'queuemember.interface': `SIP account to add like a agent to the queue.`,
    'queuemember.paused': `Paused agents won't get calls, is possible to pause and unpause dialing *180 to pause, and *181 to unpause.`,
    //TARIFFS
    'rate.id_plan': `The plan that you want to create a tariff for.`,
    'rate.id_prefix': `The prefix that you want create a tariff for.`,
    'rate.id_trunk_group': `The group of trunks that will be used to send this call.`,
    'rate.rateinitial': `The amount that you want to charge per minute.`,
    'rate.initblock': `Minimum time in seconds to buy. E.g., if set to 30s and the call duration is 21s, will be charged for 30s.`,
    'rate.billingblock': `This defines how the time is incremented after the minimum. E.g, if set to 6s and call duration is 32s, will becharged for 36.`,
    'rate.minimal_time_charge': `Minimun time to tariff. If it's set to 3, will only tariff calls when the time is equal or more than 3 seconds.`,
    'rate.additional_grace': `Aditional time to add to all call duration. If it's set to 10, will be added 10 seconds to all call time duration, this affects tarrifs.`,
    'rate.package_offer': `Set to yes if you want to include this tariff to a package offer.`,
    'rate.status': `Deactivating Tariffs, MagnusBilling will completely desconsider this tariff. Therefore, deleting or deactivating will have the sam effect.`,
    //BOOTHS TARIFFS
    'ratecallshop.dialprefix': `Prefix that wants to create a tariff. This tariff will be exclusive to CALLSHOP.`,
    'ratecallshop.destination': `Prefix destination name.`,
    'ratecallshop.buyrate': `Charged value per minute in the Callshop.`,
    'ratecallshop.minimo': `Minimum time in seconds to tariff. Ex: if it's set to 30, any calll that lasts less than 30 seconds will be charged 30 seconds.`,
    'ratecallshop.block': `Time period that will be charged after minimun time. Ex: if it's set to 6, this means that will always round up to 6 seconds, therefore, a call that lasted 32 seconds will be charged 36 seconds.`,
    'ratecallshop.minimal_time_charge': `Minimum time to tarrif. Ex: If is set to 3, will only tariff calls that lasted 3 or more seconds.`,
    //PROVIDER RATES
    'rateprovider.id_provider': `Provider.`,
    'rateprovider.id_prefix': `Prefix.`,
    'rateprovider.buyrate': `Paid amount per min to the provider.`,
    'rateprovider.buyrateinitblock': `Minimum time in seconds to tariff. Ex: if it's set to 30, any calll that lasts less than 30 seconds will be charged 30 seconds.`,
    'rateprovider.buyrateincrement': `Time period that will be charged after minimun time. Ex: if it's set to 6, this means that will always round up to 6 seconds, therefore, a call that lasted 32 seconds will be charged 36 seconds.`,
    'rateprovider.minimal_time_buy': `Minimum time to tarrif. Ex: If is set to 3, will only tariff calls that lasted 3 or more seconds.`,
    //REFILLS
    'refill.id_user': `User that will be realized the refill.`,
    'refill.credit': `Refill amount. Can be a positive or negative value, if the value is negative will remove from the total amount of credit of the client.`,
    'refill.description': `Description to the calendar, only for self control.`,
    'refill.payment': `This setting is only to your control, the credit will be released to the user anyway if set to Payment NO`,
    'refill.invoice_number': `Invoice number.`,
    //REFILL PROVIDERS
    'refillprovider.id_provider': `Providers name.`,
    'refillprovider.credit': `Refill value.`,
    'refillprovider.description': `Used for internal control.`,
    'refillprovider.payment': `This option is to your control only. The credit authorized to the client even if it's set to "NO".`,
    //RESTRICTED NUMBER
    'restrictedphonenumber.id_user': `User that wants to register the number.`,
    'restrictedphonenumber.number': `Number.`,
    'restrictedphonenumber.direction': `Calls ill be analysed according to the selected options.`,
    //SEND CREDIT PRODUCTS
    'sendcreditproducts.country': `Country`,
    'sendcreditproducts.operator_name': `Operator name.`,
    'sendcreditproducts.operator_id': `Operator ID.`,
    'sendcreditproducts.SkuCode': `SkuCode`,
    'sendcreditproducts.product': `Product`,
    'sendcreditproducts.send_value': `Send value`,
    'sendcreditproducts.wholesale_price': `Sales price.`,
    'sendcreditproducts.provider': `Provider.`,
    'sendcreditproducts.status': `Status.`,
    'sendcreditproducts.info': `Used for internal control.`,
    //SEND CREDIT RATES
    'sendcreditrates.idProductcountry': `Country.`,
    'sendcreditrates.idProductoperator_name': `Operator name.`,
    'sendcreditrates.sell_price': `Sales price.`,
    //SEND CREDIT SUMMARY
    'sendcreditsummary.id_user': `User.`,
    //SERVERS
    'servers.name': `Server name.`,
    'servers.host': `Server IP. Click here to know more about Slave servers and Proxy|https://magnussolution.com/br/servicos/auto-desempenho/servidor-slave.html.`,
    'servers.public_ip': `Public IP.`,
    'servers.username': `User to connect to the server.`,
    'servers.password': `Password to connect to the server.`,
    'servers.port': `Port to connect to the server.`,
    'servers.sip_port': `SIP port that the server will use.`,
    'servers.type': `Server type.`,
    'servers.weight': `This option is to balance the calls by weight.||Example.
    
Let's say there's 1 MagnusBilling server and 3 slave servers, and you want to send the double of calls to each slave, proporcionaly to the MagnusBilling server. Then just set the MagnusBilling server to weight 1, and for the slave servers weight 2.

`,
    'servers.status': `The proxy will only send calls to active servers and with weight higher than 0.`,
    'servers.description': `Used for internal control.`,
    //SERVICES
    'services.type': `Service type.`,
    'services.name': `Service name.`,
    'services.calllimit': `Limit of simultaneos calls..`,
    'services.disk_space': `Insert total disk space in GB.`,
    'services.sipaccountlimit': `Maximum value of SIP accounts that this client can create.`,
    'services.price': `Monthly cost to charge the client that activates this service.`,
    'services.return_credit': `If this service is cancelled before the expiry date, and if this option is set to "yes", will be refunded the proporcional value of not used days to the client.`,
    'services.description': `Used for internal control.`,
    //SERVICES USE
    'servicesuse.id_user': `User that owns the service.`,
    'servicesuse.id_services': `Service.`,
    'servicesuse.price': `Service price.`,
    'servicesuse.method': `Payment method.`,
    'servicesuse.reservationdate': `Day of service activation.`,
    //SIP USERS
    'sip.id_user': `User that this SIP account is associated with.`,
    'sip.defaultuser': `Username used to login in a Softphone or any SIP device.`,
    'sip.secret': `Password to login in a Softphone or any SIP device.`,
    'sip.callerid': `The Caller ID number that will be shown in their destination. Your trunk needs to accept CLI.`,
    'sip.alias': `Alias to dial between sip accounts from the same AccountCode (company).`,
    'sip.disallow': `Disallow all codecs and then select the codecs available below to enable them to the user.`,
    'sip.allow': `Select the codecs that the trunk will accept.`,
    'sip.host': `Dynamic is an option that allows the user to register their account under any IP. If you want to authenticate the user via IP, put the client IP here, let the password field blank and set it to "insecure" to por/invite in the Aditional Informations tab.`,
    'sip.sip_group': `When sending an call from DID, or campaign to a group, will be called all SIP accounts that are in the group. You can create the groups with any name.||

Is used as well to capture calls with *8, need to configurate the option "pickupexten = *8" in the file "feature.comf".
`,
    'sip.videosupport': `Activate video calls.`,
    'sip.block_call_reg': `Block calls using REGEX. To block calls from cellphones, just put it ^55\\d\\d9. Click here to visit the link that tests REGEX.|https://regex101.com.`,
    'sip.record_call': `Record calls of this SIP account.`,
    'sip.techprefix': `Useful option for when it's necessary to authenticate more than one client via IP that uses the same IP. Common in BBX multi tenant.`,
    'sip.nat': `Nat. Click here for more info|https://www.voip-info.org/asterisk-sip-nat/`,
    'sip.directmedia': `If enabled, Asterisk tries to redirect the RTP media stream to go directly from the caller to the callee.`,
    'sip.qualify': `Sent the "OPTION" package to verify if the user is online.||Sintax:
    
qualify = xxx | no | yes
        
Where the XXX is the number of milliseconds used. If "yes", the time configurated in sip.conf is used, 2 seconds is the standard.
    
If you activate "qualify", the Asterisk will sent the command "OPTION" to SIP peer regulary to verify if the device is still online.
If the device don't answer the "OPTION" in the set period of time, Asterisk will consider the device offline for future calls.
    
This status can be verified with the funcion "sip show peer XXXX", this funcion will only provide informations of status for the SIP peer that possess "qualify = yes.`,
    'sip.id_trunk_group': `:::::::WARNING::::::. By selecting a trunk group here, the trunk group will be ignored from tariffs and this trunk group will always be used. Only select a trunk group here if you really want all calls from this SIP account to be sent to this trunk group`,
    'sip.context': `This is the context that the call will be processed, "billing" is the standard option. Only change configuration if you have knowledge of Asterisk.`,
    'sip.dtmfmode': `DTMF type. Click here for more informations|https://www.voip-info.org/asterisk-sip-dtmfmode/.`,
    'sip.insecure': `This option need to be "NO" if the host is dynamic, so the IP authentication changes to port,invite.`,
    'sip.deny': `You can limit SIP traffic of a determined IP or network.`,
    'sip.permit': `You can allow SIP traffic of a determined IP or network.`,
    'sip.type': `Standard type is "friend", in other words, can make and receive calls. Click here for more informations|https://www.voip-info.org/asterisk-sip-type/.`,
    'sip.allowtransfer': `Enable this VOIP account to do tranference. The code to transfer is *2 + ramal. It's necessary to activa the option atxfer => *2 in the file "features.conf" of Asterisk.`,
    'sip.ringfalse': `Activate false ring. Add rR of the "Dial" command.`,
    'sip.calllimit': `Maximum simultaneous calls allowed for this SIP account.`,
    'sip.mohsuggest': `Waiting music for this SIP account.`,
    'sip.url_events': `.`,
    'sip.addparameter': `The parameters set in here will replace the system default parameters, as well of the trunks, if there's any.`,
    'sip.amd': `.`,
    'sip.type_forward': `Resend destination type. This resend will not work in queues.`,
    'sip.id_ivr': `Select the IVR that you want to to send to calls if the SIP account don't answer.`,
    'sip.id_queue': `Select the queue that you want to to send to calls if the SIP account don't answer.`,
    'sip.id_sip': `Select the SIP accounts that you want to to send to calls if the SIP account don't answer.`,
    'sip.extension': `Click for more details||We have 3 options, conform the selected type, group, number or custom.

* Group, the group name set here, needs to be exatcly the same group of SIP accounts that wants to receive the calls, is going to call all SIP accounts in the group.
* Custom, it's possible to execute any valid option of the DIAL command of Asterisk, example: SIP/contaSIP,45,tTr
* Number, can be a landline number or mobile number, needs to be in the 55 DDD format`,
    'sip.dial_timeout': `Timeout in seconds to wait for the call to be picked-up. After the timeout will be execute the channeling if it's configurated.`,
    'sip.voicemail': `Activate voicemail. It's necessary the configuration of SMTP in Linux to receive the email with the message. Click here to learn how to configure the SMTP.|https://www.magnusbilling.org/br/blog-br/9-novidades/25-configurar-ssmtp-para-enviar-voicemail-no-asterisk.html.`,
    'sip.voicemail_email': `Email that will be send the email with the voicemail.`,
    'sip.voicemail_password': `Voicemail password. It's possible to enter in the Voicemail typing *111`,
    'sip.sipshowpeer': `sip show peer`,
    //SIP TRACE
    'siptrace.head': `SIP message body.`,
    //ATA LINKSYS
    'sipuras.nserie': `LinkSys serial number`,
    'sipuras.macadr': `LinkSys MAC address`,
    'sipuras.senha_user': `Username to login in LinkSys settings`,
    'sipuras.senha_admin': `Password to login in LinkSys settings`,
    'sipuras.antireset': `Be cautious.*73738# command prevents resetting LinkSys.`,
    'sipuras.Enable_Web_Server': `Beware! If deactivated, will not be able to login in the Linksys settings.`,
    'sipuras.User_ID_1': `SIP account username that will be used in ATA line 1.`,
    'sipuras.Password_1': `SIP account password`,
    'sipuras.Use_Pref_Codec_Only_1': `Only use the preferred CODEC`,
    'sipuras.Preferred_Codec_1': `Set the preferred CODEC`,
    'sipuras.Register_Expires_1': `Interval in seconds that LinkSys will send a REGISTER to your server. Useful to avoid a loss of connection when you receive a call.`,
    'sipuras.Dial_Plan_1': `Read LinkSys documentation`,
    'sipuras.NAT_Mapping_Enable_1_': `It's recommended to activate this option if ATA is behind NAT.`,
    'sipuras.NAT_Keep_Alive_Enable_1_': `It's recommended to activate this option if ATA is behind NAT.`,
    'sipuras.User_ID_2': `SIP account username that will be used in ATA line 1.`,
    'sipuras.Password_2': `VOIP account password.`,
    'sipuras.Use_Pref_Codec_Only_2': `Only use preferencial codec.`,
    'sipuras.Preferred_Codec_2': `Settings of preferincial codec.`,
    'sipuras.Register_Expires_2': `Time in seconds that Linksys sends "REGISTER" to the server. If it's going to get calls in this line, it's better set it up between 120 and 480 seconds.`,
    'sipuras.Dial_Plan_2': `Read linksys documentation`,
    'sipuras.NAT_Mapping_Enable_2_': `It's recommended to activate this option if ATA is behind NAT.`,
    'sipuras.NAT_Keep_Alive_Enable_2_': `It's recommended to activate this option if ATA is behind NAT.`,
    'sipuras.STUN_Enable': `Activate STUN server.`,
    'sipuras.STUN_Test_Enable': `Validate STUN server periodically..`,
    'sipuras.Substitute_VIA_Addr': `Replace publia IP in the VIA.`,
    'sipuras.STUN_Server': `STUN server domain.`,
    //SMS
    'sms.id_user': `User that sent/received the SMS.`,
    'sms.telephone': `Number in the E164 format.`,
    'sms.sms': `SMS text.`,
    'sms.sms_from': `If your SMS provider accepts the submission of FROM, put it here. This value will be replaced for the variable %from% in the trunk URL.`,
    //SMTP
    'smtps.host': `SMST domain||You need to verify if the datacenter where the server will be hosted don't block the ports used by SMTP.`,
    'smtps.username': `Username used to authenticate the SMTP server.`,
    'smtps.password': `Password used to authenticate the SMTP server.`,
    'smtps.port': `Port used by the SMTP server.`,
    'smtps.encryption': `Encryption type.`,
    'smtps.sender': ``,
    //EMAILS TEMPLATES
    'templatemail.fromname': `This is the name that will be use with the fromname from the email.`,
    'templatemail.fromemail': `Email used in the frommail, must be the same email used by the SMTP user.`,
    'templatemail.subject': `Email subject.`,
    'templatemail.messagehtml': `Message. It's possible to variables, look at the variables tab to see the list of avaible variables.`,
    'templatemail.status': `This option let's you deactivate the exclusive mailings of this email.`,
    //TRUNKS
    'trunk.id_provider': `Provider which the trunk belongs.`,
    'trunk.trunkcode': `Trunk name, must be unique.`,
    'trunk.user': `Only used if the authentication is via username and password.`,
    'trunk.secret': `Only used if the authentication is via username and password.`,
    'trunk.host': `IP or Trunk domain.`,
    'trunk.trunkprefix': `Add a prefix to send to your trunk.`,
    'trunk.removeprefix': `Remove a prefix to send to your trunk.`,
    'trunk.allow': `Select the codecs that are allowed in this trunk.`,
    'trunk.providertech': `You need install appropriate drive to use card like dgv extra Dongle.`,
    'trunk.status': `If the trunk is inactive, Magnusbilling will sent the call to the backup trunk.`,
    'trunk.allow_error': `Send call to the next trunk if receive error 404.`,
    'trunk.register': `Only active this if the trunk is authenticated via username and password.`,
    'trunk.register_string': `<user>:<password>@<host>/contact.||"user" is the user ID for this SIP server (ex 2345).
"password" is the user password
"host" is the SIP server domain or host name.
"port" send an solicitation of the register to this host port. Standard for 5060
"contact" is the extension of Asterisk contact. Example 1234 is set in the contact header of the SIP register message. The contact ramal is used by the SIP server remotely when it's needed to send one call to Asterisk.
    `,
    'trunk.fromuser': `Several providers demand this option to authenticate, primarly when it's authenticated via user and paswword. Let it blank to send the CallerID of the SIP account of From.`,
    'trunk.fromdomain': `Defines the FROM domain: in the SIP messages when act like a UAC SIP (client).`,
    'trunk.language': `Default launguage used in any Playback()/Background().`,
    'trunk.context': `Only change this if you know what you are doing.`,
    'trunk.dtmfmode': `DMTF type. Click here for more informations|https://www.voip-info.org/asterisk-dtmf/.`,
    'trunk.insecure': `Insecure. Click here for more informations|https://www.voip-info.org/asterisk-sip-insecure/.`,
    'trunk.maxuse': `Maximum simultaneous calls for this trunk.`,
    'trunk.nat': `Is the trunk behind NAT? Click here for more informations|https://www.voip-info.org/asterisk-sip-nat/.`,
    'trunk.directmedia': `If activated, Asterisk will try to send the RTP media directly between your client and provider. It's necessary to active on the trunk as well. Click here for more informations|https://www.voip-info.org/asterisk-sip-canreinvite/.`,
    'trunk.qualify': `Sent the "OPTION" package to verify if the user is online.||Sintax:
    
qualify = xxx | no | yes
            
Where the XXX is the number of milliseconds used. If "yes", the time configurated in sip.conf is used, 2 seconds is the standard.
        
If you activate "qualify", the Asterisk will sent the command "OPTION" to SIP peer regulary to verify if the device is still online.
If the device don't answer the "OPTION" in the set period of time, Asterisk will consider the device offline for future calls.
        
This status can be verified with the funcion "sip show peer XXXX", this funcion will only provide informations of status for the SIP peer that possess "qualify = yes.`,
    'trunk.type': `Default type is "friend", in other words they can make and receive calls. Click here for more informations|https://www.voip-info.org/asterisk-sip-type/.`,
    'trunk.disallow': `In this option is possible to deactivate codecs. Use "Use all" to deactive all codects and make it avaible to the user only what you selected below.`,
    'trunk.sendrpid': `Defines if one Remote-Party-ID SIP header task to be send.||The default is "no".
    
This field is frequently used by VoIP wholesalers providers to supply the callers identity, independently of the privacy settings (From SIP header).    `,
    'trunk.addparameter': `These parameters will be added in the final AGI command - Dial command, where is in the ajust settings menu.||By default the DIAL command is:
,60,L(%timeout%:61000:30000) 

Let's say that you wanted to add an MACRO in the trunk, therefore in this field you will add the parameter, set it up M(macro_name) and create your MACRO in the Asterisk extensions.
    `,
    'trunk.port': `If you want to use a different port than 5060, you will need open the IPTABLES port.`,
    'trunk.link_sms': `URL to send SMS. Replace the number variable to %number% and text per %text%. EXAMPLE. Your SMS URL is http://trunkWebSite.com/sendsms.php?user=magnus&pass=billing&number=XXXXXX&sms_text=SSSSSSSSSSS. replace XXXXXX per %number and SSSSSSSSSSS per %text% `,
    'trunk.sms_res': `Leave it blank to not wait the provider answer. Or write the text that needs to consist in the providers answer to be considered SENT.`,
    'trunk.sip_config': `Valid format of Asterisk sip.conf, one option per line.||Example, let's say that you need to put the useragent parameter, so put it in this field:
    
useragent=my agent

.`,
    //TRUNK GROUPS
    'trunkgroup.name': `Trunk group name.`,
    'trunkgroup.type': `Type.||It's how the system will sort the trunk that belongs to a group.

* In order. The system will send a call to the trunks that are in the selected order
* Random. The system will sort the trunks in a randomized manner, using the RAND() function of MYSQL, therefore, will be able to repeat the trunk in sequence.
* LCR. Sorth the trunks that have a lower cost. If the trunk owner does not have tariff, will be desconsidered and will be put it in last. 

MagnusBilling will send the calls to the trunks that belongs in this group, until the calls are answered, occupied or canceled.

MagnusBilling will try to send the calls to the next trunk of the group as long as the next tested trunk group answer CHANUNAVAIL or CONGESTION, these are the values returned by Asterisk, and it's not possible to change.



`,
    'trunkgroup.id_trunk': `Select the trunks that belongs to this group. If selected the type, order, then select the trunks in the desired order.`,
    //USERS
    'user.username': `Username used to login into the panel.`,
    'user.password': `Password used to login into the panel.`,
    'user.id_group': `There are 3 groups: admin, agent and client. You can create more or edit any of these groups. Each group can have specific permissions. Check the menu Configuration->User Group.`,
    'user.id_group_agent': `Select the group that the clients of this retailer used.`,
    'user.id_plan': `Plan that will be used to charge the clients.`,
    'user.language': `Language. This languague is used for some system function, but not for the panel language.`,
    'user.prefix_local': `Prefix rules. Click here for more info|https://www.magnusbilling.org/local_prefix`,
    'user.active': `Only active users can login into the panel and make calls`,
    'user.country': `Used to CID Callback. The country prefix code will be added before the CID to convert the CID to E164`,
    'user.id_offer': `Used to give free minutes. It's necessary to inform the tariffs that will belongs to the free packages.`,
    'user.cpslimit': `CPS(calls per second) limit to this client. The calls that exceed this limit will be send CONGESTION.`,
    'user.company_name': ``,
    'user.state_number': `State number.`,
    'user.lastname': `Lastname.`,
    'user.firstname': `Firstname.`,
    'user.city': `City.`,
    'user.state': `State.`,
    'user.address': `Address.`,
    'user.neighborhood': `Neighborhood.`,
    'user.zipcode': `Zipcode.`,
    'user.phone': `Landline phone.`,
    'user.mobile': `Mobile phone.`,
    'user.email': `Email, it's necessary to send system notifications.`,
    'user.doc': `Client document.`,
    'user.vat': `Used in some payment methods.`,
    'user.typepaid': `Pos-paid clients can stay with negative balance until the credit limit informed in the field below.`,
    'user.creditlimit': `If the user is Post-paid, the user will be able to make calls until he reaches this limit.`,
    'user.credit_notification': `If the client credit get lower than this field value, MagnusBilling will send an email to the client warning that he is with low credits. IT'S NECESSARY HAVE A REGISTERED SMTP SERVER IN THE SETTINGS MENU.`,
    'user.enableexpire': `Activate expire. It's necessary to inform the expiry date in the "Expiry date" field.`,
    'user.expirationdate': `The date that the user will not be able to make calls anymore.`,
    'user.record_call': `This option is only for DID calls, to external calls it's necessary to activate in the VoIP accounts.`,
    'user.mix_monitor_format': `Format used to record calls.`,
    'user.calllimit': `The amount of  simultaneous calls allowed for this client.`,
    'user.calllimit_error': `Warning to be send if the call limit is exceeded.`,
    'user.callshop': `Activate the CallShop module. Only active if you really are going to use it. It's necessary give permition to the selected group.`,
    'user.disk_space': `Insert the amount disk space available to record, in GB. Use -1 to save it without limit. It's necessary to add in the cron the following php command /var/www/html/mbilling/cron.php UserDiskSpace .`,
    'user.sipaccountlimit': `The amount of VoIP accounts allowed by this user. Will be necessary give permission to the group to create VoIP accounts.`,
    'user.callingcard_pin': `Used to authenticate the CallingCard.`,
    'user.restriction': `Used to restrict dialing. Add the numbers in the menu: Users->Restricted numbers.`,
    'user.restriction_use': `Which number will be used to check the restriction. This option is valid only to outbound calls.`,
    'user.transfer_international_profit': `This function is not avaible in Brazil. It's only used to mobile refills in some countries.`,
    'user.transfer_flexiload_profit': `This function is not avaible in Brazil. It's only used to mobile refills in some countries.`,
    'user.transfer_bkash_profit': `This function is not avaible in Brazil. It's only used to mobile refills in some countries.`,
    'user.transfer_dbbl_rocket': `This function is not avaible in Brazil. It's only used to mobile refills in some countries.`,
    'user.transfer_dbbl_rocket_profit': `This function is not avaible in Brazil. It's only used to mobile refills in some countries.`,
    'user.transfer_show_selling_price': `This function is not avaible in Brazil. It's only used to mobile refills in some countries.`,
    //USER CUSTOM RATES
    'userrate.id_prefix': `Select the prefix that you want to subscribe.`,
    'userrate.rateinitial': `New sell price for this prefix.`,
    'userrate.initblock': `Minimum sell price.`,
    'userrate.billingblock': `Sell block.`,
    //VOUCHER
    'voucher.credit': `Voucher price. Click here to know to to set up VOUCHERS.|https://wiki.magnusbilling.org/en/source/how_to_use_voucher.html.`,
    'voucher.id_plan': `Plan that will be linked to the client that will use this VOUCHER.`,
    'voucher.language': `Language that will be used.`,
    'voucher.prefix_local': `Rule that will be used in the "prefix rule" field`,
    'voucher.quantity': `The amount of VOUCHERS to be generated.`,
    'voucher.tag': `Description to the calendar, only for self control.`,
    'voucher.voucher': `VOUCHER number.`,
});