Help.load({
    //USERNAME 
    'user.username': 'User to client login into the panel.',
    'user.password': 'Pass to client login into the panel.',
    'user.id_group': 'Exists 3 groups types, admin, agent and client. You can create or edit groups. Each group have especific permissions. Check menu Configuration-User Group.',
    'user.id_group_agent': 'The group that agent\'s client will use.',
    'user.id_plan': 'Which plan will be used to billing calls from this user.',
    'user.prefix_local': 'Use it to allow your user dial local format. Rules description: The rules is coma separated, and each rule is composed for 3 values with / separated. The fist value is the number to match. The second is the number to replace. The third is the number length. The first number can be * to match any digit and add the second number on the beginning. Example to Brazil 0/55/11,*/5511/8,*/5511/9. RULE 1 -> number that start with 0 and length is 11 digits, replace 0 per 55. RULE 2 ->  number that start with any digit and length is 8, add 5511 on the beginning. RULE 3 ->  number that start with any digit and length is 9, add 5511 on the beginning .',
    'user.active': 'Only active users can login into the panel and make calls',
    'user.country': 'Used to CID Callback. The country prefix code will be add before the CID to convert the CID to format E164',
    'user.id_offer': 'Used to give free minutes. You need add your package on the menu Rates Offer.',
    'user.cpslimit': 'How many Calls Per Seconds this user can send? The excess will receive CONGESTION.',
    'user.vat': 'Used to some payment gateways.',
    'user.typepaid': 'To postpaid is necessary add credit limit.',
    'user.creditlimit': 'If the user is postpaid, the client will make calls until reach this limit.',
    'user.credit_notification': 'If user credit is less then this value, MagnusBilling will try send a email. NEED CONFIGURE SMTP.',
    'user.enableexpire': 'Enable user expire.',
    'user.expirationdate': 'The date that the user will expire and inactivated.',
    'user.callshop': 'Active the Callshop module. It is necessary give permissions to the group.',
    'user.mix_monitor_format': 'Which format will used to record call. Active record on the Sip Account.',
    'user.disk_space': 'Insert the space available to record in GB. Use -1 to unlimit.',
    'user.calllimit': 'How many simultaneous calls this user can have? The excess will receive CONGESTION.',
    'user.calllimit_error': '',
    'user.sipaccountlimit': 'How many SipAccount this user can create. You need add permissions on the group to allow user create SipAccout. Or use Services menu to control permissions.',
    'user.callingcard_pin': 'Used to callingcard authentication.',
    'user.restriction': 'Used to restriction dial. Add the numbers in User menu, Restricted Numbers sub-menu.',
    'trunk.transport': 'Enable TLS transport. Need install certificate on Asterisk',
    'trunk.encryption': 'Whether to offer SRTP encrypted media (ONLY TO SRTP)',
    'trunk.port': 'Only port 5060 is open on IPTABLES.',
    'sip.calllimit': 'Use 0 to unlimit.',
    'sip.block_call_reg': 'Use a php regular expression to block matched with calls.',
    'sip.dial_timeout': 'Timeout in seconds to wait the sip answer the call.',
    'trunk.user': 'Only use if authentication is via user and pass.',
    'trunk.secret': 'Only use if authentication is via user and pass.',
    'trunk.trunkprefix': 'Add a prefix to send to your trunk.',
    'trunk.removeprefix': 'Remove a prefix to send to your trunk.',
    'trunk.allow': 'G723 and G729 are not installed.',
    'trunk.providertech': 'You need install appropriate drive to use card like dgv extra Dongle.',
    'services.disk_space': 'Insert the space available to record in GB.',
});