Help.load({
    //API
    'api.id_user': `Usuário que poderá usar a API.||Para usar a API é necessário o uso do projeto publicado no GITHUB.
    
O projeto esta publicado no link https://github.com/magnussolution/magnusbilling-api-php. 
A API tem documentação, atualmente somente em Ingles, e esta publicado no link https://github.com/magnussolution/magnusbilling-api-php/wiki. `,
    'api.api_key': `Key necessária para autenticar na API.`,
    'api.api_secret': `Secret necessário para autenticar na API.`,
    'api.status': `Permitir ou não a conexão na API.`,
    'api.action': `Quais as açōes será permitidas na conexão.`,
    'api.api_restriction_ips': `Quais os IPs poderão conectar na API.
Deixar em branco para permitir a conexão de qualquer IP.

É extremamente recomendável somente liberar os IPs que realmente deseja conectar.`,
    //BOLETO
    'boleto.id_user': ``,
    'boleto.payment': ``,
    'boleto.status': ``,
    'boleto.vencimento': ``,
    'boleto.description': ``,
    //EXTRATO DE CHAMADAS
    'call.starttime': ``,
    'call.src': ``,
    'call.callerid': ``,
    'call.calledstation': ``,
    'call.idPrefixdestination': ``,
    'call.idUserusername': ``,
    'call.idTrunktrunkcode': ``,
    'call.sessiontime': ``,
    'call.buycost': ``,
    'call.sessionbill': ``,
    'call.agent_bill': ``,
    'call.uniqueid': ``,
    //CHAMADAS ARQUIVADAS
    'callArchive.calledstation': ``,
    'callArchive.sessiontime': ``,
    'callArchive.buycost': ``,
    'callArchive.sessionbill': ``,
    'callArchive.agent_bill': ``,
    //CALLBACK
    'callBack.id_user': ``,
    'callBack.exten': ``,
    'callBack.status': ``,
    //CALLERID
    'callerid.id_user': ``,
    'callerid.cid': `Número do callerid para autenticar o CallingCard. É necessário cadastrar o número no formato que chega no servidor. Verifique o formato no Cli do Asterisk, ou consulte com o provedor do DID.`,
    'callerid.activated': ``,
    //CHAMADAS ONLINE
    'callOnLine.idUserusername': ``,
    'callOnLine.sip_account': ``,
    'callOnLine.idUsercredit': ``,
    'callOnLine.ndiscado': `Número`,
    'callOnLine.codec': ``,
    'callOnLine.callerid': `CallerID.`,
    'callOnLine.tronco': ``,
    'callOnLine.reinvite': ``,
    'callOnLine.from_ip': `Ip de origem`,
    'callOnLine.description': ``,
    //RELATóRIO
    'callShopCdr.id_user': ``,
    //RESUMO POR DIA
    'callSummaryCallShop.sumsessiontime': ``,
    'callSummaryCallShop.sumprice': ``,
    'callSummaryCallShop.sumlucro': ``,
    'callSummaryCallShop.sumbuycost': ``,
    'callSummaryCallShop.sumnbcall': ``,
    //RESUMO POR REVENDEDOR
    'callSummaryDayAgent.sumsessiontime': ``,
    'callSummaryDayAgent.sumsessionbill': ``,
    'callSummaryDayAgent.sumbuycost': ``,
    'callSummaryDayAgent.sumlucro': ``,
    'callSummaryDayAgent.sumnbcall': ``,
    //RESUMO POR DIA/TRONO
    'callSummaryDayTrunk.sumsessiontime': ``,
    'callSummaryDayTrunk.sumsessionbill': ``,
    'callSummaryDayTrunk.sumbuycost': ``,
    'callSummaryDayTrunk.sumlucro': ``,
    'callSummaryDayTrunk.sumnbcall': ``,
    //RESUMO POR DIA/USUáRIO
    'callSummaryDayUser.sumsessiontime': ``,
    'callSummaryDayUser.sumlucro': ``,
    'callSummaryDayUser.sumnbcall': ``,
    //RESUMO POR MêS/TRONCO
    'callSummaryMonthTrunk.sumsessiontime': ``,
    'callSummaryMonthTrunk.sumsessionbill': ``,
    'callSummaryMonthTrunk.sumbuycost': ``,
    'callSummaryMonthTrunk.sumlucro': ``,
    'callSummaryMonthTrunk.sumnbcall': ``,
    //RESUMO POR MêS/USUáRIO
    'callSummaryMonthUser.sumsessiontime': ``,
    'callSummaryMonthUser.sumlucro': ``,
    'callSummaryMonthUser.sumnbcall': ``,
    //RESUMO POR DIA
    'callSummaryPerDay.sumsessiontime': ``,
    'callSummaryPerDay.sumsessionbill': ``,
    'callSummaryPerDay.sumbuycost': ``,
    'callSummaryPerDay.sumlucro': ``,
    'callSummaryPerDay.sumnbcall': ``,
    'callSummaryPerDay.sumnbcallfail': ``,
    //RESUMO POR MêS
    'callSummaryPerMonth.sumsessiontime': ``,
    'callSummaryPerMonth.sumsessionbill': ``,
    'callSummaryPerMonth.sumbuycost': ``,
    'callSummaryPerMonth.sumlucro': ``,
    'callSummaryPerMonth.sumnbcall': ``,
    //RESUMO POR TRONCO
    'callSummaryPerTrunk.sumsessiontime': ``,
    'callSummaryPerTrunk.sumsessionbill': ``,
    'callSummaryPerTrunk.sumbuycost': ``,
    'callSummaryPerTrunk.sumlucro': ``,
    'callSummaryPerTrunk.sumnbcall': ``,
    'callSummaryPerTrunk.sumnbcallfail': ``,
    //RESUMO POR USUáRIO
    'callSummaryPerUser.sumsessiontime': ``,
    'callSummaryPerUser.sumlucro': ``,
    'callSummaryPerUser.sumnbcall': ``,
    'callSummaryPerUser.sumnbcallfail': ``,
    //CAMPANHAS
    'campaign.id_user': ``,
    'campaign.id_plan': `Que plano será usado para tarifar as chamadas desta cmapanha, pode ser um plano diferente do plano cadastrado na conta do cliente`,
    'campaign.name': ``,
    'campaign.status': ``,
    'campaign.startingdate': `Data que a campanha será considerada ativa.`,
    'campaign.expirationdate': `Data que a campanha não será mais considerada ativa, mesmo ser tiver números ativos`,
    'campaign.type': ``,
    'campaign.audio': `Somente usado se o tipo de campanha for de voz. O audio precisa ser compativel com Asterisk. Recomendamos usar GSM. Se usar WAV, tem que ser mono e 8k hz`,
    'campaign.audio_2': `Se você usar TTS, o nome do número será executado entre o audio 1 e 2`,
    'campaign.restrict_phone': `Ativando esta opção o MagnusBilling vai verificar se o número que será enviado a chamada esta cadastrado no menu Números Bloqueados, se tiver, o sistema vai mudar o status do número para bloqueado e não vai enviar a chamada.`,
    'campaign.auto_reprocess': `Reativar automaticamente todos os numeros das agendas da campanha quando não tiver mais números ativos`,
    'campaign.id_phonebook': `Selecione as agendas que esta campanha vai usar.`,
    'campaign.digit_authorize': `Você quer enviar o cliente para algum destino apos o audio? Ex. Se o cliente digitar 1 transferir para uma conta SIP, entao coloque aqui o número 1, e abaixo selecione SIP, e abaixo a conta VOIP que quer enviar a chamada. Selecione "Qualquer Digito", para enviar para o destino se o cliente marcar qu`,
    'campaign.type_0': ``,
    'campaign.extensions_0': ``,
    'campaign.id_ivr_0': ``,
    'campaign.id_queue_0': ``,
    'campaign.id_sip_0': ``,
    'campaign.extension_0': ``,
    'campaign.daily_start_time': ``,
    'campaign.daily_stop_time': ``,
    'campaign.monday': ``,
    'campaign.tuesday': ``,
    'campaign.wednesday': ``,
    'campaign.thursday': ``,
    'campaign.friday': ``,
    'campaign.saturday': ``,
    'campaign.sunday': ``,
    'campaign.frequency': `Quantas chamadas o sistema pode gerar por minuto nesta campanha`,
    'campaign.max_frequency': `Este é o valor maximo que o cliente poderá alterar. Se você colocar 50, o usuário poderá alterar, desde que um valor igual ou menor que 50.`,
    'campaign.nb_callmade': `Tempo do audio da campanha, usado para controlar quantidade de chamadas considerada sucesso`,
    'campaign.enable_max_call': `Se ativado, MagnusBilling vai verificar quantas chamadas ja foram realizadas e tiveram a duração igual ao tempo do audio, se a quantidade for igual ou mais que o campo abaixo, a campanha é desativada`,
    'campaign.secondusedreal': `Maximo de chamadas completas. Precisa ativar o campo acima`,
    'campaign.from': ``,
    'campaign.description': `Texto do SMS. Você pode usar a variavel %name% onde você deseja usar o nome do dono do número`,
    'campaign.tts_audio': ``,
    'campaign.tts_audio2': ``,
    'campaign.asr_options': ``,
    //MONITOR DE CAMPANHAS
    'campaignDashboard.name': ``,
    //CHAMADAS POR MINUTO
    'campaignLog.total': ``,
    //ENQUETES
    'campaignPoll.name': ``,
    'campaignPoll.repeat': ``,
    'campaignPoll.request_authorize': ``,
    'campaignPoll.digit_authorize': ``,
    'campaignPoll.description': ``,
    'campaignPoll.arq_audio': ``,
    'campaignPoll.option0': ``,
    'campaignPoll.option1': ``,
    'campaignPoll.option2': ``,
    'campaignPoll.option3': ``,
    'campaignPoll.option4': ``,
    'campaignPoll.option5': ``,
    'campaignPoll.option6': ``,
    'campaignPoll.option7': ``,
    'campaignPoll.option8': ``,
    'campaignPoll.option9': ``,
    //ENQUETE RELATóRIOS
    'campaignPollInfo.number': ``,
    'campaignPollInfo.resposta': ``,
    'campaignPollInfo.obs': ``,
    //TELEFONE BLOQUEADOS
    'campaignRestrictPhone.number': ``,
    //CONFIGURAçÜES
    'configuration.config_value': ``,
    'configuration.config_description': ``,
    //DIDS
    'did.did': `O número extamente como chega no Asterisk.`,
    'did.activated': ``,
    'did.callerid': `Coloque aqui CallerID name, deixe em branco para usar o que vem do provedor do DID.`,
    'did.connection_charge': `Custo de ativaçao. ESte custo será descontado do cliente somente no momento que o DID é vinculado ao usuário.`,
    'did.fixrate': `Custo mensal. Este valor será descontado automaticamente todos os meses do saldo do cliente. Se o cliente não tiver crédito o DID é cancelado automaticamente.`,
    'did.connection_sell': `Este é o valor que será cobrado em cada chamada, simplismente por atender a chamada.`,
    'did.minimal_time_charge': `Tempo minimo para tarifar o DID. Ex. Se colocar 3, qualquer chamada com tempo menor que 3 não será tarifado.`,
    'did.initblock': `Tempo minimo em segundos para tarifar. Ex, se colocar 30, qualquer chamada que durar menos de 30 segundos, será cobrado 30 segundos.`,
    'did.increment': `Bloco de quantos em quantos segundos ira cobrar apos o tempo minimo. Ex: se colocar 6, quer dizer que sempre vai arredondar de 6 em 6 segundos, ou seja, uma chamada durou 32s, vai cobrar 36s.`,
    'did.charge_of': ``,
    'did.calllimit': `Limite de chamadas simultâneas para este DID`,
    'did.description': ``,
    'did.expression_1': `Esta é um REGEX(Expressão regular) para tarifar o DID conforme o número de quem liga para o DID, CallerID. Ex. Se você ligar para o DID e seu número for 51988445566, e você quer cobrar 0.1 por minuto quando o número iniciar com 2 digitos seguidos de um 9, que seria um celular no Brasil, é so colocar`,
    'did.selling_rate_1': `Preço por minuto a ser cobrado se validar a REGEX acima`,
    'did.block_expression_1': `Se colocar como SIM, e o número de quem ligou se o número for validado com a REGEX acime, a chamada será desligada imeditamente.`,
    'did.send_to_callback_1': `Envia a chamada para CallBack se o número for  validado com a REGEX acime, a chamada será desligada imeditamente.`,
    'did.expression_2': `Igual a REGEX 1. Você pode usar ate 3 REGEX para diferenciara ate 3 tipos de tarifas para seu DID`,
    'did.selling_rate_2': ``,
    'did.block_expression_2': ``,
    'did.send_to_callback_2': ``,
    'did.expression_3': `Igual a REGEX 1. Você pode usar ate 3 REGEX para diferenciara ate 3 tipos de tarifas para seu DID`,
    'did.selling_rate_3': ``,
    'did.block_expression_3': ``,
    'did.send_to_callback_3': ``,
    'did.cbr': `Ativa o CallBack Pro.`,
    'did.cbr_ua': `Executar um audio`,
    'did.cbr_total_try': `Quantas vezes o sistema vai tentar retornar para o cliente?`,
    'did.cbr_time_try': `Intervalo de tempo entre cada tentativa, em minutos.`,
    'did.cbr_em': `Executar o audio antes de antender. O provedor do DID precisa aceitar EarlyMedia.`,
    'did.TimeOfDay_monFri': `Ex: sua trabalha de 09 as 12 e de 14 as 18 horas, e dentro deste horario você quer executar o callback e retornar a chamada para a pessoa que ligou, entao coloque 09:00-12:00|14:00-18:00, os intervalos sao separados por |`,
    'did.TimeOfDay_sat': `Mesma regra so que para sabados`,
    'did.TimeOfDay_sun': `Mesma regra so que para domingos`,
    'did.workaudio': `Audio que será executado quando alguem ligar dentro do horario de atendimento.`,
    'did.noworkaudio': `Audio que será executado quando ligar fora do horario de atendimento`,
    //DESTINO DE DID
    'diddestination.id_did': `Selecione o DID para criar o novo destino`,
    'diddestination.id_user': ``,
    'diddestination.activated': ``,
    'diddestination.priority': `Você pode criar ate 5 destino para o mesmo DID. Se a chamada não completa no 1º tenta o 2º, ate completar. `,
    'diddestination.voip_call': ``,
    'diddestination.destination': ``,
    'diddestination.id_ivr': ``,
    'diddestination.id_queue': ``,
    'diddestination.id_sip': ``,
    'diddestination.context': ``,
    //USO DE DIDS
    'didUse.id_user': ``,
    'didUse.id_did': ``,
    'didUse.reservationdate': ``,
    //FIREWALL
    'firewall.ip': ``,
    'firewall.action': ``,
    'firewall.description': ``,
    //TOKEN
    'gAuthenticator.username': ``,
    'gAuthenticator.googleAuthenticator_enable': `Após o usuário ativar o Token, somente será possível logar no painel ou desativar o token com o token gerado pela APP Google Authenticator.`,
    'gAuthenticator.code': ``,
    'gAuthenticator.google_authenticator_key': ``,
    //GROUPMODULE
    'groupModule.id_group': ``,
    'groupModule.id_module': ``,
    //GRUPOS PARA CLIENTE
    'groupUser.id': ``,
    'groupUser.name': ``,
    //GRUPOS ADMINISTRADORES
    'groupUserGroup.name': ``,
    'groupUserGroup.user_prefix': ``,
    'groupUserGroup.id_group': ``,
    //CONTAS IAX
    'iax.id_user': ``,
    'iax.username': ``,
    'iax.secret': ``,
    'iax.callerid': ``,
    'iax.disallow': ``,
    'iax.allow': ``,
    'iax.host': ``,
    'iax.nat': ``,
    'iax.context': ``,
    'iax.qualify': ``,
    'iax.dtmfmode': ``,
    'iax.insecure': ``,
    'iax.type': ``,
    'iax.calllimit': ``,
    //URAS
    'ivr.name': ``,
    'ivr.id_user': ``,
    'ivr.monFriStart': `Hora que inicia o horario de atendimento semanal`,
    'ivr.satStart': `Hora que inicia o horario de atendimento no sabado`,
    'ivr.sunStart': `Hora que inicia o horario de atendimento no domingo`,
    'ivr.workaudio': `Audio para executar dentro dos horarios de atendimento`,
    'ivr.noworkaudio': `Audio para executar fora de atendimento`,
    'ivr.type_0': ``,
    'ivr.id_ivr_0': ``,
    'ivr.id_queue_0': ``,
    'ivr.id_sip_0': ``,
    'ivr.extension_0': ``,
    'ivr.type_1': ``,
    'ivr.id_ivr_1': ``,
    'ivr.id_queue_1': ``,
    'ivr.id_sip_1': ``,
    'ivr.extension_1': ``,
    'ivr.type_2': ``,
    'ivr.id_ivr_2': ``,
    'ivr.id_queue_2': ``,
    'ivr.id_sip_2': ``,
    'ivr.extension_2': ``,
    'ivr.type_3': ``,
    'ivr.id_ivr_3': ``,
    'ivr.id_queue_3': ``,
    'ivr.id_sip_3': ``,
    'ivr.extension_3': ``,
    'ivr.type_4': ``,
    'ivr.id_ivr_4': ``,
    'ivr.id_queue_4': ``,
    'ivr.id_sip_4': ``,
    'ivr.extension_4': ``,
    'ivr.type_5': ``,
    'ivr.id_ivr_5': ``,
    'ivr.id_queue_5': ``,
    'ivr.id_sip_5': ``,
    'ivr.extension_5': ``,
    'ivr.type_6': ``,
    'ivr.id_ivr_6': ``,
    'ivr.id_queue_6': ``,
    'ivr.id_sip_6': ``,
    'ivr.extension_6': ``,
    'ivr.type_7': ``,
    'ivr.id_ivr_7': ``,
    'ivr.id_queue_7': ``,
    'ivr.id_sip_7': ``,
    'ivr.extension_7': ``,
    'ivr.type_8': ``,
    'ivr.id_ivr_8': ``,
    'ivr.id_queue_8': ``,
    'ivr.id_sip_8': ``,
    'ivr.extension_8': ``,
    'ivr.type_9': ``,
    'ivr.id_ivr_9': ``,
    'ivr.id_queue_9': ``,
    'ivr.id_sip_9': ``,
    'ivr.extension_9': ``,
    'ivr.type_10': ``,
    'ivr.id_ivr_10': ``,
    'ivr.id_queue_10': ``,
    'ivr.id_sip_10': ``,
    'ivr.extension_10': ``,
    'ivr.direct_extension': ``,
    'ivr.type_out_0': ``,
    'ivr.id_ivr_out_0': ``,
    'ivr.id_queue_out_0': ``,
    'ivr.id_sip_out_0': ``,
    'ivr.extension_out_0': ``,
    'ivr.type_out_1': ``,
    'ivr.id_ivr_out_1': ``,
    'ivr.id_queue_out_1': ``,
    'ivr.id_sip_out_1': ``,
    'ivr.extension_out_1': ``,
    'ivr.type_out_2': ``,
    'ivr.id_ivr_out_2': ``,
    'ivr.id_queue_out_2': ``,
    'ivr.id_sip_out_2': ``,
    'ivr.extension_out_2': ``,
    'ivr.type_out_3': ``,
    'ivr.id_ivr_out_3': ``,
    'ivr.id_queue_out_3': ``,
    'ivr.id_sip_out_3': ``,
    'ivr.extension_out_3': ``,
    'ivr.type_out_4': ``,
    'ivr.id_ivr_out_4': ``,
    'ivr.id_queue_out_4': ``,
    'ivr.id_sip_out_4': ``,
    'ivr.extension_out_4': ``,
    'ivr.type_out_5': ``,
    'ivr.id_ivr_out_5': ``,
    'ivr.id_queue_out_5': ``,
    'ivr.id_sip_out_5': ``,
    'ivr.extension_out_5': ``,
    'ivr.type_out_6': ``,
    'ivr.id_ivr_out_6': ``,
    'ivr.id_queue_out_6': ``,
    'ivr.id_sip_out_6': ``,
    'ivr.extension_out_6': ``,
    'ivr.type_out_7': ``,
    'ivr.id_ivr_out_7': ``,
    'ivr.id_queue_out_7': ``,
    'ivr.id_sip_out_7': ``,
    'ivr.extension_out_7': ``,
    'ivr.type_out_8': ``,
    'ivr.id_ivr_out_8': ``,
    'ivr.id_queue_out_8': ``,
    'ivr.id_sip_out_8': ``,
    'ivr.extension_out_8': ``,
    'ivr.type_out_9': ``,
    'ivr.id_ivr_out_9': ``,
    'ivr.id_queue_out_9': ``,
    'ivr.id_sip_out_9': ``,
    'ivr.extension_out_9': ``,
    'ivr.type_out_10': ``,
    'ivr.id_ivr_out_10': ``,
    'ivr.id_queue_out_10': ``,
    'ivr.id_sip_out_10': ``,
    'ivr.extension_out_10': ``,
    //LOG DE ACESSOS
    'logUsers.id_user': ``,
    'logUsers.id_log_actions': ``,
    'logUsers.ip': ``,
    'logUsers.description': ``,
    //MéTODOS DE PAGAMENTO
    'methodPay.show_name': `Nome que será mostrado no painel do cliente`,
    'methodPay.id_user': ``,
    'methodPay.country': `Somente para referencia`,
    'methodPay.active': `Ative se quiser deixar disponivel para os clientes`,
    'methodPay.min': `Valor minimo que deseja aceitar`,
    'methodPay.max': `Valor maximo que deseja aceitar`,
    'methodPay.username': ``,
    'methodPay.url': ``,
    'methodPay.fee': ``,
    'methodPay.boleto_banco': ``,
    'methodPay.boleto_agencia': ``,
    'methodPay.boleto_conta_corrente': ``,
    'methodPay.boleto_taxa': ``,
    'methodPay.boleto_instrucoes': ``,
    'methodPay.boleto_nome_emp': ``,
    'methodPay.boleto_end_emp': ``,
    'methodPay.boleto_cidade_emp': ``,
    'methodPay.boleto_estado_emp': ``,
    'methodPay.boleto_cpf_emp': ``,
    'methodPay.pagseguro_TOKEN': ``,
    'methodPay.P2P_CustomerSiteID': ``,
    'methodPay.P2P_KeyID': ``,
    'methodPay.P2P_Passphrase': ``,
    'methodPay.P2P_RecipientKeyID': ``,
    'methodPay.P2P_tax_amount': ``,
    'methodPay.client_id': ``,
    'methodPay.client_secret': ``,
    //MENUS
    'module.text': ``,
    'module.icon_cls': ``,
    'module.id_module': ``,
    'module.priority': ``,
    //PACOTES GRáTIS
    'offer.label': ``,
    'offer.packagetype': ``,
    'offer.freetimetocall': ``,
    'offer.billingtype': ``,
    'offer.price': ``,
    //RELATóRIO DE PACOTES
    'offerCdr.id_user': ``,
    'offerCdr.id_offer': ``,
    'offerCdr.used_secondes': ``,
    'offerCdr.date_consumption': ``,
    //USO DE PACOTES
    'offerUse.id_user': ``,
    'offerUse.id_offer': ``,
    'offerUse.month_payed': ``,
    'offerUse.reservationdate': ``,
    //AGENDAS
    'phoneBook.name': ``,
    'phoneBook.status': ``,
    'phoneBook.description': ``,
    //NúMEROS
    'phoneNumber.id_phonebook': ``,
    'phoneNumber.number': `Nümero para enviar o torpedo/sms. Deve ser usado sempre no formato DDI+DDD+número`,
    'phoneNumber.name': `Nome do dono do número, usado para TTS ou SMS`,
    'phoneNumber.city': ``,
    'phoneNumber.status': `MagnusBilling somente tenta enviar quando o status esta ativo. Quando a chamada é enviada para seu provedor, o número fica com estado pendente. Se a chamada é completada, o estado muda para enviado, caso contrario ficara como pendente. Você pode usar o botão reprocessar para reativar os número que e`,
    'phoneNumber.info': ``,
    //PLANOS
    'Plan.name': ``,
    'Plan.signup': `Disponibilizar este plano no formulário de registro. Se tiver somente 1 plano os clientes que se registrarem vão usar este plano, se tiver mais de 1, ai o cliente podera escolher. É necessário ter pelo menos 1 plano com esta opção ativada para funcionar o registro.`,
    'Plan.ini_credit': `Quanto de crédito você quer dar para clientes que se registram atraves do formulário de registro.`,
    'Plan.play_audio': `Executar audios para os cliente deste plano ou mandar somente erro? Por exemplo os auidos que acabou o crédito.`,
    'Plan.techprefix': `Techprefix é como uma senha para o cliente poder usar mais de uma plano. Por exemplo, digamos que você tem 3 tipos de planos,GSM, TDM e CLI, e quer deixar seu cliente escolher qual plano ele deseja usar. Então coloque techprefix nos planos e solicite ai seu cliente que para usar cada um dos planos e`,
    'Plan.id_service': ``,
    //PREFIXOS
    'prefix.prefix': `Prefixo. Prefixo serão usados para criar as tarifas. EX. 5511.`,
    'prefix.destination': `Nome do destino. EX: Brasil SP`,
    //PROVEDORES
    'provider.provider_name': `Nome do provedor. Provedor é a empresa que você compra os minutos. O mesmo provedor pode ter varios troncos`,
    'provider.credit': `Quanto você tem de crédito com o provedor? Este campo é opcional.`,
    'provider.credit_control': ``,
    'provider.description': ``,
    //FILAS DE ESPERA
    'queue.name': ``,
    'queue.strategy': ``,
    'queue.ringinuse': `Chamar ou não agentes da fila que estejam em chamada.`,
    'queue.timeout': `Por quanto tempo deve ficar chamadando um agente`,
    'queue.retry': `Tempo em segundos para tentar chamadas outro agente caso o anterior não atender`,
    'queue.wrapuptime': `Intervalo de tempo em segundos que o agente podera receber outra chamada`,
    'queue.weight': `Importancia desta fila. Por exemplo, você tem o memos agente em 2 filas, e chega 12 chamadas ao mesmo tempo, o Asterisk vai enviar a chamada da fila com maior importancia para o agente.`,
    'queue.periodic-announce': `Audio para os anuncios. Você pode colocar mais de um audio, separando por  (,). Estes audios devem estar no diretorio /var/lib/asterisk/sounds/`,
    'queue.periodic-announce-frequency': `Frequancia que deve executar os anuncios.`,
    'queue.announce-position': `Informar a posiçao que a pessoa se encontra na fila`,
    'queue.announce-holdtime': `Deveria ser incluido no anuncio da posiçao a estimativa de espera?`,
    'queue.announce-frequency': `A cada quantos segundos deve informar a posiçao. Deixe em 0 para desativar o anuncio de posiçao.`,
    'queue.joinempty': `Permitir novas chamadas quando não tiver agente disponivel para atender a chamada`,
    'queue.leavewhenempty': `Desligar as chamadas em espera quando não tiver mais agente livres`,
    'queue.max_wait_time': `Tempo maximo de espera para ser atendido`,
    'queue.max_wait_time_action': `Conta VoIP, IVR ou Fila de espera, para enviar o cliente caso o tempo máximo de espera for superado. Formatos aceitos: SIP/conta_voip, QUEUE/nome_da_queue ou IRV/nome_da_ivr.`,
    'queue.ring_or_moh': ``,
    'queue.musiconhold': ``,
    //FILAS AGENTES
    'queueMember.queue_name': ``,
    'queueMember.interface': ``,
    'queueMember.paused': ``,
    //TARIFAS
    'rate.id_plan': `O plano que você quer adiconar esta tarifa.`,
    'rate.id_prefix': `Selecione o profixo que quer criar a tarifa`,
    'rate.id_trunk_group': ``,
    'rate.rateinitial': `Preço de venda por minuto para este destino`,
    'rate.initblock': `Tempo minimo em segundos para tarifar a venda. Ex, se colocar 30, qualquer chamada que durar menos de 30 segundos, será cobrado 30 segundos.`,
    'rate.billingblock': `Bloco de quantos em quantos segundos ira cobrar apos o tempo minimo. Ex: se colocar 6, quer dizer que sempre vai arredondar de 6 em 6 segundos, ou seja, uma chamada durou 32s, vai cobrar 36s.`,
    'rate.minimal_time_charge': `Tempo minimo para tarifar. Se colocar 3, so vai tarifar chamadas que o tempo for => que 3 segundos`,
    'rate.additional_grace': `Tempo para adicionar na duração da chamada. EX. se colocar 10, será adicionar 10 segundos no tempo de todas as chamadas, isso afeta a tarifação.`,
    'rate.package_offer': `Ative esta opção se você quer que esta tarifa seja usada nos pacotes grátis`,
    'rate.status': ``,
    //TARIFAS
    'rateCallshop.dialprefix': ``,
    'rateCallshop.destination': ``,
    'rateCallshop.buyrate': ``,
    'rateCallshop.minimo': ``,
    'rateCallshop.block': ``,
    'rateCallshop.minimal_time_charge': ``,
    //TARIFAS PROVEDORES
    'rateProvider.id_provider': ``,
    'rateProvider.id_prefix': ``,
    'rateProvider.buyrate': ``,
    'rateProvider.buyrateinitblock': ``,
    'rateProvider.buyrateincrement': ``,
    'rateProvider.minimal_time_buy': ``,
    //RECARGAS
    'refill.id_user': ``,
    'refill.credit': `Valor da recarga`,
    'refill.description': ``,
    'refill.payment': `Esta opção é somente para seu controle. O crédito será liberado para o cliente mesmo colocando como NÃO`,
    'refill.invoice_number': ``,
    //RECARGA DE PROVEDORES
    'refillprovider.id_provider': ``,
    'refillprovider.credit': ``,
    'refillprovider.description': ``,
    'refillprovider.payment': ``,
    //NúMEROS BLOQUEADOS
    'restrictedPhonenumber.id_user': ``,
    'restrictedPhonenumber.number': ``,
    'restrictedPhonenumber.direction': ``,
    //SEND CREDIT PRODUCTS
    'sendCreditProducts.country': ``,
    'sendCreditProducts.operator_name': ``,
    'sendCreditProducts.operator_id': ``,
    'sendCreditProducts.SkuCode': ``,
    'sendCreditProducts.product': ``,
    'sendCreditProducts.send_value': ``,
    'sendCreditProducts.wholesale_price': ``,
    'sendCreditProducts.provider': ``,
    'sendCreditProducts.status': ``,
    'sendCreditProducts.info': ``,
    //SEND CREDIT RATES
    'sendCreditRates.idProductcountry': ``,
    'sendCreditRates.idProductoperator_name': ``,
    'sendCreditRates.sell_price': ``,
    //SEND CREDIT SUMMARY
    'sendCreditSummary.id_user': ``,
    //SERVIDORES
    'servers.name': ``,
    'servers.host': `Este menu é esclusivo para quem usa Slave e Proxy, clique para mais informaçōes|https://magnussolution.com/br/servicos/auto-desempenho/servidor-slave.html`,
    'servers.public_ip': ``,
    'servers.username': ``,
    'servers.password': ``,
    'servers.port': ``,
    'servers.sip_port': ``,
    'servers.type': ``,
    'servers.weight': ``,
    'servers.status': ``,
    'servers.description': ``,
    //SERVIçOS
    'services.type': `Tipo de serviço`,
    'services.name': `Nome para o serviço`,
    'services.calllimit': ``,
    'services.disk_space': `Coloque o total de espaço em disco em GB.`,
    'services.sipaccountlimit': ``,
    'services.price': ``,
    'services.return_credit': ``,
    'services.description': ``,
    //USO DE SERVIçOS
    'servicesUse.id_user': ``,
    'servicesUse.id_services': ``,
    'servicesUse.price': ``,
    'servicesUse.method': ``,
    'servicesUse.reservationdate': ``,
    //CONTAS SIP
    'sip.id_user': ``,
    'sip.defaultuser': `Usuário que será usado para logar nos softphones ou qualquer dispositivo SIP.`,
    'sip.secret': `Senha que será usado para logar nos softphones ou qualquer dispositivo SIP.`,
    'sip.callerid': `Este é o CallerID que será mostrado no destino, em chamadas externas o provedor precisa permitir CLI para que seja identificado corretamente no destino.`,
    'sip.alias': `Alias é um número para facilitar a discagem, pode colocar qualquer número. Pode repetir os mesmos números para contas diferente.`,
    'sip.disallow': `ESta opção destiva todos os codecs e deixa disponivel para o usuário somente os que você selecionar abaixo.`,
    'sip.allow': ``,
    'sip.host': `Dynamic é a opção para deixar o usuário registrar sua conta em qualquer IP. Se você deseja autenticar o usuário por IP, coloque aqui o IP do cliente, deixe a senha em brando e coloque insecure para port/invite na TAB Informaçōes Adicionais.`,
    'sip.sip_group': `Usado a chamadas recebidas. Quando enviar um DID parar um grupo, vai chamar todas as contas que tiver no grupo. Você pode criar os grupos com qualquer nome`,
    'sip.videosupport': ``,
    'sip.block_call_reg': `Bloquear chamadas usando REGEX. EX: Para bloquear chamadas para celular é so colocar ^55\\d\\d9. Click para ir ao site que testa REGEX.|https://regex101.com`,
    'sip.record_call': ``,
    'sip.techprefix': ``,
    'sip.nat': `Clique para mais informaçōes|https://www.voip-info.org/asterisk-sip-nat/`,
    'sip.directmedia': `Se ativado, Asterisk vai tentar enviar a midia RTP direto entre seu cliente e seu provedor. Precisa ativar no tronco também. Clique para mais informaçōes|https://www.voip-info.org/asterisk-sip-canreinvite/`,
    'sip.qualify': `Enviar pacote OPTION para para verificar se o usuário esta online.`,
    'sip.context': `Somente altere se você sabe o que esta fazendo.`,
    'sip.dtmfmode': ``,
    'sip.insecure': `Se o host estiver dynamic esta opção precisa estar como NO. Para IP authentication alterar para port,invite.`,
    'sip.deny': ``,
    'sip.permit': ``,
    'sip.type': ``,
    'sip.allowtransfer': `Permite esta conta VoIP fazer transferencia. O código para transferencia é *2ramal `,
    'sip.ringfalse': `Ativa ring falso. Adiciona rR do comando Dial.`,
    'sip.calllimit': `Chamadas simultâneas permitidas.`,
    'sip.mohsuggest': ``,
    'sip.url_events': ``,
    'sip.addparameter': ``,
    'sip.amd': ``,
    'sip.type_forward': ``,
    'sip.id_ivr': ``,
    'sip.id_queue': ``,
    'sip.id_sip': ``,
    'sip.extension': ``,
    'sip.dial_timeout': `Tempo em segundos que será aguardado para atender a chamada.`,
    'sip.voicemail': ``,
    'sip.voicemail_email': ``,
    'sip.voicemail_password': ``,
    'sip.sipshowpeer': ``,
    //SIP TRACE
    'sipTrace.head': ``,
    //ATA LINKSYS
    'sipuras.nserie': `Linksys serial number`,
    'sipuras.macadr': `Linksys MAC address`,
    'sipuras.senha_user': `Usuário para entrar na configuração do LinkSys`,
    'sipuras.senha_admin': `Senha para entrar na configuração do LinkSys`,
    'sipuras.antireset': `Tenha cuidado. Esta opção desativa o reinicio com o comando *73738#`,
    'sipuras.Enable_Web_Server': `Tenha cuidadol. Se desativado, não será mais possível entrar nas configuraçōes do Linksys.`,
    'sipuras.marca': ``,
    'sipuras.altera': ``,
    'sipuras.User_ID_1': ``,
    'sipuras.Password_1': `Senha da Conta VoIP`,
    'sipuras.Use_Pref_Codec_Only_1': `Somente usar o codec preferencial`,
    'sipuras.Preferred_Codec_1': `Configurar codec preferencial`,
    'sipuras.Register_Expires_1': `Tempo em segundos que o Linksys fica enviando o REGISTER para o servidor. Se for receber chamadas nesta linha, melhor deixar entre 120 e 480 segundos.`,
    'sipuras.Dial_Plan_1': `Read linkys documentation`,
    'sipuras.NAT_Mapping_Enable_1_': ``,
    'sipuras.NAT_Keep_Alive_Enable_1_': ``,
    'sipuras.User_ID_2': ``,
    'sipuras.Password_2': ``,
    'sipuras.Use_Pref_Codec_Only_2': ``,
    'sipuras.Preferred_Codec_2': ``,
    'sipuras.Register_Expires_2': ``,
    'sipuras.Dial_Plan_2': ``,
    'sipuras.NAT_Mapping_Enable_2_': ``,
    'sipuras.NAT_Keep_Alive_Enable_2_': ``,
    'sipuras.STUN_Enable': ``,
    'sipuras.STUN_Test_Enable': ``,
    'sipuras.Substitute_VIA_Addr': ``,
    'sipuras.STUN_Server': ``,
    //SMS
    'sms.id_user': ``,
    'sms.telephone': `Número no formato E164`,
    'sms.sms': ``,
    'sms.sms_from': ``,
    //SMTP
    'smtps.host': `Você precisa verificar se o datacenter não bloqueia as portas usada pelo SMTP`,
    'smtps.username': ``,
    'smtps.password': ``,
    'smtps.port': ``,
    'smtps.encryption': ``,
    //MODELOS DE EMAIL
    'templateMail.fromname': ``,
    'templateMail.fromemail': ``,
    'templateMail.subject': ``,
    'templateMail.messagehtml': ``,
    //TRONCOS
    'trunk.id_provider': ``,
    'trunk.trunkcode': ``,
    'trunk.user': `Somente coloque usuário se seu tronco for autenticado por usuário e senha.`,
    'trunk.secret': `Somente coloque senha se seu tronco for autenticado por usuário e senha.`,
    'trunk.host': `IP ou Dominio do tronco`,
    'trunk.trunkprefix': `Adiciona um prefixo no inicio do número to enviar para o tronco. Tambem usado para quando você precisa enviar um techprefix. EX: Se você tem que enviar o número no formato 0DDD número, coloque aqui 0 e no campo abaixo 55. Isso vai remover o 55 e adiconar o 0 `,
    'trunk.removeprefix': `Remove este prefixo do número.`,
    'trunk.allow': `Selecione os codecs que o tronco aceita.`,
    'trunk.providertech': `Protocolo do tronco. Alguns protocolos como Dahdi, Dongle, DGV, khomp, precisam ser instalado no Asterisk antes de usar.`,
    'trunk.status': `Se o tronco for inativado, Magnusbilling enviara a chamada para o tronco backup`,
    'trunk.allow_error': `Se SIM, a chamadas será enviada para o tronco backup a menos que a chamada seja atendida ou cancelada. Somente use quando seu tronco tiver algum problema de sinalização, por exemplo sinaliza BUSY quando não tiver canal disponivel.`,
    'trunk.register': `Somente ative se seu tronco for por usuário e senha.`,
    'trunk.register_string': ``,
    'trunk.fromuser': `Many SIP providers require this. Normally it is the some username`,
    'trunk.fromdomain': ``,
    'trunk.language': ``,
    'trunk.context': `Somente altere se você souber o que esta fazendo.`,
    'trunk.dtmfmode': `Clique para mais informaçōes|https://www.voip-info.org/asterisk-dtmf/`,
    'trunk.insecure': `Clique para mais informaçōes|https://www.voip-info.org/asterisk-sip-insecure/`,
    'trunk.maxuse': `Número maximo de chamadas simultaneas.`,
    'trunk.nat': ``,
    'trunk.directmedia': ``,
    'trunk.qualify': ``,
    'trunk.type': ``,
    'trunk.disallow': ``,
    'trunk.sendrpid': ``,
    'trunk.addparameter': ``,
    'trunk.port': `Porta do tronco. Se você precisar usar outra porta diferente da 5060, lembre-se de liberar a porta no IPTABLES.`,
    'trunk.link_sms': `URL para enviar SMS. Subistituir o número por %number% e o texto por %text%. EX. a URL enviada pelo seu provedor de SMS é http://trunkWebSite.com.br/sendsms.php?usuario=magnus&senha=billing&numero=XXXXXX&texto=SSSSSSSSSSS. altere XXXXXX per %number% e SSSSSSSSSSS por %text% `,
    'trunk.sms_res': `Deixe em branco para não aguardar resposta do provedor. Ou coloque o texto que deve conter na resposta do provedor para ser considerado ENVIADO.`,
    'trunk.sip_config': `Formato válido no Asterisk sip.conf, uma opção por linha.`,
    //GRUPO DE TRONCOS
    'trunkGroup.name': ``,
    'trunkGroup.type': ``,
    'trunkGroup.id_trunk': ``,
    //USUáRIOS
    'user.username': `Usuário para logar no painel de cliente.||Descriçao`,
    'user.password': `Senha para logar no painel de cliente.`,
    'user.id_group': `Existe 3 tipos de grupos: Administrador, Revendedor e Cliente. Você pode criar or editar qualquer destes grupos. Cada grupo tem suas permissōes especificas. Veja o menu Configurações, Grupo para Clientes.`,
    'user.id_group_agent': ``,
    'user.id_plan': `Plano usado para tarifar este cliente.`,
    'user.language': ``,
    'user.prefix_local': `Esta regra permite o cliente discar no formato local. || EX 0ddd ou somente o número dentro de seu DDD. As regras são separadas por virgula e composta por 2 ou 3 parametros separados por /.
1º é o número que sera subistituido. Pode ser * para pegar qualquer digito.
2º é o número que vai subistituir o 1º.
3º é a quantidade de digitos do número. Se nao colocar o 3º paramentro, nao sera verificado a quantidade de digitos.

Alguns exemplos.

Permite ligar 55DDDnº, 0DDDnº ou so numero

0/55,*/5511/8,*/5511/9
Regra 1 -> números que iniciam com 0, o zero sera subistituido por 55, independente de quantos digitos tiver o numero. 
Regra 2 -> números que iniciam com qualquer valor e tem 8 digitos, sera adicionado 5511 na frente. 
Regra 3 -> números que iniciam com qualquer valor e tem 9 digitos, sera adicionado 5511 na frente


Permite ligar 55DDDnº, 0DDDnº, DDDnº ou so numero

0/55,*/5511/8,*/5511/9,*/55/10,*/55/11
Regra 1 -> números que iniciam com 0, o zero sera subistituido por 55, independente de quantos digitos tiver o numero. 
Regra 2 -> números que iniciam com qualquer valor e tem 8 digitos, sera adicionado 55 na frente. 
Regra 3 -> números que iniciam com qualquer valor e tem 9 digitos, sera adicionado 55 na frente
Regra 4 -> números que iniciam com qualquer valor e tem 10 digitos, sera adicionado 5511 na frente. 
Regra 5 -> números que iniciam com qualquer valor e tem 11 digitos, sera adicionado 5511 na frente
`,
    'user.active': `Somente usuários ativos podem fazer chamadas.`,
    'user.country': `Usado para CID Callback. O DDI do país será adicionado antes do CallerID to converter o CallerID para o formato DDI DDD nº`,
    'user.id_offer': `Usado para ativar um pacote gratis. É necessario informar as tarifas que vão pertencer aos pacotes gratís.`,
    'user.cpslimit': `Limite de CPS(chamadas por segundo) para este cliente. As chamadas que superar este limite seráenviado CONGESTION.`,
    'user.company_name': `magnus`,
    'user.state_number': ``,
    'user.lastname': ``,
    'user.firstname': ``,
    'user.city': ``,
    'user.state': ``,
    'user.address': ``,
    'user.neighborhood': ``,
    'user.zipcode': ``,
    'user.phone': ``,
    'user.mobile': ``,
    'user.email': ``,
    'user.doc': ``,
    'user.vat': `Usado em algums metodos de pagamento.`,
    'user.typepaid': ``,
    'user.creditlimit': `Somente usado para Pos-Pago. O cliente poderá ligar até chegar a este limite negativo.`,
    'user.credit_notification': `Se o crédito do cliente ficar menor que esta campo, MagnusBilling vai enviar um email para o cliente informando que esta com pouco crédito. NECESSARIO TER CADASTRADO UM SERVIDOR SMTP NO MENU CONFIGURAÇŌES`,
    'user.enableexpire': ``,
    'user.expirationdate': `Data que este cliente não poderá mais efetuar chamadas`,
    'user.record_call': `Esta opção é somente para chamadas de DID, para chamadas externas tem que ativar nas Contas VoIP.`,
    'user.mix_monitor_format': `Formato que será usado para gravar chamadas.`,
    'user.calllimit': `Chamadas simultâneas permitidas para este usuário.`,
    'user.calllimit_error': ``,
    'user.callshop': `Ativa o modulo CallShop. Somente ative se realmente for usar. É necessário dar permissōes ao grupo selecionado.`,
    'user.disk_space': `Espaço em GB que o usuário podera usar com as gravaçōes. Coloque -1 para deixar sem limite.É necessário adicionar no cron o seguinte comando php /var/www/html/mbilling/cron.php UsuárioDiskSpace `,
    'user.sipaccountlimit': `Quantas Contas VoIP este usuário poderá ter. Será necessário dar permissōes no grupo para criar Contas VoIP.`,
    'user.callingcard_pin': `Usado para autentição do callingcard.`,
    'user.restriction': ``,
    'user.transfer_international_profit': ``,
    'user.transfer_flexiload_profit': ``,
    'user.transfer_bkash_profit': ``,
    'user.transfer_dbbl_rocket': ``,
    'user.transfer_dbbl_rocket_profit': ``,
    'user.transfer_show_selling_price': ``,
    //TARIFAS PARA CLIENTES
    'userRate.id_prefix': `Selecione o prefixo que você deseja subscrever.`,
    'userRate.rateinitial': `Novo preço de vendapara este prefixo`,
    'userRate.initblock': `Mínimo de venda`,
    'userRate.billingblock': `Bloco de venda`,
    //VOUCHER
    'voucher.credit': `Valor do VOUCHER`,
    'voucher.id_plan': `Plano que será usado no cliente que usar este crédito.`,
    'voucher.language': `Idioma que será usado`,
    'voucher.prefix_local': `Regra que será usado no campo DDD do cliente`,
    'voucher.quantity': `Quantos VOUCHER você deseja gerar?`,
    'voucher.tag': ``,
    'voucher.voucher': ``,
});