Help.load({
    //API
    'api.id_user': `You need use the MagnusBilling API from https://github.com/magnussolution/magnusbilling-api-php. The username owner this API`,
    'api.api_key': `This apy key will be necessary to execute the API`,
    'api.api_secret': `This apy secret will be necessary to execute the API`,
    'api.status': `You can activete or inactivate this API`,
    'api.action': `Which action the user will have execute`,
    'api.api_restriction_ips': `What IPS you want allow access this API. Leave blank to allow any IP. It is very recomended set the IPS`,
    //CDR
    'call.starttime': `Start time of the call`,
    'call.src': `SIP Account that made the call`,
    'call.callerid': `Number sent to the trunk as the identifier of the call.||
    If the trunk accepts the sent CallerID, then this number will be used as the identifier.
    In order to this work its going to be necessary to have the Fromuser field in the trunk empty.`,
    'call.calledstation': `Number dialed by the client.`,
    'call.idPrefixdestination': `Name of the destination, this name is a relation to the prefix menu.`,
    'call.idUserusername': `User that made the call, the one who the call cost was taken from.`,
    'call.idTrunktrunkcode': `Trunk that was used to complete the call.`,
    'call.sessiontime': `Duration of the call in seconds.`,
    'call.buycost': `Buy cost. Click to understand how the cost is calculated|https://wiki.magnusbilling.org/en/source/price_calculation.html.`,
    'call.sessionbill': `Sell price, the value that was taken from the client. Click to understand how the cost is calculated|https://wiki.magnusbilling.org/en/source/price_calculation.html.`,
    'call.agent_bill': `Sell price, the value that was taken from the client. Click to understand how the cost is calculated|https://wiki.magnusbilling.org/en/source/price_calculation.html.`,
    'call.uniqueid': `Unique ID generated by Asterisk, this field is also the start time of the call in Epoch Unix.`,
    //CALL ARCHIVE
    'callarchive.calledstation': `Number dialed by the client.`,
    'callarchive.sessiontime': `Duration of the call in seconds.`,
    'callarchive.buycost': `Buy cost. Click to understand how the cost is calculated|https://wiki.magnusbilling.org/en/source/price_calculation.html`,
    'callarchive.sessionbill': `Buy cost. Click to understand how the cost is calculated|https://wiki.magnusbilling.org/en/source/price_calculation.html`,
    'callarchive.agent_bill': `Buy cost. Click to understand how the cost is calculated|https://wiki.magnusbilling.org/en/source/price_calculation.html`,
    //CALLBACK
    'callback.id_user': `Owner of the DID that received the CallBack request.`,
    'callback.exten': `Number of who called the DID requesting the CallBack`,
    'callback.status': `Status of the call||The statuses are:
    * Active
        The CallBack still hasn't been processed.
    * Pending
        MagnusBilling processed the CallBack and sent it to the trunk.
    * Sent
        The CallBack has been processed successfully.
    * Outside of the time range
        The call was received outside of the time range configured in the DID menu, tab CallBack Pro.
    .`,
    //CALLERID
    'callerid.id_user': `Select user.`,
    'callerid.cid': `The number to CID authenticate with CallingCard. Use the exact format that you received the CallerID from your DID provider.`,
    'callerid.name': `Optional.`,
    'callerid.activated': `Status of the CallerID.`,
    //CALLS ONLINE
    'callonline.idUserusername': `Main user of the SIP account that started the call.`,
    'callonline.sip_account': `SIP Account that requested the call.`,
    'callonline.idUsercredit': `User credit.`,
    'callonline.ndiscado': `Dialed number.`,
    'callonline.codec': `Codec used.`,
    'callonline.callerid': `The CallerID number.`,
    'callonline.tronco': `Trunk that was used to complete the call.`,
    'callonline.reinvite': `Reinvite is the parameter that informs if the audio is passing through Asterisk or if its going through the client and trunk. Click to learn more about this option|https://wiki.magnusbilling.org/en/source/asterisk_options/directmedia.html.`,
    'callonline.from_ip': `IP of the caller.`,
    'callonline.description': `Data from the sip show channel command.`,
    //BOOTHS REPORT
    'callshopcdr.id_user': `User.`,
    //SUMMARY PER DAY
    'callsummarycallshop.sumsessiontime': `Sum of call minutes.`,
    'callsummarycallshop.sumprice': `Total value.`,
    'callsummarycallshop.sumlucro': `Sum of the earnings.`,
    'callsummarycallshop.sumbuycost': `Sum of the buy cost.`,
    'callsummarycallshop.sumnbcall': `Total of calls.`,
    //SUMMARY DAY AGENT
    'callsummarydayagent.sumsessiontime': `Sum of call minutes.||Its possible to use filters like showing only the last few days of the week or a specific reseller. This summary will only show the data related to the filter made.`,
    'callsummarydayagent.sumsessionbill': `Sum of the sell price.`,
    'callsummarydayagent.sumbuycost': `Sum of the buy cost.`,
    'callsummarydayagent.sumlucro': `Sum of the earnings.`,
    'callsummarydayagent.sumnbcall': `Total of calls.`,
    //SUMMARY DAY TRUNK
    'callsummarydaytrunk.sumsessiontime': `Sum of call minutes.||Its possible to use filters like showing only the last few days of the week or a specific reseller. This summary will only show the data related to the filter made.`,
    'callsummarydaytrunk.sumsessionbill': `Sum of the sell price.`,
    'callsummarydaytrunk.sumbuycost': `Sum of the buy cost.`,
    'callsummarydaytrunk.sumlucro': `Sum of the earnings.`,
    'callsummarydaytrunk.sumnbcall': `Total of calls.`,
    //SUMMARY DAY USER
    'callsummarydayuser.sumsessiontime': `Sum of call minutes.||Its possible to use filters like showing only the last few days of the week or a specific reseller. This summary will only show the data related to the filter made.`,
    'callsummarydayuser.sumlucro': `Sum of the earnings.`,
    'callsummarydayuser.sumnbcall': `Total of calls.`,
    //SUMMARY MONTH TRUNK
    'callsummarymonthtrunk.sumsessiontime': `Sum of call minutes.||Its possible to use filters like showing only the last few days of the week or a specific reseller. This summary will only show the data related to the filter made.`,
    'callsummarymonthtrunk.sumsessionbill': `Sum of the sell price.`,
    'callsummarymonthtrunk.sumbuycost': `Sum of the buy cost.`,
    'callsummarymonthtrunk.sumlucro': `Sum of the earnings.`,
    'callsummarymonthtrunk.sumnbcall': `Total of calls.`,
    //SUMMARY MONTH USER
    'callsummarymonthuser.sumsessiontime': `Sum of call minutes.||Its possible to use filters like showing only the last few days of the week or a specific reseller. This summary will only show the data related to the filter made.`,
    'callsummarymonthuser.sumlucro': `Sum of the earnings.`,
    'callsummarymonthuser.sumnbcall': `Total of calls.`,
    //SUMMARY PER DAY
    'callsummaryperday.sumsessiontime': `Sum of call minutes.||Its possible to use filters like showing only the last few days of the week or a specific reseller. This summary will only show the data related to the filter made.`,
    'callsummaryperday.sumsessionbill': `Sum of the sell price.`,
    'callsummaryperday.sumbuycost': `Sum of the buy cost.`,
    'callsummaryperday.sumlucro': `Sum of the earnings.`,
    'callsummaryperday.sumnbcall': `Total of calls.`,
    'callsummaryperday.sumnbcallfail': `Total of calls that failed.`,
    //SUMMARY PER MONTH
    'callsummarypermonth.sumsessiontime': `Sum of call minutes.||Its possible to use filters like showing only the last few days of the week or a specific reseller. This summary will only show the data related to the filter made.`,
    'callsummarypermonth.sumsessionbill': `Sum of the sell price.`,
    'callsummarypermonth.sumbuycost': `Sum of the buy cost.`,
    'callsummarypermonth.sumlucro': `Sum of the earnings.`,
    'callsummarypermonth.sumnbcall': `Total of calls.`,
    //SUMMARY PER TRUNK
    'callsummarypertrunk.sumsessiontime': `Sum of call minutes.||Its possible to use filters like showing only the last few days of the week or a specific reseller. This summary will only show the data related to the filter made.`,
    'callsummarypertrunk.sumsessionbill': `Sum of the sell price.`,
    'callsummarypertrunk.sumbuycost': `Sum of the buy cost.`,
    'callsummarypertrunk.sumlucro': `Sum of the earnings.`,
    'callsummarypertrunk.sumnbcall': `Total of calls.`,
    'callsummarypertrunk.sumnbcallfail': `Total of calls that failed.`,
    //SUMMARY PER USER
    'callsummaryperuser.sumsessiontime': `Sum of call minutes.||Its possible to use filters like showing only the last few days of the week or a specific reseller. This summary will only show the data related to the filter made.`,
    'callsummaryperuser.sumlucro': `Sum of the earnings.`,
    'callsummaryperuser.sumnbcall': `Total of calls.`,
    'callsummaryperuser.sumnbcallfail': `Total of calls that failed.`,
    //CAMPAIGNS
    'campaign.id_user': `User that owns the campaign.`,
    'campaign.id_plan': `What plan do you want to use to bill this campaign?`,
    'campaign.name': `Name of the campaign.`,
    'campaign.status': `Status of the campaign.`,
    'campaign.startingdate': `The campaign will start from this date.`,
    'campaign.expirationdate': `The campaign will stop in this date.`,
    'campaign.type': `Choose Voice or SMS. If you choose Voice you will need to import audio. If you choose SMS you will need to set the text in the SMS tab.`,
    'campaign.audio': `Available to massive calling. The audio needs to be compatible with Asterisk. The recomended format is GSM or WAV(8k hz mono).`,
    'campaign.audio_2': `If you use TTS, the name will be executed between Audio and Audio2.`,
    'campaign.restrict_phone': ``,
    'campaign.auto_reprocess': `If there are no active numbers in this campaign phone book, reactivates all pending numbers.`,
    'campaign.id_phonebook': `Select one or more phonebooks to to be used.`,
    'campaign.digit_authorize': `Do you want to forward the call after the audio?  E.g, if the callee presses 1, he gets sent to SIP account XXXX. Set Number to Forward = 1, Forward Type = SIP and select the SIP account to send the callee to. Set -1 to disable.`,
    'campaign.type_0': `Choose the type of redirect. This will send the call to the chosen destination.`,
    'campaign.id_ivr_0': `Choose a IVR to send the call to. The IVR needs to belong to the owner of the campaign.`,
    'campaign.id_queue_0': `Choose a Queue to send the call to. The Queue needs to belong to the owner of the campaign.`,
    'campaign.id_sip_0': `Choose a SIP Account to send the call to. The SIP Account needs to belong to the owner of the campaign.`,
    'campaign.extension_0': `Click for more details||There are two options available.
    *Group, the group name should be put here exactly as it is in the SIP Accounts that should receive the calls.
    *Personalized, you may execute any valid option via Asterisk's DIAL command. Example: SIP/sipaccount,45,tTr.`,
    'campaign.daily_start_time': `Time that the campaign will start sending.`,
    'campaign.daily_stop_time': `Time that the campaign will stop sending.`,
    'campaign.monday': `Activating this option the system will send calls on Mondays.`,
    'campaign.tuesday': `Activating this option the system will send calls on Tuesdays.`,
    'campaign.wednesday': `Activating this option the system will send calls on Wednesdays.`,
    'campaign.thursday': `Activating this option the system will send calls on Thursdays.`,
    'campaign.friday': `Activating this option the system will send calls on Fridays.`,
    'campaign.saturday': `Activating this option the system will send calls on Saturdays.`,
    'campaign.sunday': `Activating this option the system will send calls on Sundays.`,
    'campaign.frequency': `How many numbers will be processed per minute?||This value will be divided by 60 seconds and the calls will be sent every minute at the same time.`,
    'campaign.max_frequency': `This is the maximum value that the client will be able to set. If you set it to 50 the user will be able to change to any value that is 50 or less than 50.`,
    'campaign.nb_callmade': `Used to control the max completed calls.`,
    'campaign.enable_max_call': `If activated MagnusBilling will check how many calls were already made and have a duration total bigger than the audios. If the quantity is equal or bigger than the value set in the field, the campaign will be deactivated.`,
    'campaign.secondusedreal': `Maximum amount of complete calls. You need to activate the field above to use this.`,
    'campaign.description': `This field has different uses if the campaign is sending Voice or SMS.||Uses:
    * Voice: This field is simply a description of the campaign.
    * SMS: The text in here is going to be sent to the numbers. You may use the var %name% where you want to use the name of the customer. Example:
    Hello %name%`,
    'campaign.tts_audio': `With this setting the system will generate the audio 1 for the campaign via TTS.||In order for this to work, you will need to set the TTS URL under Settings, Configuration, TTS URL.`,
    'campaign.tts_audio2': `Same setting as the previous field but for audio 2. Keep in mind that in between audio 1 and 2, the TTS executes the name imported with the number.`,
    'campaign.record_call': `Record the calls of the campaign. They only will be recorded if the call is transferred.`,
    //CAMPAIGNS DASHBOARD
    'campaigndashboard.name': `Name of the campaign.`,
    //CALL PER MINUTES
    'campaignlog.total': `Total of calls.`,
    //POLLS
    'campaignpoll.id_campaign': `Choose the campaign that will execute this poll.`,
    'campaignpoll.name': `Name of the poll. This name is seen on your end only.`,
    'campaignpoll.repeat': `How many times should MagnusBilling repeat the poll audio if the client didn't press any valid option.||You may check what are the options under the option tab.`,
    'campaignpoll.request_authorize': `In some cases, you will need to request for compliance in order to execute the poll. If that's the case, select Yes.`,
    'campaignpoll.digit_authorize': `Digit to authorize the excution of the poll.`,
    'campaignpoll.arq_audio': `Audio file. Please use a GSM or WAV 8khz mono audio file.`,
    'campaignpoll.description': `Description of the poll.`,
    'campaignpoll.option0': `Describe the option||Example poll:
    Who will you vote for?
    Press 1 for option one
    Press 2 for option two
    Press 3 for option three
    
    .. image:: ../img/poll_options.png
    :scale: 100% 
    
    These settings will be useful when reading the poll summary.

    `,
    'campaignpoll.option1': `Describe the option. Read the description of option 0.`,
    'campaignpoll.option2': `Describe the option. Read the description of option 0.`,
    'campaignpoll.option3': `Describe the option. Read the description of option 0.`,
    'campaignpoll.option4': `Describe the option. Read the description of option 0.`,
    'campaignpoll.option5': `Describe the option. Read the description of option 0.`,
    'campaignpoll.option6': `Describe the option. Read the description of option 0.`,
    'campaignpoll.option7': `Describe the option. Read the description of option 0.`,
    'campaignpoll.option8': `Describe the option. Read the description of option 0.`,
    'campaignpoll.option9': `Describe the option. Read the description of option 0.`,
    //POLLS REPORTS
    'campaignpollinfo.number': `Number of the person who voted.`,
    'campaignpollinfo.resposta': `Option chosen.`,
    //RESTRICT PHONE
    'campaignrestrictphone.number': `Number that should be blocked. Its necessary to activate the blocked numbers option in the campaign.`,
    //CONFIGURATION
    'configuration.config_value': `Value. Click here to read more about the options of this menu.|https://wiki.magnusbilling.org/en/source/config.html.`,
    'configuration.config_description': `Description. Click here to read more about the options of this menu.|https://wiki.magnusbilling.org/en/source/config.html`,
    //DIDS
    'did.did': `The exact number coming from the context in Asterisk. We recommend you to always use the E164 format.`,
    'did.activated': `Only active numbers can receive calls.`,
    'did.callerid': `Use this field to set a CallerID name or leave it blank to use the received CallerID from the DID provider.`,
    'did.connection_charge': `Activation cost. This value will be deducted from the client the moment that the DID is associated with the user.`,
    'did.fixrate': `Monthly price. This value will be deducted automatically every month from the user's balance. If the client doesn't have enough credit the DID will be cancelled automatically.`,
    'did.connection_sell': `This is the value that will be charged for each call. Simply by picking up the call, this value will be deducted.`,
    'did.minimal_time_charge': `Minimum time to tariff the DID. If you set it to 3 any call that with lower duration will not be charged for.`,
    'did.initblock': `Minimum time in seconds to buy. If you set it to 30 and the call duration is 10, the call will be billed as 30.`,
    'did.increment': `This defines the block in which the call billing time will be incremented, in seconds. If set to 6 and call duration is 32, the call will be billed as 36.`,
    'did.charge_of': `The user that will be charged for the DID cost.`,
    'did.calllimit': `Maximum simultaneous calls for this DID.`,
    'did.description': `You may take notes here!`,
    'did.expression_1': `This is a regular expression to tariff the DID depending on who is calling it.||Lets analyze a real example:
    Suppose we want to charge 0.10 when we receive a call from a landline and 0.20 if its a mobile phone and block any other format.
    In this example we will create rules to identify the CallerID in the format 0 + area code + number, area code + number, or 55 + area code + number.

    Take a look at the following image on what the result would look like:
    
    .. image:: ../img/did_regex.png
    :scale: 100% 


    Regular expression for mobile
    ^[1-9][0-9]9\d{8}$|^0[1-9][0-9]9\d{8}$|^55[1-9][0-9]9\d{8}$

    Regular expression for landline
    ^[1-9][0-9]\d{8}$|^0[1-9][0-9]\d{8}$|^55[1-9][0-9]\d{8}$


    `,
    'did.selling_rate_1': `Price per minute if the number matches the above regular expression.`,
    'did.block_expression_1': `Set to yes to block calls that matches with the above regular expression.`,
    'did.send_to_callback_1': `Send this call to CallBack if it matches with the above regular expression.`,
    'did.expression_2': `Same as the first expression. Click for more info.|https://wiki.magnusbilling.org/en/source/modules/did/did.html#did-expression-1.`,
    'did.selling_rate_2': `Price per minute if the number matches the above regular expression.`,
    'did.block_expression_2': `Set to yes to block calls that matches with the above regular expression.`,
    'did.send_to_callback_2': `Send this call to CallBack if it matches with the above regular expression.`,
    'did.expression_3': `Same as the first expression. Click for more info.|https://wiki.magnusbilling.org/en/source/modules/did/did.html#did-expression-1.`,
    'did.selling_rate_3': `Price per minute if the number matches the above regular expression.`,
    'did.block_expression_3': `Set to yes to block calls that matches with the above regular expression.`,
    'did.send_to_callback_3': `Send this call to CallBack if it matches with the above regular expression.`,
    'did.cbr': `Enables CallBack Pro.`,
    'did.cbr_ua': `Execute an audio.`,
    'did.cbr_total_try': `How many times will the system try to return the call?`,
    'did.cbr_time_try': `Time interval between each try, in minutes.`,
    'did.cbr_em': `Execute an audio before the call is answered. Your DID provider needs to allow early media.`,
    'did.TimeOfDay_monFri': `Example: if your company only callbacks to the callee if the call was placed in between 09:00-12:00 and 14:00-18:00 MON-FRY, between this time interval the workaudio is going to be played and then callback to the callee. You can use multiple time intervals separated by |.`,
    'did.TimeOfDay_sat': `The same but for Saturday.`,
    'did.TimeOfDay_sun': `The same but for Sunday.`,
    'did.workaudio': `Audio that will be executed when a call is received at the time interval.`,
    'did.noworkaudio': `Audio that will be executed when a call is received out of the time interval.`,
    'did.record_call': `Record calls for this DID. Recorded regardless of destination.`,
    //DID DESTINATION
    'diddestination.id_did': `Select the DID that you want create new destination for.`,
    'diddestination.id_user': `User that will be the owner of this DID.`,
    'diddestination.activated': `Only active destinations will be used.`,
    'diddestination.priority': `You can create up to 5 destinations for your DID. If a try is made and a error is received, MagnusBilling will try to send the call to the next destination priority available. Only works with the "SIP call" type.`,
    'diddestination.voip_call': `Type of destination.`,
    'diddestination.destination': `Use this to take notes!`,
    'diddestination.id_ivr': `Select a IVR to send the call to. The IVR needs to belong to the owner of the DID aswell.`,
    'diddestination.id_queue': `Select a Queue  to send the call to. The Queue needs to belong to the owner of the DID aswell.`,
    'diddestination.id_sip': `Select a SIP Account to send the call to. The SIP Account needs to belong to the owner of the DID aswell.`,
    'diddestination.context': `In this field you may use a context in the format supported by Asterisk||Example:
    
_X. => 1,Dial(SIP/sipaccount,45)
same => n,Goto(s-\${DIALSTATUS},1)


exten => s-NOANSWER,1,Hangup
exten => s-CONGESTION,1,Congestion
exten => s-CANCEL,1,Hangup
exten => s-BUSY,1,Busy
exten => s-CHANUNAVAIL,1,SetCallerId(4545454545)
exten => s-CHANUNAVAIL,2,Dial(SIP/sipaccount2,,T)


You should NOT set a name for the context because the name will be set automatically as [did-number-of-the-did]

You may take a look at the context at /etc/asterisk/extensions_magnus_did.conf
    
    `,
    //DIDS USE
    'diduse.id_user': `User that owns the DID.`,
    'diduse.id_did': `DID Number`,
    'diduse.reservationdate': `Day that the DID was reserved for the user.`,
    //FAIL2BAN
    'firewall.ip': `IP Address.`,
    'firewall.action': `With this option marked on YES, the IP will be placed on the ip-blacklist list of fail2ban and will be blocked forever. ||The option will NOT block the IP momentarily according the parameters of the file /etc/fail2ba/jail.local.
    
    By default the IP is going to stay blocked for 10 minutes`,
    'firewall.description': `These informations are captured from the log file /var/log/fail2ban.log || It's possible to track this LOG with the command 
    
    tail -f /var/log/fail2ban.log`,
    //TOKEN
    'gauthenticator.username': `The user that wants to activate TOKEN`,
    'gauthenticator.googleAuthenticator_enable': `After activating the TOKEN for the user, login will be only possible using the generated TOKEN by the Google Aunthenticator APP.||After activating the TOKEN, in the next user login will be requested to scan the QR CODE as shown in the image below
    
.. image:: ../img/token.png
    :scale: 100% 
    
To scan the code will be necessary to install the Google Aunthenticator APP, this APP wil be avaible to download in the app store for IOS and Android.

It's important to save the manual code shown in the image, in case if you ever need to activate the token in another cellphone the code will be necessary.


With the token of Google Aunthentitor will be only possible to login into the panel or deactivate the token function`,
    'gauthenticator.code': `The code will be necessary to deactivate the TOKEN. In case if you don't have the code anymore, will be necessary to deactivate via the database.`,
    'gauthenticator.google_authenticator_key': `This KEY will be necessary to activate the TOKEN in a different cellphone`,
    //GROUPMODULE
    'groupmodule.id_group': `User group`,
    'groupmodule.id_module': `Menu`,
    //GROUP USERS
    'groupuser.name': `Name of the user group`,
    //GROUP TO ADMINS
    'groupusergroup.name': `Group name`,
    'groupusergroup.user_prefix': `Filling this field, all users created by an administrator that uses this group will be initialized with this prefix.`,
    'groupusergroup.id_group': `Which client groups will the administrator group have access.|| When an administrator that belongs to this group login, only the administrator will see the client data of the selected groups`,
    //IAX USERS
    'iax.id_user': `The user whose IAX account will belong`,
    'iax.username': `The user that will be used to authenticate in the softphone`,
    'iax.secret': `The Password that will be used to authenticate in the softphone`,
    'iax.callerid': `This is the CallerID that will be shown in their destination, in external calls the provider will need to permit CLI to be correctly identified in their destination.`,
    'iax.disallow': `In this option will be possible to deactivate codecs. To deactivate all the codecs and letting avaible to the user only what you select below, use "Use all"`,
    'iax.allow': `Codecs that will be accepted.`,
    'iax.host': `"Dynamic" is an option that will let the user register his account in any IP. If you want to to authenticate the user by their IP, fill here the IP of the client, let the password field blank and put "insecure" for the port/invite in the tab "Additional Information"`,
    'iax.nat': `The client is behind NAT? Click here for more information|https://www.voip-info.org/asterisk-sip-nat/.`,
    'iax.context': `This is the context that the call will be processed, by default is set to "billing". Only alter if you have knowledge of Asterisk.`,
    'iax.qualify': `Sent the "OPTION" package to verify if the user is online.||Sintaxe:
    
qualify = xxx | no | yes
    
Where the XXX is the number of milliseconds used. If "yes", the time configurated in sip.conf is used, by default is set to 2 seconds.

If you activate "qualify", the Asterisk will sent the command "OPTION" to SIP peer regulary to verify if the device is still online.
If the device don't answer the "OPTION" in the set period of time, Asterisk will consider the device offline for future calls.

This status can be verified with the function "sip show peer XXXX", this funcition will only provide status informations to the SIP peer that have "qualify = yes".`,
    'iax.dtmfmode': `Type of DTMF. Click here for more informations|https://www.voip-info.org/asterisk-sip-dtmfmode/.`,
    'iax.insecure': `If the host is set to "dynamic", this option will need to be set to "no". To authenticate via IP and alter to port. Click here for more information|https://www.voip-info.org/asterisk-sip-insecure/.`,
    'iax.type': `Default type is "friend", in other words they can make and receive calls. Click here for more informations|https://www.voip-info.org/asterisk-sip-type/.`,
    'iax.calllimit': `Total of simultaneous calls allowed for this IAX account.`,
    //IVRS
    'ivr.name': `Name of the IVR`,
    'ivr.id_user': `User who owns the IVR`,
    'ivr.monFriStart': `Weekly interval of attendance, can be configurated with multiples shifts.||Example:
Supposing that the attendance hours are 08h to 12h and 14h to 19h. In this case the rule would be

08:00-12:00|14:00-19:00

`,
    'ivr.satStart': `Interval of attendance in saturdays, can be configurated with multiple shifts||Example:

Supposing that the attendance hours in the saturdays are 08h to 13h. In this case the rule would be
    
08:00-13:00`,
    'ivr.sunStart': `Interval of attendance in sundays, can be configurated with multiple shifts||Example:
    
Supposing that theres no attendance hours in the sundays. In this case the rule would be
    
00:00-00:00
    
`,
    'ivr.workaudio': `Audio to play in the attendance hours.`,
    'ivr.noworkaudio': `Audio to play when it's not attendance hours`,
    'ivr.option_0': `Select the destiny if the option 0 is pressed. Let it in blank if don't want any action`,
    'ivr.option_1': `Select the destiny if the option 1 is pressed. Let it in blank if don't want any action`,
    'ivr.option_2': `Select the destiny if the option 2 is pressed. Let it in blank if don't want any action`,
    'ivr.option_3': `Select the destiny if the option 3 is pressed. Let it in blank if don't want any action`,
    'ivr.option_4': `Select the destiny if the option 4 is pressed. Let it in blank if don't want any action`,
    'ivr.option_5': `Select the destiny if the option 5 is pressed. Let it in blank if don't want any action`,
    'ivr.option_6': `Select the destiny if the option 6 is pressed. Let it in blank if don't want any action`,
    'ivr.option_7': `Select the destiny if the option 7 is pressed. Let it in blank if don't want any action`,
    'ivr.option_8': `Select the destiny if the option 8 is pressed. Let it in blank if don't want any action`,
    'ivr.option_9': `Select the destiny if the option  is pressed. Let it in blank if don't want any action`,
    'ivr.option_10': `Select the destiny if none of the options was selected.`,
    'ivr.direct_extension': `Activating this option will be able to type an SIP account to call it directly.`,
    'ivr.option_out_0': `Select the destiny if the option 0 is pressed. Let it in blank if don't want any action`,
    'ivr.option_out_1': `Select the destiny if the option 1 is pressed. Let it in blank if don't want any action`,
    'ivr.option_out_2': `Select the destiny if the option 2 is pressed. Let it in blank if don't want any action`,
    'ivr.option_out_3': `Select the destiny if the option 3 is pressed. Let it in blank if don't want any action`,
    'ivr.option_out_4': `Select the destiny if the option 4 is pressed. Let it in blank if don't want any action`,
    'ivr.option_out_5': `Select the destiny if the option 5 is pressed. Let it in blank if don't want any action`,
    'ivr.option_out_6': `Select the destiny if the option 6 is pressed. Let it in blank if don't want any action`,
    'ivr.option_out_7': `Select the destiny if the option 7 is pressed. Let it in blank if don't want any action`,
    'ivr.option_out_8': `Select the destiny if the option 8 is pressed. Let it in blank if don't want any action`,
    'ivr.option_out_9': `Select the destiny if the option 9 is pressed. Let it in blank if don't want any action`,
    'ivr.option_out_10': `Select the destiny if none of the options was selected.`,
    //LOG USERS
    'logusers.id_user': `User that executed the action.`,
    'logusers.id_log_actions': `Type of action.`,
    'logusers.ip': `IP utilized for the action.`,
    'logusers.description': `What was done, normally is in JSON.`,
    //PAYMENT METHODS
    'methodpay.show_name': `The name that is shown in the client panel.`,
    'methodpay.id_user': `The user payment method. You can create payment methods for administrators or resellers. `,
    'methodpay.country': `Only for reference.`,
    'methodpay.active': `Activate this if you want to be avaible for the clients.`,
    'methodpay.min': `Mininum accepted value.`,
    'methodpay.max': `Maximun accepted value.`,
    'methodpay.username': `User payment method`,
    'methodpay.url': `Payment method URL, in the most cases the methods this URL is already preconfigurated.`,
    'methodpay.fee': `Payment method fee.`,
    'methodpay.pagseguro_TOKEN': `Payment method TOKEN`,
    'methodpay.P2P_CustomerSiteID': `This field is exclusive for some payments methods.`,
    'methodpay.P2P_KeyID': `This field is exclusive for some payments methods.`,
    'methodpay.P2P_Passphrase': `This field is exclusive for some payments methods.`,
    'methodpay.P2P_RecipientKeyID': `This field is exclusive for some payments methods.`,
    'methodpay.P2P_tax_amount': `This field is exclusive for some payments methods.`,
    'methodpay.client_id': `This field is exclusive for some payments methods.`,
    'methodpay.client_secret': `This field is exclusive for some payments methods.`,
    //MENUS
    'module.text': `Menu name `,
    'module.icon_cls': `Icon, default font "awesome V4".`,
    'module.id_module': `Menu which this menu belongs. In case the menu is blank, it's a main menu`,
    'module.priority': `Order that the menu will be shown in the menu`,
    //OFFERS
    'offer.label': `Offer name`,
    'offer.packagetype': `Type of package, there's 3 types. Unlimited calls, free calls or free seconds. `,
    'offer.freetimetocall': `In this field is where the package avaible quantity configuration will occur.||Example:
* Unlimited calls: In this option the field is blank, because will be allowed to call without any control.
* Free calls: Configure the amount of free calls that you want to give.
* Free seconds: Configure the amount of seconds that you want to allow the client to call.`,
    'offer.billingtype': `This is the period that the package will be calculated.|| Look the description:
* Monthly: The system will verify the day of the plan activation + 30 days that the client reached the package limit.
* Weekly: The system will verify the day of the plan activation + 7 days that the client reached the package limit.`,
    'offer.price': `Price that will be charged monthly to the client.||If on the expiry day the client don't have the sufficient funds to pay the package // NEED TO FINISH "dar baixa?" //
    
In the settings menu, ajusts, exist one option named Package Offer Notification, this value`


                        //NEED TO FINISH UPPER LINE "offer.price"


    //OFFER CDR
    'offercdr.id_user': `User that made the call.`,
    //OFFER CDR
    'offercdr.id_user': ``,
    'offercdr.id_offer': `Name of the offer.`,
    'offercdr.used_secondes': `Call duration.`,
    'offercdr.date_consumption': `Date and hour of the call.`,
    //OFFER USE
    'offeruse.id_user': `User that made  the call.`,
    'offeruse.id_offer': `Name of the offer.`,
    'offeruse.month_payed': `Paid months.`,
    'offeruse.reservationdate': `Date and hour that the offer was canceled.`,
    //PHONEBOOKS
    'phonebook.name': `Phonebook name.`,
    'phonebook.status': `Phonebook status.`,
    'phonebook.description': `Phonebook description, personal control only.`,
    //PHONENUMBERS
    'phonenumber.id_phonebook': `Phonebook that this number belongs to.`,
    'phonenumber.number': `Number to send calls/sms. Use only E164 format`,
    'phonenumber.name': `Number owner name, used for TTS or SMS`,
    'phonenumber.city': `Client city, not required field.`,
    'phonenumber.status': ``,
    'phonenumber.info': `Phonebook description, personal control only||When used for survey, will be saved here what the number that the client typed.`,
    //PLANS
    'plan.name': `Plan name`,
    'plan.signup': ``,
    'plan.ini_credit': ``,
    'plan.play_audio': ``,
    'plan.techprefix': ``,
    'plan.id_service': ``,
    //PREFIXES
    'prefix.prefix': `Prefix code. Prefix will be used to tariff and bill the calls.`,
    'prefix.destination': `Destination name.`,
    //PROVIDERS
    'provider.provider_name': `Provider name`,
    'provider.credit': `How much credit do you have in your provider account? This field is optional.`,
    'provider.credit_control': `If you set to YES and your provider credit is < 0, all trunks from this provider will be deactivated.`,
    'provider.description': ``,
    //QUEUES
    'queue.id_user': ``,
    'queue.name': ``,
    'queue.language': ``,
    'queue.strategy': ``,
    'queue.ringinuse': ``,
    'queue.timeout': `How long the phone will ring until timeout`,
    'queue.retry': `Time in seconds to try another agent.`,
    'queue.wrapuptime': `Time in seconds until the agent receives another call.`,
    'queue.weight': `Weight of queue - when compared to other queues, higher weights get the first try at available channels when the same channel is included in more than one queue.`,
    'queue.periodic-announce': `A set of periodic announcements can be created by separating each announcements to reproduce whit commas. E.g.: queue-periodic-announce,your-call-is-important,please-wait`,
    'queue.periodic-announce-frequency': `How often to make a periodic announcement.`,
    'queue.announce-position': `Queue position announce?`,
    'queue.announce-holdtime': `Should we include an estimated hold time in the position announcements?`,
    'queue.announce-frequency': `How often to announce queue position and/or estimated holdtime to caller 0=off`,
    'queue.joinempty': ``,
    'queue.leavewhenempty': ``,
    'queue.max_wait_time': `Maximum wait time on the queue`,
    'queue.max_wait_time_action': `SipAccount, IVR or QUEUE to send the caller if the maximum wait time is reached. Use: SIP/sip_account, QUEUE/queue_name or IVR/ivr_name.`,
    'queue.ring_or_moh': ``,
    'queue.musiconhold': ``,
    //QUEUES MEMBERS
    'queuemember.queue_name': ``,
    'queuemember.interface': ``,
    'queuemember.paused': ``,
    //TARIFFS
    'rate.id_plan': `The plan that you want to create a tariff for.`,
    'rate.id_prefix': `The prefix that you want create a tariff for.`,
    'rate.id_trunk_group': ``,
    'rate.rateinitial': `How much do you want to charge per minute?`,
    'rate.initblock': `Minimum time in seconds to buy. E.g., if set to 30s and the call duration is 21s, charged for 30s.`,
    'rate.billingblock': `This defines how the time is incremented after the minimum. E.g, if set to 6s and call duration is 32s, charged for 36.`,
    'rate.minimal_time_charge': ``,
    'rate.additional_grace': `Aditional time to add to call duration. Ex: the call duration 20s and you add here 3s, will be charged 23 seconds.`,
    'rate.package_offer': `Set to yes if you want to include this tariff to a package offer.`,
    'rate.status': ``,
    //BOOTHS TARIFFS
    'ratecallshop.dialprefix': ``,
    'ratecallshop.destination': ``,
    'ratecallshop.buyrate': ``,
    'ratecallshop.minimo': ``,
    'ratecallshop.block': ``,
    'ratecallshop.minimal_time_charge': ``,
    //PROVIDER RATES
    'rateprovider.id_provider': ``,
    'rateprovider.id_prefix': ``,
    'rateprovider.buyrate': ``,
    'rateprovider.buyrateinitblock': ``,
    'rateprovider.buyrateincrement': ``,
    'rateprovider.minimal_time_buy': ``,
    //REFILLS
    'refill.id_user': ``,
    'refill.credit': ``,
    'refill.description': ``,
    'refill.payment': `This setting is only to your control, the credit will be released to the user anyway if set to Payment NO`,
    'refill.invoice_number': ``,
    //REFILL PROVIDERS
    'refillprovider.id_provider': ``,
    'refillprovider.credit': ``,
    'refillprovider.description': ``,
    'refillprovider.payment': ``,
    //RESTRICTED NUMBER
    'restrictedphonenumber.id_user': ``,
    'restrictedphonenumber.number': ``,
    'restrictedphonenumber.direction': ``,
    //SEND CREDIT PRODUCTS
    'sendcreditproducts.country': ``,
    'sendcreditproducts.operator_name': ``,
    'sendcreditproducts.operator_id': ``,
    'sendcreditproducts.SkuCode': ``,
    'sendcreditproducts.product': ``,
    'sendcreditproducts.send_value': ``,
    'sendcreditproducts.wholesale_price': ``,
    'sendcreditproducts.provider': ``,
    'sendcreditproducts.status': ``,
    'sendcreditproducts.info': ``,
    //SEND CREDIT RATES
    'sendcreditrates.idProductcountry': ``,
    'sendcreditrates.idProductoperator_name': ``,
    'sendcreditrates.sell_price': ``,
    //SEND CREDIT SUMMARY
    'sendcreditsummary.id_user': ``,
    //SERVERS
    'servers.name': ``,
    'servers.host': ``,
    'servers.public_ip': ``,
    'servers.username': ``,
    'servers.password': ``,
    'servers.port': ``,
    'servers.sip_port': ``,
    'servers.type': ``,
    'servers.weight': ``,
    'servers.status': ``,
    'servers.description': ``,
    //SERVICES
    'services.type': ``,
    'services.name': ``,
    'services.calllimit': ``,
    'services.disk_space': `Insert the space available to record in GB.`,
    'services.sipaccountlimit': ``,
    'services.price': ``,
    'services.return_credit': `Return credit to the user if they cancel before the expiration date.`,
    'services.description': ``,
    //SERVICES USE
    'servicesuse.id_user': ``,
    'servicesuse.id_services': ``,
    'servicesuse.price': ``,
    'servicesuse.method': ``,
    'servicesuse.reservationdate': ``,
    //SIP USERS
    'sip.id_user': ``,
    'sip.defaultuser': `Username used to login in a SIP device.`,
    'sip.secret': `Password to login in a SIP device.`,
    'sip.callerid': `The Caller ID number. Your trunk needs to accept CLI.`,
    'sip.alias': `Alias to dial between sip accounts from the same AccountCode (company).`,
    'sip.disallow': `Disallow all codecs and then select the codecs available below to enable them to the user.`,
    'sip.allow': ``,
    'sip.host': ``,
    'sip.sip_group': ``,
    'sip.videosupport': ``,
    'sip.block_call_reg': `You can block calls with a regular expression. For example, if you want block all calls that start with a 9, use regex ^9 `,
    'sip.record_call': ``,
    'sip.techprefix': ``,
    'sip.nat': `Nat. Click here for more info|https://www.voip-info.org/asterisk-sip-nat/`,
    'sip.directmedia': `If enabled, Asterisk tries to redirect the RTP media stream to go directly from the caller to the callee.`,
    'sip.qualify': `Send OPTION to user CONTACT field to qualify the user.`,
    'sip.context': ``,
    'sip.dtmfmode': ``,
    'sip.insecure': `Needs to be NO if the host is dynamic. To IP authenticate set to invite.`,
    'sip.deny': ``,
    'sip.permit': ``,
    'sip.type': ``,
    'sip.allowtransfer': `Enable it to allow transfers between SIP accounts.`,
    'sip.ringfalse': `If YES, generate a ringing tone for the calling party.`,
    'sip.calllimit': `Maximum simultaneous calls`,
    'sip.mohsuggest': ``,
    'sip.url_events': ``,
    'sip.addparameter': ``,
    'sip.amd': ``,
    'sip.type_forward': ``,
    'sip.id_ivr': ``,
    'sip.id_queue': ``,
    'sip.id_sip': ``,
    'sip.extension': ``,
    'sip.dial_timeout': `Timeout in seconds to wait for the call to be picked-up.`,
    'sip.voicemail': ``,
    'sip.voicemail_email': ``,
    'sip.voicemail_password': ``,
    'sip.sipshowpeer': ``,
    //SIP TRACE
    'siptrace.head': ``,
    //ATA LINKSYS
    'sipuras.nserie': `LinkSys serial number`,
    'sipuras.macadr': `LinkSys MAC address`,
    'sipuras.senha_user': `User to set in LinkSys configuration`,
    'sipuras.senha_admin': `Pass to set in LinkSys configuration`,
    'sipuras.antireset': `Prevent resetting LinkSys with *73738#`,
    'sipuras.Enable_Web_Server': `Enabling/Disabling LinkSys configuration WebPage`,
    'sipuras.User_ID_1': `SIP account username`,
    'sipuras.Password_1': `SIP account password`,
    'sipuras.Use_Pref_Codec_Only_1': `Only use the preferred CODEC`,
    'sipuras.Preferred_Codec_1': `Set the preferred CODEC`,
    'sipuras.Register_Expires_1': `Interval in seconds that LinkSys will send a REGISTER to your server. Useful to avoid a loss of connection when you receive a call.`,
    'sipuras.Dial_Plan_1': `Read LinkSys documentation`,
    'sipuras.NAT_Mapping_Enable_1_': ``,
    'sipuras.NAT_Keep_Alive_Enable_1_': ``,
    'sipuras.User_ID_2': ``,
    'sipuras.Password_2': ``,
    'sipuras.Use_Pref_Codec_Only_2': ``,
    'sipuras.Preferred_Codec_2': ``,
    'sipuras.Register_Expires_2': ``,
    'sipuras.Dial_Plan_2': ``,
    'sipuras.NAT_Mapping_Enable_2_': ``,
    'sipuras.NAT_Keep_Alive_Enable_2_': ``,
    'sipuras.STUN_Enable': ``,
    'sipuras.STUN_Test_Enable': ``,
    'sipuras.Substitute_VIA_Addr': ``,
    'sipuras.STUN_Server': ``,
    //SMS
    'sms.id_user': ``,
    'sms.telephone': `Needs to be in E164 format`,
    'sms.sms': ``,
    'sms.sms_from': ``,
    //SMTP
    'smtps.host': ``,
    'smtps.username': ``,
    'smtps.password': ``,
    'smtps.port': ``,
    'smtps.encryption': ``,
    //EMAILS TEMPLATES
    'templatemail.fromname': ``,
    'templatemail.fromemail': ``,
    'templatemail.subject': ``,
    'templatemail.messagehtml': ``,
    'templatemail.status': ``,
    //TRUNKS
    'trunk.id_provider': ``,
    'trunk.trunkcode': ``,
    'trunk.user': `Only used if the authentication is via user and pass.`,
    'trunk.secret': `Only used if the authentication is via user and pass.`,
    'trunk.host': `IP or SIP`,
    'trunk.trunkprefix': `Add a prefix to send to your trunk.`,
    'trunk.removeprefix': `Remove a prefix to send to your trunk.`,
    'trunk.allow': `Select the codecs that are allowed in this trunk.`,
    'trunk.providertech': `You need install appropriate drive to use card like dgv extra Dongle.`,
    'trunk.status': ``,
    'trunk.allow_error': `If YES all calls but ANSWERED and CANCEL will be sent to a backup trunk.`,
    'trunk.register': ``,
    'trunk.register_string': ``,
    'trunk.fromuser': ``,
    'trunk.fromdomain': `Set the Trunk IP or SIP, if required.`,
    'trunk.language': ``,
    'trunk.context': `Only change if you know what you are doing.`,
    'trunk.dtmfmode': `Set default dtmfmode for sending DTMF. Default: rfc2833 Other options: info : SIP INFO messages (application/dtmf-relay) shortinfo : SIP INFO messages (application/dtmf) inband : Inband audio (requires 64 kbit codec -alaw, ulaw) auto : Use rfc2833 if offered, inband otherwise.`,
    'trunk.insecure': ``,
    'trunk.maxuse': `Maximum simultaneous call. If you set it, your server will need to use a lot of resources to control it. Not recommended.`,
    'trunk.nat': ``,
    'trunk.directmedia': ``,
    'trunk.qualify': ``,
    'trunk.type': ``,
    'trunk.disallow': ``,
    'trunk.sendrpid': ``,
    'trunk.addparameter': ``,
    'trunk.port': `If you want to use a different than 5060, you will need open the port in IPTABLES.`,
    'trunk.link_sms': `Set your SMS link here to send SMS. Replace: number variable per %number% and text per %text%. EXAMPLE. Your SMS URL is http://trunkWebSite.com/sendsms.php?user=magnus&pass=billing&number=XXXXXX&sms_text=SSSSSSSSSSS. replace XXXXXX per %number and SSSSSSSSSSS per %text% `,
    'trunk.sms_res': `Leave it empty to not wait URL result. If you want wait the any success message, write here the expected result.`,
    'trunk.sip_config': ``,
    //TRUNK GROUPS
    'trunkgroup.name': ``,
    'trunkgroup.type': ``,
    'trunkgroup.id_trunk': ``,
    //USERS
    'user.username': `Username used to login into the panel.`,
    'user.password': `Password used to login into the panel.`,
    'user.id_group': `There are 3 groups: admin, agent and client. You can create more or edit any of these groups. Each group can have specific permissions. Check the menu Configuration->User Group.`,
    'user.id_group_agent': ``,
    'user.id_plan': `Which plan will be used to bill calls for this user.`,
    'user.language': ``,
    'user.prefix_local': `Prefix rules. Click here for more info|https://www.magnusbilling.org/local_prefix`,
    'user.active': `Only active users can login into the panel and make calls`,
    'user.country': `Used to CID Callback. The country prefix code will be added before the CID to convert the CID to E164`,
    'user.id_offer': `Used to give free minutes. You need to add your package in the menu: Rates->Offer.`,
    'user.cpslimit': `How many Calls Per Second this user can send? The excess will receive CONGESTION.`,
    'user.company_name': ``,
    'user.state_number': ``,
    'user.lastname': ``,
    'user.firstname': ``,
    'user.city': ``,
    'user.state': ``,
    'user.address': ``,
    'user.neighborhood': ``,
    'user.zipcode': ``,
    'user.phone': ``,
    'user.mobile': ``,
    'user.email': ``,
    'user.doc': ``,
    'user.vat': `Used with some payment gateways.`,
    'user.typepaid': ``,
    'user.creditlimit': `If the user is Post-paid, the user will be able to make calls until he reaches this limit.`,
    'user.credit_notification': ``,
    'user.enableexpire': `Makes the user expire at a determined date.`,
    'user.expirationdate': `The date that the user will expire and be deactivated.`,
    'user.record_call': ``,
    'user.mix_monitor_format': `What format will used to record calls. Activate recording in the menu: Users->SIP accounts.`,
    'user.calllimit': `How many simultaneous calls this user can have? The excess will receive CONGESTION.`,
    'user.calllimit_error': ``,
    'user.callshop': ``,
    'user.disk_space': `Insert the amount disk space available to record, in GB. Use -1 to remove the limit.`,
    'user.sipaccountlimit': ``,
    'user.callingcard_pin': `Used to authenticate through CallingCard.`,
    'user.restriction': `Used to restrict dialing. Add the numbers in the menu: Users->Restricted numbers.`,
    'user.transfer_international_profit': ``,
    'user.transfer_flexiload_profit': ``,
    'user.transfer_bkash_profit': ``,
    'user.transfer_dbbl_rocket': ``,
    'user.transfer_dbbl_rocket_profit': ``,
    'user.transfer_show_selling_price': ``,
    //USER CUSTOM RATES
    'userrate.id_prefix': `Select the prefix that you want set the price.`,
    'userrate.rateinitial': `Sell price`,
    'userrate.initblock': `Initial block`,
    'userrate.billingblock': `Increment block`,
    //VOUCHER
    'voucher.credit': `How much credit is this voucher worth?`,
    'voucher.id_plan': `Select the plan that is going to be used to create the user when the voucher is redeemed.`,
    'voucher.language': `Language used to create the user when voucher when the voucher is redeemed.`,
    'voucher.prefix_local': `Local Prefix used to the create user when the voucher is redeemed.`,
    'voucher.quantity': `How many vouchers do you want to generate?`,
    'voucher.tag': ``,
    'voucher.voucher': ``,
});