/**
 * Classe que define a combo "boolean"
 *
 * =======================================
 * ###################################
 * MagnusBilling
 *
 * @package MagnusBilling
 * @author Adilson Leffa Magnus.
 * @copyright Copyright (C) 2005 - 2016 MagnusBilling. All rights reserved.
 * ###################################
 *
 * This software is released under the terms of the GNU Lesser General Public License v3
 * A copy of which is available from http://www.gnu.org/copyleft/lesser.html
 *
 * Please submit bug reports, patches, etc to https://github.com/magnusbilling/mbilling/issues
 * =======================================
 * Magnusbilling.org <info@magnussolution.com>
 * 10/07/2012
 */
Ext.define('MBilling.view.general.BooleanCombo', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.booleancombo',
    fieldLabel: t('status'),
    forceSelection: true,
    editable: false,
    value: 1,
    store: [
        [1, t('active')],
        [0, t('inactive')]
    ]
});
Ext.define('MBilling.view.general.ServicesTypeCombo', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.servicestypecombo',
    fieldLabel: t('status'),
    forceSelection: true,
    editable: false,
    value: 'Custom',
    store: [
        ['disk_space', t('disk_space')],
        ['sipAccountLimit', t('Sip Account Limit')],
        ['calllimit', t('calllimit')],
        ['Custom', t('Custom')]
    ]
});
Ext.define('MBilling.view.general.TypeSipForward', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.typesipforwardcombo',
    fieldLabel: t('Forward'),
    forceSelection: true,
    editable: false,
    value: '',
    store: [
        ['', t('')],
        ['undefined', t('Undefined')],
        ['sip', t('SIP')],
        ['ivr', t('IVR')],
        ['queue', t('Queue')],
        ['group', t('Group')],
        ['number', t('Number')],
        ['hangup', t('Hangup')],
        ['custom', t('Custom')]
    ]
});
Ext.define('MBilling.view.general.TypeDestination', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.typedestinationcombo',
    fieldLabel: t('type'),
    forceSelection: true,
    editable: false,
    value: '',
    store: [
        ['', t('')],
        ['undefined', t('Undefined')],
        ['sip', t('SIP')],
        ['ivr', t('IVR')],
        ['queue', t('Queue')],
        ['group', t('Group')],
        ['number', t('Number')],
        ['repeat', t('Repeat IVR')],
        ['hangup', t('Hangup')],
        ['custom', t('Custom')]
    ]
});
Ext.define('MBilling.view.general.PontoVirgula', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.pontovirgulacombo',
    fieldLabel: t('status'),
    forceSelection: true,
    editable: false,
    value: ',',
    store: [
        [',', ', (' + t('Comma') + ')'],
        [';', '; (' + t('Semicolon') + ')']
    ]
});
Ext.define('MBilling.view.general.StatusCombo', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.statuscombo',
    fieldLabel: t('status'),
    forceSelection: true,
    editable: false,
    value: 1,
    store: [
        [1, t('Active')],
        [0, t('Inactivated')],
        [2, t('Pending')],
        [3, t('Sent')],
        [4, t('Blocked')],
        [5, t('AMD')]
    ]
});
Ext.define('MBilling.view.general.StatusUserCombo', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.statususercombo',
    fieldLabel: t('status'),
    forceSelection: true,
    editable: false,
    value: 1,
    store: [
        [1, t('Active')],
        [0, t('Inactivated')],
        [2, t('Pending')]
    ]
});
Ext.define('MBilling.view.general.CallbackCombo', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.callbackcombo',
    fieldLabel: t('status'),
    forceSelection: true,
    editable: false,
    value: 1,
    store: [
        [1, t('Active')],
        [2, t('Pending')],
        [3, t('Sent')],
        [4, t('Not working')],
        [5, t('Complete')]
    ]
});
Ext.define('MBilling.view.general.TypeNoYes', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.noyescombo',
    fieldLabel: t('typepaid'),
    forceSelection: true,
    editable: false,
    value: 0,
    store: [
        [0, t('no')],
        [1, t('yes')]
    ]
});
Ext.define('MBilling.view.general.TypeYesNo', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.yesnocombo',
    fieldLabel: t('typepaid'),
    forceSelection: true,
    editable: false,
    value: 1,
    store: [
        [0, t('no')],
        [1, t('yes')]
    ]
});
Ext.define('MBilling.view.general.TypeYesNoString', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.yesnostringcombo',
    fieldLabel: t('typepaid'),
    forceSelection: true,
    editable: false,
    value: 'yes',
    store: [
        ['no', t('no')],
        ['yes', t('yes')]
    ]
});
Ext.define('MBilling.view.general.TypeNoYesString', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.noyesstringcombo',
    fieldLabel: t('typepaid'),
    forceSelection: true,
    editable: false,
    value: 'no',
    store: [
        ['no', t('no')],
        ['yes', t('yes')]
    ]
});
Ext.define('MBilling.view.general.Typenumber', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.numbercombo',
    fieldLabel: t('typenumber'),
    forceSelection: true,
    editable: false,
    value: 1,
    store: [
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5]
    ]
});
Ext.define('MBilling.view.general.Typelanguage', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.languagecombo',
    fieldLabel: t('language'),
    forceSelection: true,
    editable: false,
    value: 'en',
    store: [
        ['', t('undefined')],
        ['br', t('Portuguese')],
        ['en', t('English')],
        ['es', t('Spanish')],
        ['ru', t('Russian')]
    ]
});
Ext.define('MBilling.view.general.TypeCampaign', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.campaigntypecombo',
    fieldLabel: t('type'),
    forceSelection: true,
    editable: false,
    value: 1,
    store: [
        [1, t('voice')],
        [0, t('sms')]
    ]
});
Ext.define('MBilling.view.general.TypeFullCampaign', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.campaigntypefullcombo',
    fieldLabel: t('type'),
    forceSelection: true,
    editable: false,
    value: 1,
    store: [
        [1, t('voice')],
        [0, t('sms')]
    ]
});
Ext.define('MBilling.view.general.TypeBoleto', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.boletocombo',
    fieldLabel: t('status'),
    forceSelection: true,
    editable: false,
    value: 'D',
    store: [
        ['D', t('no')],
        ['P', t('yes')]
    ]
});
Ext.define('MBilling.view.general.RestrictionCombo', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.restrictioncombo',
    fieldLabel: t('status'),
    forceSelection: true,
    editable: false,
    value: 0,
    store: [
        [0, t('inactive')],
        [1, t('cantCallRestrictedNumbers')],
        [2, t('canOnlyCallRestrictedNumbers')]
    ]
});
Ext.define('MBilling.view.general.CountryISOCombo', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.countryisocombo',
    forceSelection: true,
    editable: false,
    listeners: {
        focus: function(combo) {
            combo.expand();
        }
    },
    store: [
        ['AFG', t('Afghanistan')],
        ['ALA', t('Åland Islands')],
        ['ALB', t('Albania')],
        ['DZA', t('Algeria')],
        ['ASM', t('American Samoa')],
        ['AND', t('Andorra')],
        ['AGO', t('Angola')],
        ['AIA', t('Anguilla')],
        ['ATA', t('Antarctica')],
        ['ATG', t('Antigua and Barbuda')],
        ['ARG', t('Argentina')],
        ['ARM', t('Armenia')],
        ['ABW', t('Aruba')],
        ['AUS', t('Australia')],
        ['AUT', t('Austria')],
        ['AZE', t('Azerbaijan')],
        ['BHS', t('Bahamas')],
        ['BHR', t('Bahrain')],
        ['BGD', t('Bangladesh')],
        ['BRB', t('Barbados')],
        ['BLR', t('Belarus')],
        ['BEL', t('Belgium')],
        ['BLZ', t('Belize')],
        ['BEN', t('Benin')],
        ['BMU', t('Bermuda')],
        ['BTN', t('Bhutan')],
        ['BOL', t('Bolivia, Plurinational State of')],
        ['BES', t('Bonaire, Sint Eustatius and Saba')],
        ['BIH', t('Bosnia and Herzegovina')],
        ['BWA', t('Botswana')],
        ['BVT', t('Bouvet Island')],
        ['BRL', t('Brazil')],
        ['IOT', t('British Indian Ocean Territory')],
        ['BRN', t('Brunei Darussalam')],
        ['BGR', t('Bulgaria')],
        ['BFA', t('Burkina Faso')],
        ['BDI', t('Burundi')],
        ['KHM', t('Cambodia')],
        ['CMR', t('Cameroon')],
        ['CAN', t('Canada')],
        ['CPV', t('Cape Verde')],
        ['CYM', t('Cayman Islands')],
        ['CAF', t('Central African Republic')],
        ['TCD', t('Chad')],
        ['CHL', t('Chile')],
        ['CHN', t('China')],
        ['CXR', t('Christmas Island')],
        ['CCK', t('Cocos (Keeling) Islands')],
        ['COL', t('Colombia')],
        ['COM', t('Comoros')],
        ['COG', t('Congo')],
        ['COD', t('Congo, the Democratic Republic of the')],
        ['COK', t('Cook Islands')],
        ['CRI', t('Costa Rica')],
        ['CIV', t('Côte dIvoire')],
        ['HRV', t('Croatia')],
        ['CUB', t('Cuba')],
        ['CUW', t('Curaçao')],
        ['CYP', t('Cyprus')],
        ['CZE', t('Czech Republic')],
        ['DNK', t('Denmark')],
        ['DJI', t('Djibouti')],
        ['DMA', t('Dominica')],
        ['DOM', t('Dominican Republic')],
        ['ECU', t('Ecuador')],
        ['EGY', t('Egypt')],
        ['SLV', t('El Salvador')],
        ['GNQ', t('Equatorial Guinea')],
        ['ERI', t('Eritrea')],
        ['EST', t('Estonia')],
        ['ETH', t('Ethiopia')],
        ['FLK', t('Falkland Islands (Malvinas)')],
        ['FRO', t('Faroe Islands')],
        ['FJI', t('Fiji')],
        ['FIN', t('Finland')],
        ['FRA', t('France')],
        ['GUF', t('French Guiana')],
        ['PYF', t('French Polynesia')],
        ['ATF', t('French Southern Territories')],
        ['GAB', t('Gabon')],
        ['GMB', t('Gambia')],
        ['GEO', t('Georgia')],
        ['DEU', t('Germany')],
        ['GHA', t('Ghana')],
        ['GIB', t('Gibraltar')],
        ['GRC', t('Greece')],
        ['GRL', t('Greenland')],
        ['GRD', t('Grenada')],
        ['GLP', t('Guadeloupe')],
        ['GUM', t('Guam')],
        ['GTM', t('Guatemala')],
        ['GGY', t('Guernsey')],
        ['GIN', t('Guinea')],
        ['GNB', t('Guinea-Bissau')],
        ['GUY', t('Guyana')],
        ['HTI', t('Haiti')],
        ['HMD', t('Heard Island and McDonald Islands')],
        ['VAT', t('Holy See (Vatican City State)')],
        ['HND', t('Honduras')],
        ['HKG', t('Hong Kong')],
        ['HUN', t('Hungary')],
        ['ISL', t('Iceland')],
        ['IND', t('India')],
        ['IDN', t('Indonesia')],
        ['IRN', t('Iran, Islamic Republic of')],
        ['IRQ', t('Iraq')],
        ['IRL', t('Ireland')],
        ['IMN', t('Isle of Man')],
        ['ISR', t('Israel')],
        ['ITA', t('Italy')],
        ['JAM', t('Jamaica')],
        ['JPN', t('Japan')],
        ['JEY', t('Jersey')],
        ['JOR', t('Jordan')],
        ['KAZ', t('Kazakhstan')],
        ['KEN', t('Kenya')],
        ['KIR', t('Kiribati')],
        ['PRK', t('Korea, Democratic Peoples Republic of')],
        ['KOR', t('Korea, Republic of')],
        ['KWT', t('Kuwait')],
        ['KGZ', t('Kyrgyzstan')],
        ['LAO', t('Lao Peoples Democratic Republic')],
        ['LVA', t('Latvia')],
        ['LBN', t('Lebanon')],
        ['LSO', t('Lesotho')],
        ['LBR', t('Liberia')],
        ['LBY', t('Libya')],
        ['LIE', t('Liechtenstein')],
        ['LTU', t('Lithuania')],
        ['LUX', t('Luxembourg')],
        ['MAC', t('Macao')],
        ['MKD', t('Macedonia, the former Yugoslav Republic of')],
        ['MDG', t('Madagascar')],
        ['MWI', t('Malawi')],
        ['MYS', t('Malaysia')],
        ['MDV', t('Maldives')],
        ['MLI', t('Mali')],
        ['MLT', t('Malta')],
        ['MHL', t('Marshall Islands')],
        ['MTQ', t('Martinique')],
        ['MRT', t('Mauritania')],
        ['MUS', t('Mauritius')],
        ['MYT', t('Mayotte')],
        ['MEX', t('Mexico')],
        ['FSM', t('Micronesia, Federated States of')],
        ['MDA', t('Moldova, Republic of')],
        ['MCO', t('Monaco')],
        ['MNG', t('Mongolia')],
        ['MNE', t('Montenegro')],
        ['MSR', t('Montserrat')],
        ['MAR', t('Morocco')],
        ['MOZ', t('Mozambique')],
        ['MMR', t('Myanmar')],
        ['NAM', t('Namibia')],
        ['NRU', t('Nauru')],
        ['NPL', t('Nepal')],
        ['NLD', t('Netherlands')],
        ['NCL', t('New Caledonia')],
        ['NZL', t('New Zealand')],
        ['NIC', t('Nicaragua')],
        ['NER', t('Niger')],
        ['NGA', t('Nigeria')],
        ['NIU', t('Niue')],
        ['NFK', t('Norfolk Island')],
        ['MNP', t('Northern Mariana Islands')],
        ['NOR', t('Norway')],
        ['OMN', t('Oman')],
        ['PAK', t('Pakistan')],
        ['PLW', t('Palau')],
        ['PSE', t('Palestinian Territory, Occupied')],
        ['PAN', t('Panama')],
        ['PNG', t('Papua New Guinea')],
        ['PRY', t('Paraguay')],
        ['PER', t('Peru')],
        ['PHL', t('Philippines')],
        ['PCN', t('Pitcairn')],
        ['POL', t('Poland')],
        ['PRT', t('Portugal')],
        ['PRI', t('Puerto Rico')],
        ['QAT', t('Qatar')],
        ['REU', t('Réunion')],
        ['ROU', t('Romania')],
        ['RUS', t('Russian Federation')],
        ['RWA', t('Rwanda')],
        ['BLM', t('Saint Barthélemy')],
        ['SHN', t('Saint Helena, Ascension and Tristan da Cunha')],
        ['KNA', t('Saint Kitts and Nevis')],
        ['LCA', t('Saint Lucia')],
        ['MAF', t('Saint Martin (French part)')],
        ['SPM', t('Saint Pierre and Miquelon')],
        ['VCT', t('Saint Vincent and the Grenadines')],
        ['WSM', t('Samoa')],
        ['SMR', t('San Marino')],
        ['STP', t('Sao Tome and Principe')],
        ['SAU', t('Saudi Arabia')],
        ['SEN', t('Senegal')],
        ['SRB', t('Serbia')],
        ['SYC', t('Seychelles')],
        ['SLE', t('Sierra Leone')],
        ['SGP', t('Singapore')],
        ['SXM', t('Sint Maarten (Dutch part)')],
        ['SVK', t('Slovakia')],
        ['SVN', t('Slovenia')],
        ['SLB', t('Solomon Islands')],
        ['SOM', t('Somalia')],
        ['ZAF', t('South Africa')],
        ['SGS', t('South Georgia and the South Sandwich Islands')],
        ['SSD', t('South Sudan')],
        ['ESP', t('Spain')],
        ['LKA', t('Sri Lanka')],
        ['SDN', t('Sudan')],
        ['SUR', t('Suriname')],
        ['SJM', t('Svalbard and Jan Mayen')],
        ['SWZ', t('Swaziland')],
        ['SWE', t('Sweden')],
        ['CHE', t('Switzerland')],
        ['SYR', t('Syrian Arab Republic')],
        ['TWN', t('Taiwan, Province of China')],
        ['TJK', t('Tajikistan')],
        ['TZA', t('Tanzania, United Republic of')],
        ['THA', t('Thailand')],
        ['TLS', t('Timor-Leste')],
        ['TGO', t('Togo')],
        ['TKL', t('Tokelau')],
        ['TON', t('Tonga')],
        ['TTO', t('Trinidad and Tobago')],
        ['TUN', t('Tunisia')],
        ['TUR', t('Turkey')],
        ['TKM', t('Turkmenistan')],
        ['TCA', t('Turks and Caicos Islands')],
        ['TUV', t('Tuvalu')],
        ['UGA', t('Uganda')],
        ['UKR', t('Ukraine')],
        ['ARE', t('United Arab Emirates')],
        ['GBR', t('United Kingdom')],
        ['USA', t('United States')],
        ['UMI', t('United States Minor Outlying Islands')],
        ['URY', t('Uruguay')],
        ['UZB', t('Uzbekistan')],
        ['VUT', t('Vanuatu')],
        ['VEN', t('Venezuela, Bolivarian Republic of')],
        ['VNM', t('Viet Nam')],
        ['VGB', t('Virgin Islands, British')],
        ['VIR', t('Virgin Islands, U.S.')],
        ['WLF', t('Wallis and Futuna')],
        ['ESH', t('Western Sahara')],
        ['YEM', t('Yemen')],
        ['ZMB', t('Zambia')],
        ['ZWE', t('Zimbabwe')]
    ]
});
Ext.define('MBilling.view.general.CountryCombo', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.countrycombo',
    fieldLabel: t('Country'),
    forceSelection: true,
    editable: true,
    allowBlank: true,
    listeners: {
        focus: function(combo) {
            combo.expand();
        }
    },
    store: [
        ['', t('Select')],
        ['93', t('Afghanistan')],
        ['355', t('Albania')],
        ['213', t('Algeria')],
        ['684', t('American Samoa')],
        ['376', t('Andorra')],
        ['244', t('Angola')],
        ['1264', t('Anguilla')],
        ['672', t('Antarctica')],
        ['1268', t('Antigua And Barbuda')],
        ['54', t('Argentina')],
        ['374', t('Armenia')],
        ['297', t('Aruba')],
        ['61', t('Australia')],
        ['43', t('Austria')],
        ['994', t('Azerbaijan')],
        ['1242', t('Bahamas')],
        ['973', t('Bahrain')],
        ['880', t('Bangladesh')],
        ['1246', t('Barbados')],
        ['375', t('Belarus')],
        ['32', t('Belgium')],
        ['501', t('Belize')],
        ['229', t('Benin')],
        ['1441', t('Bermuda')],
        ['975', t('Bhutan')],
        ['591', t('Bolivia')],
        ['387', t('Bosnia And Herzegovina')],
        ['267', t('Botswana')],
        ['55', t('Brazil')],
        ['1284', t('British Indian Ocean Territory')],
        ['673', t('Brunei Darussalam')],
        ['359', t('Bulgaria')],
        ['226', t('Burkina Faso')],
        ['257', t('Burundi')],
        ['855', t('Cambodia')],
        ['237', t('Cameroon')],
        ['238', t('Cape Verde')],
        ['1345', t('Cayman Islands')],
        ['236', t('Central African Republic')],
        ['235', t('Chad')],
        ['56', t('Chile')],
        ['86', t('China')],
        ['618', t('Christmas Island')],
        ['61', t('Cocos (Keeling); Islands')],
        ['57', t('Colombia')],
        ['269', t('Comoros')],
        ['242', t('Congo')],
        ['243', t('Congo, The Democratic Republic Of The')],
        ['682', t('Cook Islands')],
        ['506', t('Costa Rica')],
        ['385', t('Croatia')],
        ['53', t('Cuba')],
        ['357', t('Cyprus')],
        ['420', t('Czech Republic')],
        ['45', t('Denmark')],
        ['253', t('Djibouti')],
        ['1767', t('Dominica')],
        ['1809', t('Dominican Republic')],
        ['593', t('Ecuador')],
        ['20', t('Egypt')],
        ['503', t('El Salvador')],
        ['240', t('Equatorial Guinea')],
        ['291', t('Eritrea')],
        ['372', t('Estonia')],
        ['251', t('Ethiopia')],
        ['500', t('Falkland Islands (Malvinas)')],
        ['298', t('Faroe Islands')],
        ['679', t('Fiji')],
        ['358', t('Finland')],
        ['33', t('France')],
        ['596', t('French Guiana')],
        ['594', t('French Polynesia')],
        ['689', t('French Southern Territories')],
        ['241', t('Gabon')],
        ['220', t('Gambia')],
        ['995', t('Georgia')],
        ['49', t('Germany')],
        ['233', t('Ghana')],
        ['350', t('Gibraltar')],
        ['30', t('Greece')],
        ['299', t('Greenland')],
        ['1473', t('Grenada')],
        ['590', t('Guadeloupe')],
        ['1671', t('Guam')],
        ['502', t('Guatemala')],
        ['224', t('Guinea')],
        ['245', t('Guinea-Bissau')],
        ['592', t('Guyana')],
        ['509', t('Haiti')],
        ['504', t('Honduras')],
        ['852', t('Hong Kong')],
        ['36', t('Hungary')],
        ['354', t('Iceland')],
        ['91', t('India')],
        ['62', t('Indonesia')],
        ['98', t('Iran, Islamic Republic Of')],
        ['964', t('Iraq')],
        ['353', t('Ireland')],
        ['972', t('Israel')],
        ['39', t('Italy')],
        ['1876', t('Jamaica')],
        ['81', t('Japan')],
        ['962', t('Jordan')],
        ['77', t('Kazakhstan')],
        ['254', t('Kenya')],
        ['686', t('Kiribati')],
        ['850', t('Korea, Democratic Peoples Republic Of')],
        ['82', t('Korea, Republic of')],
        ['965', t('Kuwait')],
        ['996', t('Kyrgyzstan')],
        ['856', t('Lao Peoples Democratic Republic')],
        ['371', t('Latvia')],
        ['961', t('Lebanon')],
        ['266', t('Lesotho')],
        ['231', t('Liberia')],
        ['218', t('Libyan Arab Jamahiriya')],
        ['423', t('Liechtenstein')],
        ['370', t('Lithuania')],
        ['352', t('Luxembourg')],
        ['853', t('Macao')],
        ['389', t('Macedonia, The Former Yugoslav Republic Of')],
        ['261', t('Madagascar')],
        ['265', t('Malawi')],
        ['60', t('Malaysia')],
        ['960', t('Maldives')],
        ['223', t('Mali')],
        ['356', t('Malta')],
        ['692', t('Marshall islands')],
        ['596', t('Martinique')],
        ['222', t('Mauritania')],
        ['230', t('Mauritius')],
        ['269', t('Mayotte')],
        ['52', t('Mexico')],
        ['691', t('Micronesia, Federated States Of')],
        ['1808', t('Moldova, Republic Of')],
        ['377', t('Monaco')],
        ['976', t('Mongolia')],
        ['1664', t('Montserrat')],
        ['212', t('Morocco')],
        ['258', t('Mozambique')],
        ['95', t('Myanmar')],
        ['264', t('Namibia')],
        ['674', t('Nauru')],
        ['977', t('Nepal')],
        ['31', t('Netherlands')],
        ['599', t('Netherlands Antilles')],
        ['687', t('New Caledonia')],
        ['64', t('New Zealand')],
        ['505', t('Nicaragua')],
        ['227', t('Niger')],
        ['234', t('Nigeria')],
        ['683', t('Niue')],
        ['672', t('Norfolk Island')],
        ['1670', t('Northern Mariana Islands')],
        ['47', t('Norway')],
        ['968', t('Oman')],
        ['92', t('Pakistan')],
        ['680', t('Palau')],
        ['970', t('Palestinian Territory, Occupied')],
        ['507', t('Panama')],
        ['675', t('Papua New Guinea')],
        ['595', t('Paraguay')],
        ['51', t('Peru')],
        ['63', t('Philippines')],
        ['48', t('Poland')],
        ['351', t('Portugal')],
        ['1787', t('Puerto Rico')],
        ['974', t('Qatar')],
        ['262', t('Reunion')],
        ['40', t('Romania')],
        ['7', t('Russian Federation')],
        ['250', t('Rwanda')],
        ['290', t('SaINT Helena')],
        ['1869', t('SaINT Kitts And Nevis')],
        ['1758', t('SaINT Lucia')],
        ['508', t('SaINT Pierre And Miquelon')],
        ['1784', t('SaINT Vincent And The Grenadines')],
        ['685', t('Samoa')],
        ['378', t('San Marino')],
        ['239', t('SÃ£o TomÃ© And Principe')],
        ['966', t('Saudi Arabia')],
        ['221', t('Senegal')],
        ['248', t('Seychelles')],
        ['232', t('Sierra Leone')],
        ['65', t('Singapore')],
        ['421', t('Slovakia')],
        ['386', t('Slovenia')],
        ['677', t('Solomon Islands')],
        ['252', t('Somalia')],
        ['27', t('South Africa')],
        ['34', t('Spain')],
        ['94', t('Sri Lanka')],
        ['249', t('Sudan')],
        ['597', t('Suriname')],
        ['268', t('Swaziland')],
        ['46', t('Sweden')],
        ['41', t('Switzerland')],
        ['963', t('Syrian Arab Republic')],
        ['886', t('Taiwan, Province Of China')],
        ['992', t('Tajikistan')],
        ['255', t('Tanzania, United Republic Of')],
        ['66', t('Thailand')],
        ['670', t('Timor-Leste')],
        ['228', t('Togo')],
        ['690', t('Tokelau')],
        ['676', t('Tonga')],
        ['1868', t('Trinidad And Tobago')],
        ['216', t('Tunisia')],
        ['90', t('Turkey')],
        ['993', t('Turkmenistan')],
        ['1649', t('Turks And Caicos Islands')],
        ['688', t('Tuvalu')],
        ['256', t('Uganda')],
        ['380', t('Ukraine')],
        ['971', t('United Arab Emirates')],
        ['44', t('United Kingdom')],
        ['1', t('United States/Canada')],
        ['598', t('Uruguay')],
        ['998', t('Uzbekistan')],
        ['678', t('Vanuatu')],
        ['58', t('Venezuela')],
        ['84', t('Vietnam')],
        ['1284', t('Virgin Islands, British')],
        ['808', t('Virgin Islands, U.S.')],
        ['681', t('Wallis And Futuna')],
        ['967', t('Yemen')],
        ['260', t('Zambia')],
        ['263', t('Zimbabwe')],
        ['35818', t('Aland Islands')],
        ['441481', t('Guernsey')],
        ['441624', t('Isle of Man')],
        ['441534', t('Jersey')],
        ['382', t('Montenegro, Republic of')],
        ['381', t('Serbia, Republic of')]
    ]
});